{
 "title": "EON main",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "qmsInstanceName",
    "label": "QMS Instance name",
    "query": "eon-dev, eon-uat, eon-test, eon-prod"
   },
   { "name": "qmsDatasource", "label": "QMS Datasource", "query": "prometheus" },
   { "name": "lokiInstance", "label": "Loki Instance", "query": "loki" },
   { "name": "qmsDomainSuffix", "query": ".quadient.cloud" },
   { "name": "qmsCustomerName", "query": "EON" },
   { "name": "qmsEntitlementName", "label": "QMS Entitlement Name", "query": "EON PROD QMS, EON Non-PROD QMS" }
  ]
 },
 "panels": [
  {
   "title": "Last login per user",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"audit_interactive\"} |= `LOGIN_SUCCESS` | json"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Linux VM Overview", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 } },
  { "title": "Inspire heartbeat", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 } },
  { "title": "Interactive Package", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 10, "x": 0, "y": 26 } },
  { "title": "Audit Logs", "type": "library-panel-ref", "gridPos": { "h": 3, "w": 5, "x": 10, "y": 26 } },
  { "title": "RHEL security updates", "type": "library-panel-ref", "gridPos": { "h": 13, "w": 9, "x": 15, "y": 26 } },
  { "title": "Number of requests over 30m ", "type": "library-panel-ref", "gridPos": { "h": 3, "w": 5, "x": 10, "y": 29 } },
  {
   "title": "Number of produced pages - departments",
   "type": "library-panel-ref",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 31 }
  },
  { "title": "Number of requests over 3s ", "type": "library-panel-ref", "gridPos": { "h": 3, "w": 5, "x": 10, "y": 32 } },
  {
   "title": "Backups Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily VM/Disk Azure backup",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n    and not(\r\n        BackupItemFriendlyName1 contains \"test\" or\r\n        BackupItemFriendlyName1 contains \"qa\"\r\n    )\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resources": [
         "/subscriptions/2305a810-3543-4007-b1ac-5535cf9ee314/resourceGroups/hmsrg-eon-hub-prod/providers/Microsoft.RecoveryServices/vaults/rsv-eon-prod"
        ],
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Azure VM/Disks backup health",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "",
        "resources": [
         "/subscriptions/6b7f3c14-d3a0-4dd2-9990-d079120c95ad/resourceGroups/hmsrg-aware-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-aware-nonprod"
        ]
       },
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "healthStatus",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "dataSourceType",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "backupInstanceName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "BackupHealthEvent",
        "metricNamespace": "microsoft.recoveryservices/vaults",
        "region": "germanywestcentral",
        "resources": [
         {
          "metricNamespace": "Microsoft.RecoveryServices/vaults",
          "region": "germanywestcentral",
          "resourceGroup": "hmsrg-eon-hub-prod",
          "resourceName": "rsv-eon-prod",
          "subscription": "2305a810-3543-4007-b1ac-5535cf9ee314"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "2305a810-3543-4007-b1ac-5535cf9ee314"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    { "title": "CPU Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 34 } },
    { "title": "Memory Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 8, "y": 34 } },
    { "title": "DiskSpace usage", "type": "library-panel-ref", "gridPos": { "h": 33, "w": 8, "x": 16, "y": 34 } },
    { "title": "Average CPU Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 68 } },
    { "title": "File Shares usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 8, "y": 68 } },
    { "title": "Network Traffic", "type": "library-panel-ref", "gridPos": { "h": 13, "w": 16, "x": 0, "y": 78 } }
   ]
  },
  {
   "title": "Scalers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    { "title": "Failed jobs  ", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 } },
    { "title": "Completed jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 } },
    { "title": "Canceled jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 } },
    {
     "title": "Scaler Jobs per Workflow (Completed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 }
    },
    {
     "title": "Scaler Jobs per Workflow (Failed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 }
    },
    { "title": "Processing jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 } },
    { "title": "Average IPS Queue Waiting Time", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 } },
    { "title": "Scaler workflows", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 } }
   ]
  },
  {
   "title": "Interactives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    { "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 445 } },
    { "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 445 } },
    { "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 445 } },
    { "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 467 } },
    { "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 467 } },
    { "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 467 } }
   ]
  },
  {
   "title": "Scaler JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    { "title": "Scaler heap used", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 160 } },
    { "title": "Scaler start time", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 6, "y": 160 } },
    { "title": "JVM Heap Scaler", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 12, "y": 160 } },
    { "title": "Scaler thread states", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 160 } }
   ]
  },
  {
   "title": "Interactive JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    { "title": "Interactive heap used", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 161 } },
    { "title": "Interactive start time", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 6, "y": 161 } },
    { "title": "JVM Heap interactive", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 12, "y": 161 } },
    { "title": "Interactive thread states", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 161 } }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    { "title": "Scaler Logs", "type": "library-panel-ref", "gridPos": { "h": 15, "w": 24, "x": 0, "y": 162 } },
    { "title": "Scaler ICM Logs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 } },
    { "title": "Scaler IPS Logs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 } },
    { "title": "Interactive Logs", "type": "library-panel-ref", "gridPos": { "h": 13, "w": 24, "x": 0, "y": 185 } },
    { "title": "Interactive ICM Logs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 } },
    { "title": "Interactive  IPS Logs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 } }
   ]
  }
 ]
}