{
 "title": "KPI Dashboard - All Customers",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Tickets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average first response",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(firstresponse) AS \"firstresponse\"\nFROM case_details\nWHERE\n  $__timeFilter(created) AND origin != 'Internal'"
    }
   ]
  },
  {
   "title": "Tickets by priority",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT priority, COUNT(*) AS count\r\nFROM case_details\r\nWHERE created BETWEEN $__timeFrom() AND $__timeTo() AND origin != 'Internal'\r\nGROUP BY priority\r\nORDER BY priority DESC;"
    }
   ]
  },
  {
   "title": "Cases with incorrect tags",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  CAST(casenumber as text) \"Case Number\",\n  subject,\n  tagPrimary as \"Primary tag\",\n  tagSecondary as \"Secondary tag\"\n\nFROM case_details\nWHERE\n  $__timeFilter(created)\n  AND (tagPrimary IS NULL OR tagSecondary is NULL)\nORDER BY \"casenumber\""
    }
   ]
  },
  {
   "title": "Tickets by tags",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT tagPrimary, tagSecondary, COUNT(*) AS \"No Tags\"\r\nFROM case_details\r\nWHERE created BETWEEN $__timeFrom() AND $__timeTo() AND origin != 'Internal'\r\nGROUP BY tagPrimary, tagSecondary\r\nORDER BY tagPrimary, tagSecondary DESC;"
    }
   ]
  },
  {
   "title": "Cases above 90% of SLA",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  CAST(casenumber as text) \"Case Number\",\n  subject,\n  ROUND((firstresponse::numeric / responsesla::numeric) * 100, 2) || '%' AS \"First Response / SLA %\",\n  ROUND((resolution::numeric / resolutionsla::numeric) * 100, 2) || '%'  AS \"Resolution / SLA %\"\nFROM case_details\nWHERE\n  $__timeFilter(created) AND\n  ((firstresponse::numeric / responsesla::numeric) * 100 > 90 OR (resolution::numeric / resolutionsla::numeric) * 100 > 90) and origin != 'Internal'\nORDER BY \"casenumber\""
    }
   ]
  },
  {
   "title": "Avg resolution by priority",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT priority, avg(resolution) AS count\r\nFROM case_details\r\nWHERE created BETWEEN $__timeFrom() AND $__timeTo()  AND origin != 'Internal'\r\nGROUP BY priority\r\nORDER BY priority DESC;"
    }
   ]
  },
  {
   "title": "Open Cases",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  CAST(casenumber as text) \"Case Number\",\n  priority AS \"Priority\",\n  subject,\n  tagPrimary as \"Primary tags\",\n  tagSecondary as \"Secondary tags\",\n  status,\n  firstresponse * interval '1 sec' as \"First response\",\n  CONCAT(\n    (resolution / 86400)::integer, 'd ',\n    ((resolution % 86400) / 3600)::integer, 'h ',\n    ((resolution % 3600) / 60)::integer, 'm ',\n    (resolution % 60), 's'\n  ) as \"Resolution time*\"\nFROM case_details\nWHERE\n  $__timeFilter(created) AND\n  status != 'Closed' AND\n  origin != 'Internal'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Open Internal Cases",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  CAST(casenumber as text) \"Case Number\",\n  priority AS \"Priority\",\n  subject,\n  tagPrimary as \"Primary tags\",\n  tagSecondary as \"Secondary tags\",\n  status\nFROM case_details\nWHERE\n  $__timeFilter(created) AND\n  status != 'Closed' AND\n  origin = 'Internal'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "All Cases",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CAST(casenumber as text) \"Case Number\",\r\n  priority AS \"Priority\",\r\n  subject,\r\n  tagPrimary as \"Primary tag\",\r\n  tagSecondary as \"Secondary tag\",\r\n  status,\r\n  CONCAT(\r\n    (firstresponse / 86400)::integer, 'd ',\r\n    ((firstresponse % 86400) / 3600)::integer, 'h ',\r\n    ((firstresponse % 3600) / 60)::integer, 'm ',\r\n    (firstresponse % 60), 's'\r\n  ) as \"First response\",\r\n  CASE WHEN responsesla is not null THEN CONCAT(\r\n    (responsesla / 86400)::integer, 'd ',\r\n    ((responsesla % 86400) / 3600)::integer, 'h ',\r\n    ((responsesla % 3600) / 60)::integer, 'm ',\r\n    (responsesla % 60), 's')\r\n  END as \"Response time SLA\",\r\n  CONCAT(\r\n    (resolution / 86400)::integer, 'd ',\r\n    ((resolution % 86400) / 3600)::integer, 'h ',\r\n    ((resolution % 3600) / 60)::integer, 'm ',\r\n    (resolution % 60), 's'\r\n  ) as \"Resolution time\",\r\n  CASE WHEN resolutionsla is not null THEN CONCAT(\r\n    (resolutionsla / 86400)::integer, 'd ',\r\n    ((resolutionsla % 86400) / 3600)::integer, 'h ',\r\n    ((resolutionsla % 3600) / 60)::integer, 'm ',\r\n    (resolutionsla % 60), 's')\r\n  END as \"Resolution time SLA\",\r\n  ROUND((firstresponse::numeric / responsesla::numeric) * 100, 2) || '%' AS \"First Response / SLA %\",\r\n  ROUND((resolution::numeric / resolutionsla::numeric) * 100, 2) || '%'  AS \"Resolution / SLA %\",\r\n  slaexcluded as \"Excluded from SLA\"\r\n  \r\nFROM case_details\r\nWHERE\r\n  $__timeFilter(created) AND\r\n  origin != 'Internal'\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "All Internal Cases",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CAST(casenumber as text) \"Case Number\",\r\n  priority AS \"Priority\",\r\n  subject,\r\n  tagPrimary as \"Primary tag\",\r\n  tagSecondary as \"Secondary tag\",\r\n  status  \r\nFROM case_details\r\nWHERE\r\n  $__timeFilter(created) AND\r\n  origin = 'Internal'\r\nORDER BY 1"
    }
   ]
  },
  { "title": "First Responders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Average first response",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT\n  firstresponder, avg(firstresponse) * interval '1 sec' AS \"First response\"\nFROM case_firstresponders\nWHERE\n  $__timeFilter(created) AND origin != 'Internal' AND accountid != '0013k00003MRvgCAAT'\ngroup by firstresponder\n"
    }
   ]
  },
  {
   "title": "Case First Responders",
   "type": "table",
   "gridPos": { "h": 16, "w": 15, "x": 9, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT\n  casenumber, customername, firstresponder, firstresponse  * interval '1 sec' as \"First response\"\nFROM case_firstresponders\nWHERE\n  $__timeFilter(created) AND origin != 'Internal' AND accountid != '0013k00003MRvgCAAT'\n"
    }
   ]
  },
  {
   "title": "Breached First response KPI",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT\n  casenumber, firstresponder, firstresponse  * interval '1 sec' as \"First response\"\nFROM case_firstresponders\nWHERE\n  $__timeFilter(created) AND origin != 'Internal' AND accountid != '0013k00003MRvgCAAT' and firstresponse > 1799\n"
    }
   ]
  }
 ]
}