{
 "title": "QBR Reports - Customer",
 "time": { "from": "2023-09-01T00:00:00.000Z", "to": "2023-12-31T23:59:59.000Z" },
 "panels": [
  {
   "title": "Avg. memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (sum without(instance,cpu) (node_memory_MemAvailable_bytes{instanceName=\"cnjdoh-prod\",instance=~\"interactive.*\"}) / sum without(instance,cpu) (node_memory_MemTotal_bytes{instanceName=\"cnjdoh-prod\",instance=~\"interactive.*\"})) *100",
     "legendFormat": "interactives"
    },
    {
     "expr": "100 - (sum without(instance,cpu) (node_memory_MemAvailable_bytes{instanceName=\"cnjdoh-prod\",instance=~\"scaler.*\"}) / sum without(instance,cpu) (node_memory_MemTotal_bytes{instanceName=\"cnjdoh-prod\",instance=~\"scaler.*\"})) *100",
     "legendFormat": "scalers"
    }
   ]
  },
  {
   "title": "Avg. CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg without(instance, cpu) (irate(node_cpu_seconds_total{mode=\"idle\",customerName=\"C-NJ-DOH\", instance=~\"scaler.*\", instanceName=\"cnjdoh-prod\"}[5m])) * 100",
     "legendFormat": "Scalers"
    },
    {
     "expr": "100 - avg without(instance, cpu) (irate(node_cpu_seconds_total{mode=\"idle\",customerName=\"C-NJ-DOH\", instance=~\"interactive.*\", instanceName=\"cnjdoh-prod\"}[5m])) * 100",
     "legendFormat": "Interactives"
    }
   ]
  },
  {
   "title": "Completed jobs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "last_over_time(sum by(group) (increase(scaler_job_runs_total{instance=~\"scaler.*\", instanceName=\"cnjdoh-prod\", status=\"completed\"}[24h]))[1d:1d])",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}