{
 "title": "Prometheus Internal Metrics",
 "tags": [
  "prometheus",
  "internal"
 ],
 "refresh": "30s",
 "panels": [
  {
   "title": "Query Log Enabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_Inactive_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bar chart",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 0 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scrape Series Added",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "targets": [
    { "expr": "rate(scrape_series_added[1m])", "legendFormat": "Series Added" }
   ]
  }
 ]
}