{
 "title": "GAFG-PROD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Avaliability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server's Availability",
     "type": "stat",
     "description": "NOTE: The monitoring server needs to be ON to show Automation traffic lights properly. \n",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(up{job=~\".*vm\", instanceName=\"gafg-prod\"}, \"instance\", \"approval.gafg-prod.quadient.cloud\", \"instance\", \"localhost:9182\")",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Server's Percentage Availability",
     "type": "stat",
     "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"gafg-prod\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"gafg-prod\"}[$__range])))[$__range:1m]) * 100 , \"instance\", \"approval.gafg-prod.quadient.cloud\", \"instance\", \"localhost:9182\")",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Inspire heartbeat",
     "type": "stat",
     "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
     "gridPos": { "h": 17, "w": 3, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(windows_service_state{state=\"running\", name=~\".*(inspire|mssqlserver|w3svc).*\",name!=\"mssqlserverolapservice\", instanceName=\"gafg-prod\"}, \"instance\", \"approval.gafg-prod.quadient.cloud\", \"instance\", \"localhost:9182\")",
       "legendFormat": "{{instance}}: {{ name}}"
      }
     ]
    },
    {
     "title": "Inspire heartbeat percentage",
     "type": "stat",
     "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
     "gridPos": { "h": 17, "w": 7, "x": 13, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(avg_over_time((sum without() (windows_service_state{state=\"running\", name=~\".*(inspire|mssqlserver|w3svc).*\",name!=\"mssqlserverolapservice\", instanceName=\"gafg-prod\"}) or (0 * sum_over_time(windows_service_state{state=\"running\", name=~\".*(inspire|mssqlserver|w3svc).*\",name!=\"mssqlserverolapservice\", instanceName=\"gafg-prod\"}[$__range])))[$__range:1m]) * 100, \"instance\", \"approval.gafg-prod.quadient.cloud\", \"instance\", \"localhost:9182\")",
       "legendFormat": "{{instance}}: {{ name}}"
      }
     ]
    },
    { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 17, "w": 4, "x": 20, "y": 1 } },
    {
     "title": "Appgw Health",
     "type": "stat",
     "description": "gafg-prod applicaiton gateway healt",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 117 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "UnhealthyHostCount",
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-gafg-hub-prod",
        "resourceName": "appgw-gafg-prod",
        "timeGrain": "auto"
       },
       "subscription": "0fc63408-3977-498b-901f-7ab244989b22",
       "subscriptions": [
        "8fe0a41f-d0e7-4659-af05-5b6675f2fdc2"
       ]
      }
     ]
    },
    {
     "title": "PAW Avaliability",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 121 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "VmAvailabilityMetric",
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "eastus",
        "resources": [
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "eastus",
          "resourceGroup": "hmsrg-gafg-paw",
          "resourceName": "vm-gafg-paw-01",
          "subscription": "0fc63408-3977-498b-901f-7ab244989b22"
         },
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "eastus",
          "resourceGroup": "hmsrg-gafg-paw",
          "resourceName": "vm-gafg-paw-02",
          "subscription": "0fc63408-3977-498b-901f-7ab244989b22"
         },
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "eastus",
          "resourceGroup": "HMSRG-GAFG-PAW",
          "resourceName": "VM-GAFG-PAW-03",
          "subscription": "0fc63408-3977-498b-901f-7ab244989b22"
         }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "0fc63408-3977-498b-901f-7ab244989b22"
      }
     ]
    },
    {
     "title": "Daily Backups",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 127 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hms_backup_info_daily_all{instanceName=\"\",backupType=\"daily\"})"
      }
     ]
    },
    { "title": "Shared Panels", "type": "dashlist", "gridPos": { "h": 6, "w": 7, "x": 3, "y": 127 } },
    {
     "title": "Weekly Backups",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 130 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hms_backup_info_weekly_all{instanceName=\"\",backupType=\"weekly\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily VM/Disk Azure backup",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resource": "/subscriptions/0fc63408-3977-498b-901f-7ab244989b22/resourceGroups/hmsrg-gafg-hub-prod/providers/Microsoft.RecoveryServices/vaults/rsv-gafg-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Azure VM/Disks backup health",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(7d)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resource": "/subscriptions/de74e022-0016-4972-ac5a-d17f177ed92d/resourceGroups/hmsrg-gfbank-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-gfbank-nonprod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [
         {
          "dimension": "healthStatus",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "backupInstanceName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "BackupHealthEvent",
        "metricNamespace": "microsoft.recoveryservices/vaults",
        "resourceGroup": "hmsrg-gafg-hub-prod",
        "resourceName": "rsv-gafg-prod",
        "timeGrain": "auto"
       },
       "subscription": "0fc63408-3977-498b-901f-7ab244989b22"
      }
     ]
    },
    {
     "title": "Daily (Monday - Saturday)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 120 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info{containerName=~\".*disks$\",instanceName=\"\",backupType=\"daily\"}",
       "legendFormat": "{{backupItem}}-disk"
      }
     ]
    },
    {
     "title": "Weekly (4 Sundays)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 120 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info{containerName=~\".*disks$\",instanceName=\"\",backupType=\"weekly\"}",
       "legendFormat": "{{backupItem}}-disk"
      }
     ]
    },
    {
     "title": "Daily (Monday - Saturday)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 120 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info{containerName=~\".*db$\",instanceName=\"\",backupType=\"daily\"}",
       "legendFormat": "{{backupItem}}-database"
      }
     ]
    },
    {
     "title": "Weekly (4 Sundays)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 120 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info{containerName=~\".*db$\",instanceName=\"\",backupType=\"weekly\"}",
       "legendFormat": "{{backupItem}}-database"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (virtualMachine) (irate(windows_cpu_time_total{mode=\"idle\"}[5m]))* 100)",
       "legendFormat": "approval0"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(windows_net_bytes_received_total{instanceName=\"gafg-prod\"}[5m])",
       "legendFormat": "approva0 recv"
      },
      {
       "expr": "rate(windows_net_bytes_sent_total{instanceName=\"gafg-prod\"}[5m])",
       "legendFormat": "approval0 trans"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (windows_os_virtual_memory_free_bytes{instanceName=\"gafg-prod\"} / windows_os_virtual_memory_bytes{instanceName=\"gafg-prod\"})*100",
       "legendFormat": "approval0"
      }
     ]
    },
    {
     "title": "Disk Space Used Designer VM",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((windows_logical_disk_free_bytes{volume=~\"C:|S:|F:|G:\", instanceName=\"gafg-prod\"} * 100) / windows_logical_disk_size_bytes{volume=~\"C:|S:|F:|G:\", instanceName=\"gafg-prod\"})",
       "legendFormat": "{{volume}}"
      }
     ]
    }
   ]
  },
  { "title": "Scaler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Failed jobs",
   "type": "timeseries",
   "description": "Indicates jobs that failed to process.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_job_runs_total{customerName=\"Globalatlantic\", status=\"failed\"}[5m])",
     "legendFormat": "approval0-scaler/{{group}}"
    }
   ]
  },
  {
   "title": "Completed jobs",
   "type": "timeseries",
   "description": "Indicates jobs that have been successfully processed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_job_runs_total{customerName=\"Globalatlantic\", status=\"completed\"}[5m])",
     "legendFormat": "approval0-scaler/{{group}}"
    }
   ]
  },
  {
   "title": "Canceled jobs",
   "type": "timeseries",
   "description": "Indicates jobs that have been successfully processed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_job_runs_total{status=\"canceled\", customerName=\"Globalatlantic\"}[5m])",
     "legendFormat": "approval0-scaler/{{group}}"
    }
   ]
  },
  {
   "title": "Processing jobs",
   "type": "timeseries",
   "description": "Provides the number of all the jobs that are currently being processed.\nUse this metric to create custom alerts about the number of currently processed jobs that is rapidly growing. That could indicate issues, for example, with jobs being stuck in a loop in the Script workflow module.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_processing_jobs_total{customerName=\"Globalatlantic\"}[5m])",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Average IPS Queue Waiting Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(scaler_processing_jobs_total{customerName=\"Globalatlantic\"}[5m])",
     "legendFormat": "approval0-scaler/{{group}}"
    }
   ]
  },
  {
   "title": "Scaler workflows",
   "type": "timeseries",
   "description": "Provides the number of deployed workflows for each workflow type, and for each of the following statuse",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scaler_deployed_workflows_total{customerName=\"Globalatlantic\"}",
     "legendFormat": "approval0-scaler/{{ group }}: {{ status }}"
    }
   ]
  },
  { "title": "Scaler JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Scaler heap used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"heap\",customerName=\"Globalatlantic\"})*100/sum(jvm_memory_bytes_max{area=\"heap\",customerName=\"Globalatlantic\"})",
     "legendFormat": "Approval0-scaler"
    }
   ]
  },
  {
   "title": "Scaler start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{customerName=\"Globalatlantic\",job=\"gafg-prod-approval-scaler\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Heap Scaler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"Globalatlantic\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{customerName=\"Globalatlantic\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{customerName=\"Globalatlantic\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Scaler thread states",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(state) (jvm_threads_state{customerName=\"Globalatlantic\"})",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}