{
 "title": "Prudential main",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "qmsInstanceName",
    "label": "QMS Instance name",
    "query": "prudential-dev, prudential-perf, prudential-prod, prudential-stage, prudential-test, prudential-uat"
   },
   { "name": "qmsDatasource", "label": "QMS Datasource", "query": "prometheus" },
   { "name": "lokiInstance", "label": "Loki Instance", "query": "loki" },
   { "name": "qmsDomainSuffix", "query": ".quadient.cloud" },
   { "name": "qmsCustomerName", "query": "Prudential" }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Linux VM Overview", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 } },
  { "title": "Inspire heartbeat", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 } },
  { "title": "RHEL security updates", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 15, "x": 0, "y": 18 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 14, "w": 9, "x": 15, "y": 18 } },
  { "title": "Number of requests over 30m ", "type": "library-panel-ref", "gridPos": { "h": 3, "w": 5, "x": 0, "y": 26 } },
  { "title": "Number of requests over 3s ", "type": "library-panel-ref", "gridPos": { "h": 3, "w": 5, "x": 5, "y": 26 } },
  { "title": "Audit Logs", "type": "library-panel-ref", "gridPos": { "h": 3, "w": 5, "x": 10, "y": 26 } },
  {
   "title": "Scaler Job Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    { "title": "Scaler jobs over 3s percentage", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 } },
    { "title": "Scaler jobs over 5s percentage", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 } },
    {
     "title": "Appgw number of requests over 3s",
     "type": "library-panel-ref",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 }
    },
    { "title": "Scaler jobs over 3 seconds", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 } },
    { "title": "Scaler jobs over 5 seconds", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 } },
    {
     "title": "Appgw number of requests over 5s",
     "type": "library-panel-ref",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 }
    },
    {
     "title": "Appgw number of requests over 3s - Detail",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 }
    },
    { "title": "Request Count", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 } },
    {
     "title": "SUCCESSFUL - Overall average request time in (s)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 }
    },
    {
     "title": "FAILED - Overall average request time in (s)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 }
    }
   ]
  },
  {
   "title": "Backups Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    { "type": "library-panel-ref", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1336 } },
    { "type": "library-panel-ref", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1336 } }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    { "title": "CPU Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 66 } },
    { "title": "Memory Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 8, "y": 66 } },
    { "title": "DiskSpace usage", "type": "library-panel-ref", "gridPos": { "h": 33, "w": 8, "x": 16, "y": 66 } },
    { "title": "Average CPU Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 76 } },
    { "title": "File Shares usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 8, "y": 76 } },
    { "title": "Network Traffic", "type": "library-panel-ref", "gridPos": { "h": 13, "w": 16, "x": 0, "y": 86 } }
   ]
  },
  {
   "title": "Application Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler workflows (Job Duration)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 }
    },
    { "title": "Number of requests over 3s ", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 } },
    { "title": "Request Count", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 } },
    {
     "title": "SUCCESSFUL - Average Request Time",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 }
    },
    { "title": "FAILED - Average Request Time", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 } },
    {
     "title": "Number of requests over 3s - Detail",
     "type": "library-panel-ref",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 }
    }
   ]
  },
  {
   "title": "Scalers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    { "title": "Scaler-Failed jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 } },
    { "title": "Scaler-Completed jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 } },
    { "title": "Scaler-Canceled jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 } },
    {
     "title": "Scaler Jobs per Workflow (Completed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 }
    },
    {
     "title": "Scaler Jobs per Workflow (Failed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 }
    },
    { "title": "Processing jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 } },
    { "title": "Average IPS Queue Waiting Time", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 } },
    { "title": "Scaler workflows", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 } }
   ]
  },
  {
   "title": "Interactives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    { "title": "Number of tickets", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 } },
    { "title": "IPS call errors", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 } },
    { "title": "Interactive requests & errors", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 } },
    { "title": "Number of users", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 } },
    { "title": "Drafts and Tickets", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 } },
    { "title": "Connections", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 } }
   ]
  },
  {
   "title": "Scaler JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    { "title": "Scaler heap used", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 70 } },
    { "title": "Scaler start time", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 6, "y": 70 } },
    { "title": "JVM Heap Scaler", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 12, "y": 70 } },
    { "title": "Scaler thread states", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 70 } }
   ]
  },
  {
   "title": "Interactive JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    { "title": "Interactive heap used", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 71 } },
    { "title": "Interactive start time", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 6, "y": 71 } },
    { "title": "JVM Heap Interactive", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 12, "y": 71 } },
    { "title": "Interactive thread states", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 71 } }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler Logs",
     "type": "logs",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 72 },
     "targets": [
      {
       "direction": "forward",
       "expr": "{job=\"scalerlogs\"} != `CachedIcmWorkflowDao: Workflow` != `DistributedMasterCheckRoutine` != `net.gmc.nuc.engine.log.Log4jJobLogger`",
       "maxLines": 5000
      }
     ]
    },
    {
     "title": "Scaler ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "targets": [
      {
       "direction": "forward",
       "expr": "{instance=~\"(scaler|inspire).*\", job=\"icmlogs\"} != `connection to 168`"
      }
     ]
    },
    {
     "title": "Scaler IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{instance=~\"(scaler|inspire).*\", job=\"ipslogs\"}",
       "maxLines": 2000
      }
     ]
    },
    {
     "title": "Interactive Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 95 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"interactivelogs\"}"
      }
     ]
    },
    {
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{instance=~\"interactive.*\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{instance=~\"interactive.*\", job=\"ipslogs\"}"
      }
     ]
    }
   ]
  }
 ]
}