{
 "title": "Prudential monthly",
 "tags": [ "qms-monthly" ],
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "templating": {
  "list": [
   { "name": "qmsEnvironment", "label": "Environment", "query": "DEV,TEST,STAGE,UAT,PERF,PROD" },
   { "name": "qmsCustomer", "query": "prudential" },
   { "name": "qmsContacts", "query": "m.cernohorsky@quadient.com" },
   { "name": "qmsTimezone", "query": "America/New_York" },
   { "name": "qmsDatasource", "label": "QMS Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "| **Customer:** ${qmsCustomer} | **Environments:** ${qmsEnvironment} | **Delivery Contacts:** ${qmsContacts} | **Timezone:** ${qmsTimezone} |"
   }
  },
  { "title": "$qmsEnvironment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "qmsEnvironment" },
  {
   "title": "Scaler jobs over 3s percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "( sum(increase(hms_scaler_jobDuration_3s_total{ workflow=\"ComposeDocument\", instanceName=~\"$qmsCustomer-(?i:($qmsEnvironment))\"}[$__range])) * 100) / sum(increase(scaler_job_runs_total{instanceName=~\"$qmsCustomer-(?i:($qmsEnvironment))\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaler jobs over 3s percentage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hms_scaler_jobDuration_3s_total{ workflow=\"ComposeDocument\", instanceName=~\"$qmsCustomer-(?i:($qmsEnvironment))\"}[$__range]))",
     "legendFormat": "Jobs over 3 seconds"
    },
    {
     "expr": "sum(increase(scaler_job_runs_total{instanceName=~\"$qmsCustomer-(?i:($qmsEnvironment))\"}[$__range]))",
     "legendFormat": "Jobs total"
    }
   ]
  },
  {
   "title": "Scaler jobs over 5s percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "( sum(increase(hms_scaler_jobDuration_5s_total{ workflow=\"ComposeDocument\", instanceName=~\"$qmsCustomer-(?i:($qmsEnvironment))\"}[$__range])) * 100) / sum(increase(scaler_job_runs_total{instanceName=~\"$qmsCustomer-(?i:($qmsEnvironment))\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaler jobs over 5s percentage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hms_scaler_jobDuration_5s_total{ workflow=\"ComposeDocument\", instanceName=~\"$qmsCustomer-(?i:($qmsEnvironment))\"}[$__range]))",
     "legendFormat": "Jobs over 5 seconds"
    },
    {
     "expr": "sum(increase(scaler_job_runs_total{instanceName=~\"$qmsCustomer-(?i:($qmsEnvironment))\"}[$__range]))",
     "legendFormat": "Jobs total"
    }
   ]
  },
  {
   "title": "Scaler jobs over 3 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "increase(hms_scaler_jobDuration_3s_total{ workflow=\"ComposeDocument\", instanceName=~\"$qmsCustomer-(?i:($qmsEnvironment))\"}[$__interval])",
     "legendFormat": "3s/{{workflow}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Scaler jobs over 5 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "increase(hms_scaler_jobDuration_5s_total{ workflow=\"ComposeDocument\", instanceName=~\"$qmsCustomer-(?i:($qmsEnvironment))\"}[$__interval])",
     "legendFormat": "5s/{{workflow}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Appgw number of requests over 3s",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and not(\r\n        requestUri_s == \"/rest/api/submit-job/test\"\r\n    )\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, clientResponseTime_d, serverResponseLatency_s\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count() by RequestType, RequestEndpoint\r\n| render table\r\n",
      "resources": [
       "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-nonprod/providers/Microsoft.Network/applicationGateways/appgw-prudential-nonprod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-fmr-hub-prod", "resourceName": "appgw-fmr-prod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
    }
   ]
  },
  {
   "title": "Appgw number of requests over 5s",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 5\r\n    and not(\r\n        requestUri_s == \"/rest/api/submit-job/TEST\"\r\n    )\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, clientResponseTime_d, serverResponseLatency_s\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count() by RequestType, RequestEndpoint\r\n| render table\r\n",
      "resources": [
       "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-nonprod/providers/Microsoft.Network/applicationGateways/appgw-prudential-nonprod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-fmr-hub-prod", "resourceName": "appgw-fmr-prod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
    }
   ]
  },
  { "title": "CPU Usage $qmsEnvironment", "gridPos": { "h": 17, "w": 16, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage (AVG) $qmsEnvironment",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 27 }
  },
  { "title": "Memory Usage $qmsEnvironment", "gridPos": { "h": 17, "w": 16, "x": 0, "y": 44 } },
  {
   "title": "Memory Usage (AVG) $qmsEnvironment",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 44 }
  },
  { "title": "Disk Usage $qmsEnvironment", "gridPos": { "h": 17, "w": 16, "x": 0, "y": 61 } },
  {
   "title": "Disk Usage (AVG) $qmsEnvironment",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 61 }
  },
  { "title": "Storage Usage $qmsEnvironment", "gridPos": { "h": 17, "w": 16, "x": 0, "y": 78 } },
  {
   "title": "Storage Usage (AVG) $qmsEnvironment",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 78 }
  },
  {
   "title": "Storage capacity $qmsEnvironment",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 }
  },
  { "title": "Completed Jobs $qmsEnvironment", "gridPos": { "h": 10, "w": 16, "x": 0, "y": 95 } },
  {
   "title": "AVG Completed Jobs $qmsEnvironment",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 95 }
  }
 ]
}