{
 "title": "Azure / Insights / Applications - Overview",
 "description": "The dashboard provides insights of Azure Apps via different metrics for app monitoring through Application Insights.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "res",
    "label": "Resource",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Azure Portal Links", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://portal.azure.com/#@${tenant}/resource/subscriptions/${sub}/resourceGroups/${rg}/providers/microsoft.insights/components/${res}/overview\" target=\"_blank\">\n<div style=\"padding-top: 20px\">\n  <center><p style=\"color: #7E58FF; font-size:18px;\">Application Insights </p></center>\n  <center><p style=\"margin-top:0px;\">${res}</p></center>\n</div>\n</a>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://portal.azure.com/#blade/AppInsightsExtension/ProactiveDetectionFeedBlade/ComponentId/%7B%22Name%22%3A%22${res}%22%2C%22SubscriptionId%22%3A%22${sub}%22%2C%22ResourceGroup%22%3A%22${rg}%22%7D/TimeContext/%7B%22durationMs%22%3A604800000%2C%22endTime%22%3Anull%2C%22createdTime%22%3A%222021-10-18T19%3A26%3A58.876Z%22%2C%22isInitialTime%22%3Atrue%2C%22grain%22%3A1%2C%22useDashboardTimeRange%22%3Afalse%7D\" target=\"_blank\">\n<div style=\"padding-top: 20px\">\n  <center><p style=\"color: #4d99b8; font-size:18px;\">Smart detection</p></center>\n  <center><p style=\"margin-top:0px;\">${res}</p></center>\n</div>\n</a>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://portal.azure.com/#@${tenant}/resource/subscriptions/${sub}/resourceGroups/${rg}/providers/microsoft.insights/components/${res}/quickPulse\" target=\"_blank\">\n<div style=\"padding-top: 20px\">\n  <center><p style=\"color: #2272b9; font-size:18px;\">Live Metrics</p></center>\n  <center><p style=\"margin-top:0px;\">${res}</p></center>\n</div>\n</a>\n           \n           "
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://portal.azure.com/#@${tenant}/resource/subscriptions/${sub}/resourceGroups/${rg}/providers/microsoft.insights/components/${res}/applicationMap\" target=\"_blank\">\n<div style=\"padding-top: 20px;\">\n  <center><p style=\"position:center; color: #ff8c00; font-size:18px\">App map</p></center>\n  <center><p style=\"margin-top:0px;\">${res}</p></center>\n</div>\n</a>\n           "
   }
  },
  { "title": "Application Insights Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Average available memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "performanceCounters/memoryAvailableBytes",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$res" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/count",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$res" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/duration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/microsoft.insights/components/$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Average processor and process CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processorCpuPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processCpuPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Average process I/O rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processIOBytesPerSecond",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "100"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server exceptions and Dependency failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "exceptions/server",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "alias": "Dependency failures",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}