{
 "title": "CAIXA main",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "qmsInstanceName",
    "label": "QMS Instance name",
    "query": "caixabank-lab,caixabank-tst,caixabank-pre,caixabank-pro"
   },
   { "name": "qmsDatasource", "label": "QMS Datasource", "query": "prometheus" },
   { "name": "lokiInstance", "label": "Loki Instance", "query": "loki" },
   { "name": "qmsDomainSuffix", "query": ".quadient.cloud" },
   { "name": "qmsCustomerName", "query": "CAIXABANK" }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Linux VM Overview", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 } },
  { "title": "Inspire heartbeat", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 } },
  { "title": "RHEL security updates", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 15, "x": 0, "y": 18 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 14, "w": 9, "x": 15, "y": 18 } },
  {
   "title": "Number of requests over 30m NONPROD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 1800 // 1800 seconds = 30 minutes\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = TimeGenerated, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()\r\n",
      "resources": [
       "/subscriptions/b23c85b4-23e0-43dd-ad7a-988029bcba1d/resourceGroups/hmsrg-caixa-hub-nonprod/providers/Microsoft.Network/applicationGateways/appgw-caixa-nonprod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod", "resourceName": "appgw-excellusbcbs-nonprod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
    }
   ]
  },
  {
   "title": "Number of requests over 3s NONPROD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = TimeGenerated, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()\r\n",
      "resources": [
       "/subscriptions/b23c85b4-23e0-43dd-ad7a-988029bcba1d/resourceGroups/hmsrg-caixa-hub-nonprod/providers/Microsoft.Network/applicationGateways/appgw-caixa-nonprod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod", "resourceName": "appgw-excellusbcbs-nonprod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
    }
   ]
  },
  { "title": "Audit Logs", "type": "library-panel-ref", "gridPos": { "h": 3, "w": 5, "x": 10, "y": 26 } },
  {
   "title": "Number of requests over 30m PROD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 1800 // 1800 seconds = 30 minutes\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = TimeGenerated, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()\r\n",
      "resources": [
       "/subscriptions/b23c85b4-23e0-43dd-ad7a-988029bcba1d/resourceGroups/hmsrg-caixa-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-caixa-prod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod", "resourceName": "appgw-excellusbcbs-nonprod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
    }
   ]
  },
  {
   "title": "Number of requests over 3s PROD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = TimeGenerated, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()\r\n",
      "resources": [
       "/subscriptions/b23c85b4-23e0-43dd-ad7a-988029bcba1d/resourceGroups/hmsrg-caixa-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-caixa-prod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod", "resourceName": "appgw-excellusbcbs-nonprod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
    }
   ]
  },
  {
   "title": "Backups Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily VM/Disk Azure backup",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n    and not(\r\n        BackupItemFriendlyName1 contains \"test\" or\r\n        BackupItemFriendlyName1 contains \"qa\"\r\n    )\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resources": [
         "/subscriptions/2305a810-3543-4007-b1ac-5535cf9ee314/resourceGroups/hmsrg-eon-hub-prod/providers/Microsoft.RecoveryServices/vaults/rsv-eon-prod"
        ],
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Azure VM/Disks backup health",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "",
        "resources": [
         "/subscriptions/6b7f3c14-d3a0-4dd2-9990-d079120c95ad/resourceGroups/hmsrg-aware-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-aware-nonprod"
        ]
       },
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "healthStatus",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "dataSourceType",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "backupInstanceName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "BackupHealthEvent",
        "metricNamespace": "microsoft.recoveryservices/vaults",
        "region": "germanywestcentral",
        "resources": [
         {
          "metricNamespace": "Microsoft.RecoveryServices/vaults",
          "region": "germanywestcentral",
          "resourceGroup": "hmsrg-eon-hub-prod",
          "resourceName": "rsv-eon-prod",
          "subscription": "2305a810-3543-4007-b1ac-5535cf9ee314"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "2305a810-3543-4007-b1ac-5535cf9ee314"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    { "title": "CPU Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 34 } },
    { "title": "Memory Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 8, "y": 34 } },
    { "title": "DiskSpace usage", "type": "library-panel-ref", "gridPos": { "h": 33, "w": 8, "x": 16, "y": 34 } },
    { "title": "Average CPU Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 44 } },
    { "title": "File Shares usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 8, "y": 44 } },
    { "title": "Network Traffic", "type": "library-panel-ref", "gridPos": { "h": 13, "w": 16, "x": 0, "y": 54 } }
   ]
  },
  {
   "title": "Scalers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    { "title": "Failed jobs  ", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 } },
    { "title": "Completed jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 } },
    { "title": "Canceled jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 } },
    {
     "title": "Scaler Jobs per Workflow (Completed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 }
    },
    {
     "title": "Scaler Jobs per Workflow (Failed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 }
    },
    { "title": "Processing jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 137 } },
    { "title": "Average IPS Queue Waiting Time", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 137 } },
    { "title": "Scaler workflows", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 137 } }
   ]
  },
  {
   "title": "Interactives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    { "title": "Number of tickets", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 498 } },
    { "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 498 } },
    { "title": "Interactive requests & errors", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 498 } },
    { "title": "Number of users", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 520 } },
    { "title": "Drafts and Tickets", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 520 } },
    { "title": "Connections", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 520 } }
   ]
  },
  {
   "title": "Scaler JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    { "title": "Scaler heap used", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 213 } },
    { "title": "Scaler start time", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 6, "y": 213 } },
    { "title": "JVM Heap Scaler", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 12, "y": 213 } },
    { "title": "Scaler thread states", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 213 } }
   ]
  },
  {
   "title": "Interactive JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    { "title": "Interactive heap used", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 148 } },
    { "title": "Interactive start time", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 6, "y": 148 } },
    { "title": "JVM Heap interactive", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 12, "y": 148 } },
    { "title": "Interactive thread states", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 148 } }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  { "title": "Scaler Logs", "type": "library-panel-ref", "gridPos": { "h": 15, "w": 24, "x": 0, "y": 39 } },
  { "title": "Scaler ICM Logs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 } },
  { "title": "Scaler IPS Logs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 } },
  { "title": "Interactive Logs", "type": "library-panel-ref", "gridPos": { "h": 13, "w": 24, "x": 0, "y": 62 } },
  { "title": "Interactive ICM Logs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 } },
  { "title": "Interactive  IPS Logs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 } }
 ]
}