{
 "title": "Apex-PROD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server's Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show designer traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*vm\", instanceName=\"apex-prod\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat",
   "type": "stat",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 16, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"apex-prod\", environment=\"prod1\"}",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 16, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"apex-prod\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"apex-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 7, "x": 17, "y": 1 } },
  {
   "title": "Server's Percentage Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"apex-prod\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"apex-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RHEL security updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "hms_dnf{instanceName=\"apex-prod\",type=~\"Critical|Important|Moderate\"}",
     "legendFormat": "{{job}}:{{type}}"
    }
   ]
  },
  {
   "title": "All Daily (Monday - Saturday)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_backup_info_daily_all{instanceName=\"apex-prod\",backupType=\"daily\"})"
    }
   ]
  },
  {
   "title": "DB - Daily (Monday - Saturday)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hms_backup_info_daily_all{containerName=~\".*db$\",instanceName=\"apex-prod\"}",
     "legendFormat": "{{backupItem}}-database"
    }
   ]
  },
  { "title": "Shared Panels", "type": "dashlist", "gridPos": { "h": 6, "w": 9, "x": 13, "y": 17 } },
  {
   "title": "Audit Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_audit_log{instance=\"monitoring.apex-prod.quadient.cloud:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Weekly (4 Sundays)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_backup_info_weekly_all{instanceName=\"apex-prod\",backupType=\"weekly\"})"
    }
   ]
  },
  {
   "title": "DB - Weekly (4 Sundays)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hms_backup_info_weekly_all{containerName=~\".*db$\",instanceName=\"apex-prod\"}",
     "legendFormat": "{{backupItem}}-database"
    }
   ]
  },
  { "title": "Backups Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Daily VM/Disk Azure backup",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
      "resource": "/subscriptions/ba8401dd-6f58-42da-87f7-c0a690bf1d9c/resourceGroups/hmsrg-apex-hub-prod/providers/Microsoft.RecoveryServices/vaults/rsv-apex-prod",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Azure VM/Disks backup health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(7d)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
      "resource": "/subscriptions/de74e022-0016-4972-ac5a-d17f177ed92d/resourceGroups/hmsrg-gfbank-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-gfbank-nonprod",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "healthStatus",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "backupInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "BackupHealthEvent",
      "metricNamespace": "microsoft.recoveryservices/vaults",
      "resourceGroup": "hmsrg-apex-hub-prod",
      "resourceName": "rsv-apex-prod",
      "timeGrain": "auto"
     },
     "subscription": "ba8401dd-6f58-42da-87f7-c0a690bf1d9c"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"designer0.apex-prod.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "designer0"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"monitoring.apex-prod.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "monitoring"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"^(.*?)apex-prod.quadient.cloud:9100\"}[5m])",
     "legendFormat": "{{instance}} recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"^(.*?)apex-prod.quadient.cloud:9100\"}[5m])",
     "legendFormat": "{{instance}} trans {{device}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"apex-prod\",instance=\"designer0.apex-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"apex-prod\",instance=\"designer0.apex-prod.quadient.cloud:9100\"})*100",
     "legendFormat": "designer0"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"apex-prod\",instance=\"monitoring.apex-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"apex-prod\",instance=\"monitoring.apex-prod.quadient.cloud:9100\"})*100",
     "legendFormat": "monitoring"
    }
   ]
  },
  {
   "title": "Disk Space Used Monitoring VM",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"monitoring.*\", instanceName=\"apex-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"monitoring.*\", instanceName=\"apex-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Designer VM",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"designer0.*\", instanceName=\"apex-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"designer0.*\", instanceName=\"apex-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "ICM Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "{instance=~\"designer0.apex-prod.quadient.cloud\", job=\"icmlogs\"}"
    }
   ]
  },
  {
   "title": "IPS Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "{instance=~\"designer0.apex-prod.quadient.cloud\", job=\"ipslogs\"}"
    }
   ]
  }
 ]
}