{
 "title": "ASH-STAGE",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server's Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Automation traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*vm\", instanceName=\"ash-stage\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat",
   "type": "stat",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"ash-stage\", environment=\"pre2\"}",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"ash-stage\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"ash-stage\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 22, "w": 7, "x": 17, "y": 1 } },
  {
   "title": "Server's Percentage Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"ash-stage\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"ash-stage\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RHEL security updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "hms_dnf{instanceName=\"ash-stage\",type=~\"Critical|Important|Moderate\"}",
     "legendFormat": "{{job}}:{{type}}"
    }
   ]
  },
  { "title": "Shared Panels", "type": "dashlist", "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 } },
  {
   "title": "Audit Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_audit_status{instanceName=\"ash-stage\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backups Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Daily VM/Disk Azure backup",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n    and not(\r\n        BackupItemFriendlyName1 contains \"test\" or\r\n        BackupItemFriendlyName1 contains \"qa\"\r\n    )\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
      "resources": [
       "/subscriptions/73459f66-7add-4e0f-a787-a6976cd99cbb/resourceGroups/hmsrg-ash-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-ash-nonprod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Azure VM/Disks backup health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(7d)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
      "resources": [
       "/subscriptions/de74e022-0016-4972-ac5a-d17f177ed92d/resourceGroups/hmsrg-gfbank-hub-nonstage/providers/Microsoft.RecoveryServices/vaults/rsv-gfbank-nonstage"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "healthStatus",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "backupInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "BackupHealthEvent",
      "metricNamespace": "microsoft.recoveryservices/vaults",
      "region": "westus3",
      "resources": [
       {
        "metricNamespace": "Microsoft.RecoveryServices/vaults",
        "region": "westus3",
        "resourceGroup": "hmsrg-ash-hub-nonprod",
        "resourceName": "rsv-ash-nonprod",
        "subscription": "73459f66-7add-4e0f-a787-a6976cd99cbb"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "azureResourceGraph": { "query": "" },
     "subscription": "73459f66-7add-4e0f-a787-a6976cd99cbb",
     "subscriptions": [
      "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
     ]
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive0.ash-stage.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "interactive0"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"automation0.ash-stage.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "automation0"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"monitoring.ash-stage.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "monitoring"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive1.ash-stage.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "interactive1"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"automation1.ash-stage.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "automation1"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler0.ash-stage.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "scaler0"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler1.ash-stage.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "scaler1"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler2.ash-stage.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "scaler2"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"^(.*?)ash-stage.quadient.cloud:9100\"}[5m])",
     "legendFormat": "{{instance}} recv {{stageice}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"^(.*?)ash-stage.quadient.cloud:9100\"}[5m])",
     "legendFormat": "{{instance}} trans {{stageice}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"ash-stage\",instance=\"interactive0.ash-stage.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"ash-stage\",instance=\"interactive0.ash-stage.quadient.cloud:9100\"})*100",
     "legendFormat": "interactive0"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"ash-stage\",instance=\"automation0.ash-stage.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"ash-stage\",instance=\"automation0.ash-stage.quadient.cloud:9100\"})*100",
     "legendFormat": "automation0"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"ash-stage\",instance=\"monitoring.ash-stage.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"ash-stage\",instance=\"monitoring.ash-stage.quadient.cloud:9100\"})*100",
     "legendFormat": "monitoring"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"ash-stage\",instance=\"interactive1.ash-stage.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"ash-stage\",instance=\"interactive1.ash-stage.quadient.cloud:9100\"})*100",
     "legendFormat": "interactive1"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"ash-stage\",instance=\"automation1.ash-stage.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"ash-stage\",instance=\"automation1.ash-stage.quadient.cloud:9100\"})*100",
     "legendFormat": "automation1"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"ash-stage\",instance=\"scaler0.ash-stage.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"ash-stage\",instance=\"scaler0.ash-stage.quadient.cloud:9100\"})*100",
     "legendFormat": "scaler0"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"ash-stage\",instance=\"scaler1.ash-stage.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"ash-stage\",instance=\"scaler1.ash-stage.quadient.cloud:9100\"})*100",
     "legendFormat": "scaler1"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"ash-stage\",instance=\"scaler2.ash-stage.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"ash-stage\",instance=\"scaler2.ash-stage.quadient.cloud:9100\"})*100",
     "legendFormat": "scaler2"
    }
   ]
  },
  {
   "title": "Disk Space Used Monitoring VM",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"monitoring.*\", instanceName=\"ash-stage\", stageice!~'rootfs', mountpoint!=\"/mnt/hmstemp\"} * 100) / node_filesystem_size_bytes{instance=~\"monitoring.*\", instanceName=\"ash-stage\", stageice!~'rootfs', mountpoint!=\"/mnt/hmstemp\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Interactive 0 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive0.ash-stage.quadient.cloud:9100\", instanceName=\"ash-stage\",stageice!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive0.ash-stage.quadient.cloud:9100\", instanceName=\"ash-stage\",stageice!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Interactive 1 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive1.ash-stage.quadient.cloud:9100\", instanceName=\"ash-stage\",stageice!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive1.ash-stage.quadient.cloud:9100\", instanceName=\"ash-stage\",stageice!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Automation 0 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"automation0.ash-stage.quadient.cloud:9100\", instanceName=\"ash-stage\",stageice!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"automation0.ash-stage.quadient.cloud:9100\", instanceName=\"ash-stage\",stageice!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Automation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Submodules Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "increase(qms_automation_submodule_error{environment=\"pre2\", instanceName=\"ash-stage\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Metrics Last Update (seconds)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - qms_automation_metrics_lastUpdate{environment=\"pre2\",customerName=\"ASH\",exported_instance=\"automation0.ash-stage.quadient.cloud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 71 },
   "targets": [
    {
     "expr": "increase(qms_automation_job_status_counter{exported_instance=\"automation0.ash-stage.quadient.cloud\",status=\"error\"}[5m])",
     "legendFormat": "Error Jobs"
    },
    {
     "expr": "increase(qms_automation_job_status_counter{exported_instance=\"automation0.ash-stage.quadient.cloud\",status=\"ok\"}[5m])",
     "legendFormat": "Success Jobs"
    }
   ]
  },
  {
   "title": "Server's Percentage Availability",
   "type": "timeseries",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "up{job=~\".*vm\", instanceName=\"ash-stage\",instance=\"automation0.ash-stage.quadient.cloud:9100\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Automation heartbeat percentage",
   "type": "timeseries",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "network_check{name=\"automation0.ash-stage.quadient.cloud\"}",
     "legendFormat": "Network"
    }
   ]
  },
  {
   "title": "Automation start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{customerName=\"ASH\",job=\"ash-stage-automation-vm\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Interactives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Number of tickets",
   "type": "timeseries",
   "description": "Number of tickets created since Interactive startup.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "II_CreatedTicketsCount_total{instance=~\"interactive0.ash-stage.quadient.cloud:30701|interactive1.ash-stage.quadient.cloud:30701\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IPS call errors",
   "type": "timeseries",
   "description": "Number of IPS calls made ending in errors since Interactive startup.\nNumber of IPS calls ending in a timeout made since Interactive startup.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "targets": [
    {
     "expr": "rate(II_IPSCallExceptionCount_total{instance=~\"interactive0.ash-stage.quadient.cloud:30701|interactive1.ash-stage.quadient.cloud:30701\"}[5m])",
     "legendFormat": "IPS Call Expections/{{instance}}"
    }
   ]
  },
  {
   "title": "Interactive requests & errors",
   "type": "timeseries",
   "description": "Number of user synchronization errors since Interactive startup.\nNumber of REST/SOAP requests received since Interactive startup.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "targets": [
    {
     "expr": "increase(II_InteractiveError{instance=~\"interactive0.ash-stage.quadient.cloud:30701|interactive1.ash-stage.quadient.cloud:30701\"}[5m])",
     "legendFormat": "II Errors/{{instance}}/{{Type}}"
    },
    {
     "expr": "increase(II_InteractiveRequest_count{instance=~\"interactive0.ash-stage.quadient.cloud:30701|interactive1.ash-stage.quadient.cloud:30701\"}[5m])",
     "legendFormat": "II Requests/{{instance}}"
    },
    {
     "expr": "increase(II_InteractiveRequestExceptionCount{instance=~\"interactive0.ash-stage.quadient.cloud:30701|interactive1.ash-stage.quadient.cloud:30701\"}[5m])",
     "legendFormat": "II Errors/{{instance}}/Requests"
    }
   ]
  },
  {
   "title": "Number of users",
   "type": "timeseries",
   "description": "Number of currently logged in users (active session only).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "II_DBSessions{instance=~\"interactive0.ash-stage.quadient.cloud:30701|interactive1.ash-stage.quadient.cloud:30701\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Drafts and Tickets",
   "type": "timeseries",
   "description": "Number of currently active drafts and tickets, and drafts and tickets that are marked for deletion. Numbers are grouped by: active drafts, drafts marked for deletion, active tickets, tickets marked for deletion.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 94 },
   "targets": [
    {
     "expr": "II_DBData{instance=~\"interactive0.ash-stage.quadient.cloud:30701|interactive1.ash-stage.quadient.cloud:30701\"}",
     "legendFormat": "{{instance}}/{{ObjectType}}/{{State}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Number of currently active and idle Interactive connections to the database.\nNumber of currently active and idle Interactive connections to Inspire Content Manager (ICM).\n\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 94 },
   "targets": [
    {
     "expr": "II_DBConnections{instance=~\"interactive0.ash-stage.quadient.cloud:30701|interactive1.ash-stage.quadient.cloud:30701\"}",
     "legendFormat": "DB {{instance}}/{{Connection}}"
    },
    {
     "expr": "II_ICMConnections{instance=~\"interactive0.ash-stage.quadient.cloud:30701|interactive1.ash-stage.quadient.cloud:30701\"}",
     "legendFormat": "ICM {{instance}}/{{Connection}}"
    },
    {
     "expr": "II_IPSConnections{instance=~\"interactive0.ash-stage.quadient.cloud:30701|interactive1.ash-stage.quadient.cloud:30701\"}",
     "legendFormat": "IPS {{instance}}/{{Connection}}"
    }
   ]
  },
  { "title": "Interactive JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Interactive heap used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"ASH\",area=\"heap\",instance=\"interactive0.ash-stage.quadient.cloud:30701\"})*100/sum(jvm_memory_bytes_max{customerName=\"ASH\",area=\"heap\",instance=\"interactive0.ash-stage.quadient.cloud:30701\"})",
     "legendFormat": "Interactive 0"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"ASH\",area=\"heap\",instance=\"interactive1.ash-stage.quadient.cloud:30701\"})*100/sum(jvm_memory_bytes_max{customerName=\"ASH\",area=\"heap\",instance=\"interactive1.ash-stage.quadient.cloud:30701\"})",
     "legendFormat": "Interactive 1"
    }
   ]
  },
  {
   "title": "Interactive start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{customerName=\"ASH\",job=\"ash-stage-interactive-vm\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Heap Interactive 0",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"interactive0.ash-stage.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive0.ash-stage.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"interactive0.ash-stage.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Heap Interactive 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"interactive1.ash-stage.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive1.ash-stage.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"interactive1.ash-stage.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Interactive 0 thread states",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"interactive0.ash-stage.quadient.cloud:30701\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Interactive 1 thread states",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"interactive1.ash-stage.quadient.cloud:30701\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Automation Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "{job=\"automationlogs\"}"
    }
   ]
  },
  {
   "title": "Automation ICM Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "{instance=~\"automation0.ash-stage.quadient.cloud\", job=\"icmlogs\"}"
    }
   ]
  },
  {
   "title": "Audit Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "{job=\"auditlogs\"}"
    }
   ]
  },
  {
   "title": "Interactive Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "{job=\"interactivelogs\"}"
    }
   ]
  },
  {
   "title": "Interactive ICM Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "targets": [
    {
     "expr": "{instance=~\"interactive0.ash-stage.quadient.cloud|interactive1.ash-stage.quadient.cloud\", job=\"icmlogs\"}"
    }
   ]
  },
  {
   "title": "Interactive  IPS Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "targets": [
    {
     "expr": "{instance=~\"interactive0.ash-stage.quadient.cloud|interactive1.ash-stage.quadient.cloud\", job=\"ipslogs\"}"
    }
   ]
  }
 ]
}