{
 "title": "Aware - PERF2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "qmsInstanceName", "label": "QMS Instance name", "query": "aware-perf2" },
   { "name": "qmsDatasource", "label": "QMS Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server's Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Automation traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*vm\", instanceName=\"aware-perf2\", instance=~\"interactive[0-1].aware-perf2.quadient.cloud:9100|scaler[0-2].aware-perf2.quadient.cloud:9100|monitoring.aware-perf2.quadient.cloud:9100\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat",
   "type": "stat",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"aware-perf2\", environment=\"pre7\"}",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"aware-perf2\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"aware-perf2\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 22, "w": 7, "x": 17, "y": 1 } },
  {
   "title": "Server's Percentage Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"aware-perf2\", instance!=\"scaler3.aware-perf2.quadient.cloud:9100\", instance!=\"scaler4.aware-perf2.quadient.cloud:9100\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"aware-perf2\", instance!=\"scaler3.aware-perf2.quadient.cloud:9100\", instance!=\"scaler4.aware-perf2.quadient.cloud:9100\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RHEL security updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "hms_dnf{instanceName=\"aware-perf2\",type=~\"Critical|Important|Moderate\"}",
     "legendFormat": "{{job}}:{{type}}"
    }
   ]
  },
  { "title": "Linux VM Overview", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 } },
  { "title": "Shared Panels", "type": "dashlist", "gridPos": { "h": 6, "w": 9, "x": 0, "y": 33 } },
  {
   "title": "Number of requests over 3s ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()\r\n",
      "resources": [
       "/subscriptions/6b7f3c14-d3a0-4dd2-9990-d079120c95ad/resourceGroups/hmsrg-aware-hub-nonprod/providers/Microsoft.Network/applicationGateways/appgw-aware-nonprod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod", "resourceName": "appgw-excellusbcbs-nonprod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
    }
   ]
  },
  {
   "title": "Audit Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_audit_status{instanceName=\"aware-perf2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests over 30m ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 1800 // 1800 seconds = 30 minutes\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()",
      "resources": [
       "/subscriptions/6b7f3c14-d3a0-4dd2-9990-d079120c95ad/resourceGroups/hmsrg-aware-hub-nonprod/providers/Microsoft.Network/applicationGateways/appgw-aware-nonprod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod", "resourceName": "appgw-excellusbcbs-nonprod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
    }
   ]
  },
  {
   "title": "Backups Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily VM/Disk Azure backup",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 132 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n    and BackupItemFriendlyName1 contains \"vm-$qmsInstanceName\"\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resources": [
         "/subscriptions/6b7f3c14-d3a0-4dd2-9990-d079120c95ad/resourceGroups/hmsrg-aware-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-aware-nonprod"
        ],
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Azure VM/Disks backup health",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 132 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "",
        "resources": [
         "/subscriptions/6b7f3c14-d3a0-4dd2-9990-d079120c95ad/resourceGroups/hmsrg-aware-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-aware-nonprod"
        ]
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "DB - Daily (Monday - Saturday)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info_daily_all{containerName=~\".*db$\",instanceName=\"aware-perf2\",backupType=\"daily\"}",
       "legendFormat": "{{backupItem}}-database"
      }
     ]
    },
    {
     "title": "DB - Weekly (4 Sundays)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info_weekly_all{containerName=~\".*db$\",instanceName=\"aware-perf2\",backupType=\"weekly\"}",
       "legendFormat": "{{backupItem}}-database"
      }
     ]
    },
    {
     "title": "All Daily (Monday - Saturday)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hms_backup_info_daily_all{instanceName=\"aware-perf2\",backupType=\"daily\"})"
      }
     ]
    },
    {
     "title": "All Weekly (4 Sundays)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hms_backup_info_weekly_all{instanceName=\"aware-perf2\",backupType=\"weekly\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    { "title": "CPU Usage", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 } },
    { "title": "Memory Usage", "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 } },
    { "title": "DiskSpace usage", "gridPos": { "h": 29, "w": 8, "x": 16, "y": 69 } },
    { "title": "Average CPU Usage", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 } },
    { "title": "File Shares usage", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 } },
    { "title": "Network Traffic", "gridPos": { "h": 12, "w": 16, "x": 0, "y": 86 } }
   ]
  },
  {
   "title": "Scalers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    { "title": "Failed jobs", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 } },
    { "title": "Completed jobs", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 } },
    {
     "title": "Canceled jobs",
     "type": "timeseries",
     "description": "Indicates jobs that have been successfully processed.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{status=\"canceled\", instance=~\"scaler0.aware-perf2.quadient.cloud:30600|scaler1.aware-perf2.quadient.cloud:30600|scaler2.aware-perf2.quadient.cloud:30600\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    { "title": "Processing jobs", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 } },
    { "title": "Average IPS Queue Waiting Time", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 } },
    {
     "title": "Scaler workflows",
     "type": "timeseries",
     "description": "Provides the number of deployed workflows for each workflow type, and for each of the following statuse",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "scaler_deployed_workflows_total{instance=~\"scaler0.aware-perf2.quadient.cloud:30600|scaler1.aware-perf2.quadient.cloud:30600|scaler2.aware-perf2.quadient.cloud:30600\"}",
       "legendFormat": "{{instance}}/{{ group }}: {{ status }}"
      }
     ]
    },
    {
     "title": "Scaler Jobs per Workflow (Completed)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 }
    },
    {
     "title": "Scaler Jobs per Workflow (Failed)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 }
    }
   ]
  },
  {
   "title": "Interactives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of tickets",
     "type": "timeseries",
     "description": "Number of tickets created since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "II_CreatedTicketsCount_total{instance=~\"interactive0.aware-perf2.quadient.cloud:30701|interactive1.aware-perf2.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IPS call errors",
     "type": "timeseries",
     "description": "Number of IPS calls made ending in errors since Interactive startup.\nNumber of IPS calls ending in a timeout made since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
     "targets": [
      {
       "expr": "rate(II_IPSCallExceptionCount_total{instance=~\"interactive0.aware-perf2.quadient.cloud:30701|interactive1.aware-perf2.quadient.cloud:30701\"}[5m])",
       "legendFormat": "IPS Call Expections/{{instance}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "Number of currently active and idle Interactive connections to the database.\nNumber of currently active and idle Interactive connections to Inspire Content Manager (ICM).\n\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
     "targets": [
      {
       "expr": "II_DBConnections{instance=~\"interactive0.aware-perf2.quadient.cloud:30701|interactive1.aware-perf2.quadient.cloud:30701\"}",
       "legendFormat": "DB {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_ICMConnections{instance=~\"interactive0.aware-perf2.quadient.cloud:30701|interactive1.aware-perf2.quadient.cloud:30701\"}",
       "legendFormat": "ICM {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_IPSConnections{instance=~\"interactive0.aware-perf2.quadient.cloud:30701|interactive1.aware-perf2.quadient.cloud:30701\"}",
       "legendFormat": "IPS {{instance}}/{{Connection}}"
      }
     ]
    },
    {
     "title": "Number of users",
     "type": "timeseries",
     "description": "Number of currently logged in users (active session only).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "II_DBSessions{instance=~\"interactive0.aware-perf2.quadient.cloud:30701|interactive1.aware-perf2.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Drafts and Tickets",
     "type": "timeseries",
     "description": "Number of currently active drafts and tickets, and drafts and tickets that are marked for deletion. Numbers are grouped by: active drafts, drafts marked for deletion, active tickets, tickets marked for deletion.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
     "targets": [
      {
       "expr": "II_DBData{instance=~\"interactive0.aware-perf2.quadient.cloud:30701|interactive1.aware-perf2.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}/{{ObjectType}}/{{State}}"
      }
     ]
    },
    {
     "title": "Interactive requests & errors",
     "type": "timeseries",
     "description": "Number of user synchronization errors since Interactive startup.\nNumber of REST/SOAP requests received since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
     "targets": [
      {
       "expr": "increase(II_InteractiveError{instance=~\"interactive0.aware-perf2.quadient.cloud:30701|interactive1.aware-perf2.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Errors/{{instance}}/{{Type}}"
      },
      {
       "expr": "increase(II_InteractiveRequest_count{instance=~\"interactive0.aware-perf2.quadient.cloud:30701|interactive1.aware-perf2.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Requests/{{instance}}"
      },
      {
       "expr": "increase(II_InteractiveRequestExceptionCount{instance=~\"interactive0.aware-perf2.quadient.cloud:30701|interactive1.aware-perf2.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Errors/{{instance}}/Requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Scaler JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler heap used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Aware\",area=\"heap\",instance=\"scaler0.aware-perf2.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Aware\",area=\"heap\",instance=\"scaler0.aware-perf2.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 0"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Aware\",area=\"heap\",instance=\"scaler1.aware-perf2.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Aware\",area=\"heap\",instance=\"scaler0.aware-perf2.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 1"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Aware\",area=\"heap\",instance=\"scaler1.aware-perf2.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Aware\",area=\"heap\",instance=\"scaler0.aware-perf2.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 2"
      }
     ]
    },
    {
     "title": "Scaler start time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{customerName=\"Aware\",job=\"aware-perf2-scaler-vm\"}*1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Heap Scaler",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler0.aware-perf2.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler0.aware-perf2.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.aware-perf2.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler1.aware-perf2.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler1.aware-perf2.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.aware-perf2.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler2.aware-perf2.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler2.aware-perf2.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler2.aware-perf2.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Scaler thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler0.aware-perf2.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler1.aware-perf2.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler2.aware-perf2.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactive JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactive heap used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Aware\",area=\"heap\",instance=\"interactive0.aware-perf2.quadient.cloud:30701\"})*100/sum(jvm_memory_bytes_max{customerName=\"Aware\",area=\"heap\",instance=\"interactive0.aware-perf2.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 0"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Aware\",area=\"heap\",instance=\"interactive1.aware-perf2.quadient.cloud:30701\",instanceName=\"aware-perf2\"})*100/sum(jvm_memory_bytes_max{customerName=\"Aware\",area=\"heap\",instance=\"interactive1.aware-perf2.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 1"
      }
     ]
    },
    {
     "title": "Interactive start time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{customerName=\"Aware\",job=\"aware-perf2-interactive-vm\"}*1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 0",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive0.aware-perf2.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive0.aware-perf2.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive0.aware-perf2.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 1",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive1.aware-perf2.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive1.aware-perf2.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive1.aware-perf2.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Interactive 0 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive0.aware-perf2.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Interactive 1 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive1.aware-perf2.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 178 },
     "targets": [
      {
       "expr": "{job=\"scalerlogs\"}"
      }
     ]
    },
    {
     "title": "Scaler ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
     "targets": [
      {
       "expr": "{instance=~\"scaler2.aware-perf2.quadient.cloud|scaler1.aware-perf2.quadient.cloud|scaler0.aware-perf2.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Scaler IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 191 },
     "targets": [
      {
       "expr": "{instance=~\"scaler0.aware-perf2.quadient.cloud|scaler2.aware-perf2.quadient.cloud|scaler1.aware-perf2.quadient.cloud\", job=\"ipslogs\"}"
      }
     ]
    },
    {
     "title": "Interactive Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 199 },
     "targets": [
      {
       "expr": "{job=\"interactivelogs\"}"
      }
     ]
    },
    {
     "title": "Interactive ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.aware-perf2.quadient.cloud|interactive1.aware-perf2.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Interactive  IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.aware-perf2.quadient.cloud|interactive1.aware-perf2.quadient.cloud\", job=\"ipslogs\"}"
      }
     ]
    }
   ]
  }
 ]
}