{
 "title": "Chubb-NORAM-PROD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server's Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Automation traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*vm\", instanceName=\"chubb-na-prod\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat",
   "type": "stat",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"chubb-na-prod\", environment=\"prod1\"}",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"chubb-na-prod\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"chubb-na-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 22, "w": 7, "x": 17, "y": 1 } },
  {
   "title": "Server's Percentage Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"chubb-na-prod\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"chubb-na-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RHEL security updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "hms_dnf{instanceName=\"chubb-na-prod\",type=~\"Critical|Important|Moderate\"}",
     "legendFormat": "{{job}}:{{type}}"
    }
   ]
  },
  {
   "title": "Audit Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_audit_log{instance=\"monitoring.na-prod.chubb.quadient.cloud:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backups Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Daily VM/Disk Azure backup",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
      "resources": [
       "/subscriptions/8f1c49a1-638a-4a59-9e19-551a7c4e7f14/resourceGroups/hmsrg-chubb-americas-hub-prod/providers/Microsoft.RecoveryServices/vaults/rsv-chubb-americas-prod"
      ],
      "resultFormat": "logs"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.recoveryservices",
      "region": "northeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.RecoveryServices",
        "region": "northeurope",
        "resourceGroup": "hmsrg-chubb-ne-hub-nonprod",
        "resourceName": "rsv-chubb-ne-nonprod",
        "subscription": "8f1c49a1-638a-4a59-9e19-551a7c4e7f14"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "8f1c49a1-638a-4a59-9e19-551a7c4e7f14"
    }
   ]
  },
  {
   "title": "Azure VM/Disks backup health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.recoveryservices/vaults",
      "dimensionFilters": [
       {
        "dimension": "healthStatus",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "backupInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "BackupHealthEvent",
      "metricNamespace": "microsoft.recoveryservices/vaults",
      "region": "eastus",
      "resources": [
       {
        "metricNamespace": "Microsoft.RecoveryServices/vaults",
        "region": "eastus",
        "resourceGroup": "hmsrg-chubb-americas-hub-prod",
        "resourceName": "rsv-chubb-americas-prod",
        "subscription": "8f1c49a1-638a-4a59-9e19-551a7c4e7f14"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "8f1c49a1-638a-4a59-9e19-551a7c4e7f14"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive0.na-prod.chubb.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "interactive0"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive1.na-prod.chubb.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "interactive1"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler0.na-prod.chubb.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "scaler0"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler1.na-prod.chubb.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "scaler1"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler2.na-prod.chubb.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "scaler2"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"monitoring.na-prod.chubb.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "monitoring"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"^(.*?)na-prod.chubb.quadient.cloud:9100\"}[5m])",
     "legendFormat": "{{instance}} recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"^(.*?)na-prod.chubb.quadient.cloud:9100\"}[5m])",
     "legendFormat": "{{instance}} trans {{device}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"chubb-na-prod\",instance=\"interactive0.na-prod.chubb.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"chubb-na-prod\",instance=\"interactive0.na-prod.chubb.quadient.cloud:9100\"})*100",
     "legendFormat": "interactive0"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"chubb-na-prod\",instance=\"interactive1.na-prod.chubb.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"chubb-na-prod\",instance=\"interactive1.na-prod.chubb.quadient.cloud:9100\"})*100",
     "legendFormat": "interactive1"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"chubb-na-prod\",instance=\"scaler0.na-prod.chubb.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"chubb-na-prod\",instance=\"scaler0.na-prod.chubb.quadient.cloud:9100\"})*100",
     "legendFormat": "scaler0"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"chubb-na-prod\",instance=\"scaler1.na-prod.chubb.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"chubb-na-prod\",instance=\"scaler1.na-prod.chubb.quadient.cloud:9100\"})*100",
     "legendFormat": "scaler1"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"chubb-na-prod\",instance=\"scaler2.na-prod.chubb.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"chubb-na-prod\",instance=\"scaler2.na-prod.chubb.quadient.cloud:9100\"})*100",
     "legendFormat": "scaler2"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"chubb-na-prod\",instance=\"monitoring.na-prod.chubb.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"chubb-na-prod\",instance=\"monitoring.na-prod.chubb.quadient.cloud:9100\"})*100",
     "legendFormat": "monitoring"
    }
   ]
  },
  {
   "title": "Disk Space Used Monitoring VM",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"monitoring.*\", instanceName=\"chubb-na-prod\", device!~'rootfs', mountpoint!=\"/mnt/hmstemp\"} * 100) / node_filesystem_size_bytes{instance=~\"monitoring.*\", instanceName=\"chubb-na-prod\", device!~'rootfs', mountpoint!=\"/mnt/hmstemp\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Interactive 0 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive0.na-prod.chubb.quadient.cloud:9100\", instanceName=\"chubb-na-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive0.na-prod.chubb.quadient.cloud:9100\", instanceName=\"chubb-na-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Interactive 1 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive1.na-prod.chubb.quadient.cloud:9100\", instanceName=\"chubb-na-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive1.na-prod.chubb.quadient.cloud:9100\", instanceName=\"chubb-na-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Scaler 0 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler0.na-prod.chubb.quadient.cloud:9100\", instanceName=\"chubb-na-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler0.na-prod.chubb.quadient.cloud:9100\", instanceName=\"chubb-na-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Scaler 1 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler1.na-prod.chubb.quadient.cloud:9100\", instanceName=\"chubb-na-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler1.na-prod.chubb.quadient.cloud:9100\", instanceName=\"chubb-na-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Scaler 2 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler2.na-prod.chubb.quadient.cloud:9100\", instanceName=\"chubb-na-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler2.na-prod.chubb.quadient.cloud:9100\", instanceName=\"chubb-na-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Scalers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Failed jobs",
   "type": "timeseries",
   "description": "Indicates jobs that failed to process.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_job_runs_total{instance=~\"scaler0.na-prod.chubb.quadient.cloud:30600|scaler1.na-prod.chubb.quadient.cloud:30600|scaler2.na-prod.chubb.quadient.cloud:30600\", status=\"failed\"}[5m])",
     "legendFormat": "{{instance}}/{{group}}"
    }
   ]
  },
  {
   "title": "Completed jobs",
   "type": "timeseries",
   "description": "Indicates jobs that have been successfully processed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_job_runs_total{instance=~\"scaler0.na-prod.chubb.quadient.cloud:30600|scaler1.na-prod.chubb.quadient.cloud:30600|scaler2.na-prod.chubb.quadient.cloud:30600\", status=\"completed\"}[5m])",
     "legendFormat": "{{instance}}/{{group}}"
    }
   ]
  },
  {
   "title": "Canceled jobs",
   "type": "timeseries",
   "description": "Indicates jobs that have been successfully processed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_job_runs_total{status=\"canceled\", instance=~\"scaler0.na-prod.chubb.quadient.cloud:30600|scaler1.na-prod.chubb.quadient.cloud:30600|scaler2.na-prod.chubb.quadient.cloud:30600\"}[5m])",
     "legendFormat": "{{instance}}/{{group}}"
    }
   ]
  },
  {
   "title": "Processing jobs",
   "type": "timeseries",
   "description": "Provides the number of all the jobs that are currently being processed.\nUse this metric to create custom alerts about the number of currently processed jobs that is rapidly growing. That could indicate issues, for example, with jobs being stuck in a loop in the Script workflow module.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_processing_jobs_total{instance=~\"scaler0.na-prod.chubb.quadient.cloud:30600|scaler1.na-prod.chubb.quadient.cloud:30600|scaler2.na-prod.chubb.quadient.cloud:30600\"}[5m])",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Average IPS Queue Waiting Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(scaler_processing_jobs_total{instance=~\"scaler0.na-prod.chubb.quadient.cloud:30600|scaler1.na-prod.chubb.quadient.cloud:30600|scaler2.na-prod.chubb.quadient.cloud:30600\"}[5m])",
     "legendFormat": "{{instance}}/{{group}}"
    }
   ]
  },
  {
   "title": "Scaler workflows",
   "type": "timeseries",
   "description": "Provides the number of deployed workflows for each workflow type, and for each of the following statuse",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scaler_deployed_workflows_total{instance=~\"scaler0.na-prod.chubb.quadient.cloud:30600|scaler1.na-prod.chubb.quadient.cloud:30600|scaler2.na-prod.chubb.quadient.cloud:30600\"}",
     "legendFormat": "{{instance}}/{{ group }}: {{ status }}"
    }
   ]
  },
  { "title": "Interactives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Number of tickets",
   "type": "timeseries",
   "description": "Number of tickets created since Interactive startup.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "II_CreatedTicketsCount_total{instance=~\"interactive0.na-prod.chubb.quadient.cloud:30701|interactive1.na-prod.chubb.quadient.cloud:30701\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IPS call errors",
   "type": "timeseries",
   "description": "Number of IPS calls made ending in errors since Interactive startup.\nNumber of IPS calls ending in a timeout made since Interactive startup.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "targets": [
    {
     "expr": "rate(II_IPSCallExceptionCount_total{instance=~\"interactive0.na-prod.chubb.quadient.cloud:30701|interactive1.na-prod.chubb.quadient.cloud:30701\"}[5m])",
     "legendFormat": "IPS Call Expections/{{instance}}"
    }
   ]
  },
  {
   "title": "Interactive requests & errors",
   "type": "timeseries",
   "description": "Number of user synchronization errors since Interactive startup.\nNumber of REST/SOAP requests received since Interactive startup.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "targets": [
    {
     "expr": "increase(II_InteractiveError{instance=~\"interactive0.na-prod.chubb.quadient.cloud:30701|interactive1.na-prod.chubb.quadient.cloud:30701\"}[5m])",
     "legendFormat": "II Errors/{{instance}}/{{Type}}"
    },
    {
     "expr": "increase(II_InteractiveRequest_count{instance=~\"interactive0.na-prod.chubb.quadient.cloud:30701|interactive1.na-prod.chubb.quadient.cloud:30701\"}[5m])",
     "legendFormat": "II Requests/{{instance}}"
    },
    {
     "expr": "increase(II_InteractiveRequestExceptionCount{instance=~\"interactive0.na-prod.chubb.quadient.cloud:30701|interactive1.na-prod.chubb.quadient.cloud:30701\"}[5m])",
     "legendFormat": "II Errors/{{instance}}/Requests"
    }
   ]
  },
  {
   "title": "Number of users",
   "type": "timeseries",
   "description": "Number of currently logged in users (active session only).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "II_DBSessions{instance=~\"interactive0.na-prod.chubb.quadient.cloud:30701|interactive1.na-prod.chubb.quadient.cloud:30701\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Drafts and Tickets",
   "type": "timeseries",
   "description": "Number of currently active drafts and tickets, and drafts and tickets that are marked for deletion. Numbers are grouped by: active drafts, drafts marked for deletion, active tickets, tickets marked for deletion.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
   "targets": [
    {
     "expr": "II_DBData{instance=~\"interactive0.na-prod.chubb.quadient.cloud:30701|interactive1.na-prod.chubb.quadient.cloud:30701\"}",
     "legendFormat": "{{instance}}/{{ObjectType}}/{{State}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Number of currently active and idle Interactive connections to the database.\nNumber of currently active and idle Interactive connections to Inspire Content Manager (ICM).\n\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "targets": [
    {
     "expr": "II_DBConnections{instance=~\"interactive0.na-prod.chubb.quadient.cloud:30701|interactive1.na-prod.chubb.quadient.cloud:30701\"}",
     "legendFormat": "DB {{instance}}/{{Connection}}"
    },
    {
     "expr": "II_ICMConnections{instance=~\"interactive0.na-prod.chubb.quadient.cloud:30701|interactive1.na-prod.chubb.quadient.cloud:30701\"}",
     "legendFormat": "ICM {{instance}}/{{Connection}}"
    },
    {
     "expr": "II_IPSConnections{instance=~\"interactive0.na-prod.chubb.quadient.cloud:30701|interactive1.na-prod.chubb.quadient.cloud:30701\"}",
     "legendFormat": "IPS {{instance}}/{{Connection}}"
    }
   ]
  },
  { "title": "Scaler JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Scaler heap used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"heap\",instance=\"scaler0.na-prod.chubb.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"scaler0.na-prod.chubb.quadient.cloud:30600\"})",
     "legendFormat": "Scaler 0"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"scaler1.na-prod.chubb.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"scaler1.na-prod.chubb.quadient.cloud:30600\"})",
     "legendFormat": "Scaler 1"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"scaler2.na-prod.chubb.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"scaler2.na-prod.chubb.quadient.cloud:30600\"})",
     "legendFormat": "Scaler 2"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"scaler3.na-prod.chubb.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"scaler3.na-prod.chubb.quadient.cloud:30600\"})",
     "legendFormat": "Scaler 3"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"scaler4.na-prod.chubb.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"scaler4.na-prod.chubb.quadient.cloud:30600\"})",
     "legendFormat": "Scaler 4"
    }
   ]
  },
  {
   "title": "Scaler start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{customerName=\"CHUBBAMERICAS\",job=\"chubb-na-prod-scaler-vm\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Heap Scaler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"scaler0.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler0.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"scaler1.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler1.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"scaler2.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler2.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"scaler2.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"scaler3.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler3.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"scaler3.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"scaler4.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler4.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"scaler4.na-prod.chubb.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Scaler thread states",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"scaler0.na-prod.chubb.quadient.cloud:30600\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"scaler1.na-prod.chubb.quadient.cloud:30600\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"scaler2.na-prod.chubb.quadient.cloud:30600\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"scaler3.na-prod.chubb.quadient.cloud:30600\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"scaler4.na-prod.chubb.quadient.cloud:30600\"})",
     "legendFormat": "sum by(state) (jvm_threads_state{instance=\"scaler3.na-prod.chubb.quadient.cloud:30600\"})"
    }
   ]
  },
  { "title": "Interactive JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Interactive heap used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"interactive0.na-prod.chubb.quadient.cloud:30701\"})*100/sum(jvm_memory_bytes_max{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"interactive0.na-prod.chubb.quadient.cloud:30701\"})",
     "legendFormat": "Interactive 0"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"interactive1.na-prod.chubb.quadient.cloud:30701\",instanceName=\"chubb-na-prod\"})*100/sum(jvm_memory_bytes_max{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"interactive1.na-prod.chubb.quadient.cloud:30701\"})",
     "legendFormat": "Interactive 1"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"interactive2.na-prod.chubb.quadient.cloud:30701\",instanceName=\"chubb-na-prod\"})*100/sum(jvm_memory_bytes_max{customerName=\"CHUBBAMERICAS\",area=\"heap\",instance=\"interactive2.na-prod.chubb.quadient.cloud:30701\"})",
     "legendFormat": "interactive 2"
    }
   ]
  },
  {
   "title": "Interactive start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{customerName=\"CHUBBAMERICAS\",job=\"chubb-na-prod-interactive-vm\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Heap Interactive 0",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"interactive0.na-prod.chubb.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive0.na-prod.chubb.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"interactive0.na-prod.chubb.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Heap Interactive 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"interactive1.na-prod.chubb.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive1.na-prod.chubb.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"interactive1.na-prod.chubb.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Heap Interactive 0",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"interactive0.na-prod.chubb.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive0.na-prod.chubb.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"interactive0.na-prod.chubb.quadient.cloud:30701\",area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Interactive 1 thread states",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"interactive1.na-prod.chubb.quadient.cloud:30701\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Interactive 2 thread states",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"interactive2.na-prod.chubb.quadient.cloud:30701\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Interactive 1 thread states",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"interactive1.na-prod.chubb.quadient.cloud:30701\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 134 },
     "targets": [
      {
       "expr": "{job=\"scalerlogs\"}"
      }
     ]
    },
    {
     "title": "Scaler ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "{job=\"icmlogs\", instance=~\"scaler[0-9]+.*\"}"
      }
     ]
    },
    {
     "title": "Scaler IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
     "targets": [
      {
       "expr": "{job=\"ipslogs\", instance=~\"scaler[0-9]+.*\"}"
      }
     ]
    },
    {
     "title": "Interactive Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "{job=\"interactivelogs\"}"
      }
     ]
    },
    {
     "title": "Interactive ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
     "targets": [
      {
       "expr": "{job=\"icmlogs\", instance=~\"interactive[0-9]+.*\"}"
      }
     ]
    },
    {
     "title": "Interactive  IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
     "targets": [
      {
       "expr": "{job=\"ipslogs\", instance=~\"interactive.*.na-prod.chubb.quadient.cloud\"}"
      }
     ]
    }
   ]
  }
 ]
}