{
 "title": "CNJDOH-PROD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "qmsDatasource", "label": "QMS Datasource", "query": "prometheus" },
   { "name": "qmsInstanceName", "label": "QMS Instance name", "query": "cnjdoh-prod" }
  ]
 },
 "panels": [
  { "title": "Linux VM Overview", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Server's Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Automation traffic lights properly. \n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(up{job=~\".*vm\", instanceName=\"cnjdoh-prod\"}, \"grafanaLabel\", \"$1\", \"instance\", \"^([^.]+)\\\\..+\")",
     "legendFormat": "{{grafanaLabel}}"
    },
    {
     "expr": "up{instanceName=\"cnjdoh-qar-prod\",instance=\"localhost:30600\"}",
     "legendFormat": "scalerqar"
    }
   ]
  },
  {
   "title": "Inspire heartbeat",
   "type": "stat",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{customerName=\"C-NJ-DOH\", state=\"active\", name=~\"Inspire.*service\", instanceName=\"cnjdoh-prod\", environment=\"prod1\"}",
     "legendFormat": "{{instance}}: {{ name}}"
    },
    {
     "expr": "windows_service_state{instanceName=\"cnjdoh-qar-prod\",state=\"running\", name=\"inspire scaler 30600\",environment=\"qar-prod\"}",
     "legendFormat": "{{instanceName}}: {{ name}}"
    },
    {
     "expr": "windows_service_state{instanceName=\"cnjdoh-qar-prod\",state=\"running\", name=\"icm_30535\",environment=\"qar-prod\"}",
     "legendFormat": "{{instanceName}}: {{ name}}"
    },
    {
     "expr": "windows_service_state{instanceName=\"cnjdoh-qar-prod\",state=\"running\", name=\"ips_30354\",environment=\"qar-prod\"}",
     "legendFormat": "{{instanceName}}: {{ name}}"
    },
    {
     "expr": "windows_service_state{instanceName=\"cnjdoh-qar-prod\",state=\"running\", name=\"ondemand load data (archive)\",environment=\"qar-prod\"}",
     "legendFormat": "{{instanceName}}: {{ name}}"
    },
    {
     "expr": "windows_service_state{instanceName=\"cnjdoh-qar-prod\",state=\"running\", name=\"mssqlserver\",environment=\"qar-prod\"}",
     "legendFormat": "{{instanceName}}: {{ name}}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"cnjdoh-prod\", instance!~\"monitoring.*\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"cnjdoh-prod\", instance!~\"monitoring.*\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}: {{ name}}"
    },
    {
     "expr": "avg_over_time((sum without() (windows_service_state{state=\"running\", name=\"inspire scaler 30600\", instanceName=\"cnjdoh-qar-prod\"}) or (0 * sum_over_time(windows_service_state{state=\"running\", name=\"inspire scaler 30600\", instanceName=\"cnjdoh-qar-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instanceName}}: {{ name}}"
    },
    {
     "expr": "avg_over_time((sum without() (windows_service_state{state=\"running\", name=\"icm_30535\", instanceName=\"cnjdoh-qar-prod\"}) or (0 * sum_over_time(windows_service_state{state=\"running\", name=\"icm_30535\", instanceName=\"cnjdoh-qar-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instanceName}}: {{ name}}"
    },
    {
     "expr": "avg_over_time((sum without() (windows_service_state{state=\"running\", name=\"ips_30354\", instanceName=\"cnjdoh-qar-prod\"}) or (0 * sum_over_time(windows_service_state{state=\"running\", name=\"ips_30354\", instanceName=\"cnjdoh-qar-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instanceName}}: {{ name}}"
    },
    {
     "expr": "avg_over_time((sum without() (windows_service_state{state=\"running\", name=\"mssqlserver\", instanceName=\"cnjdoh-qar-prod\"}) or (0 * sum_over_time(windows_service_state{state=\"running\", name=\"mssqlserver\", instanceName=\"cnjdoh-qar-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instanceName}}: {{ name}}"
    },
    {
     "expr": "avg_over_time((sum without() (windows_service_state{state=\"running\", name=\"ondemand load data (archive)\", instanceName=\"cnjdoh-qar-prod\"}) or (0 * sum_over_time(windows_service_state{state=\"running\", name=\"ondemand load data (archive)\", instanceName=\"cnjdoh-qar-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instanceName}}: {{ name}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 22, "w": 8, "x": 16, "y": 9 } },
  {
   "title": "Server's Percentage Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"doh-nj-dev\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"doh-nj-dev\"}[$__range])))[$__range:1m]) * 100, \"grafanaLabel\", \"$1\", \"instance\", \"^([^.]+)\\\\..+\")",
     "legendFormat": "{{ grafanaLabel }}"
    },
    {
     "expr": "label_replace(avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"cnjdoh-prod\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"cnjdoh-prod\"}[$__range])))[$__range:1m]) * 100, \"grafanaLabel\", \"$1\", \"instance\", \"^([^.]+)\\\\..+\")",
     "legendFormat": "{{grafanaLabel}}"
    },
    {
     "expr": "label_replace(avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"cnjdoh-qar-prod\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"cnjdoh-qar-prod\"}[$__range])))[$__range:1m]) * 100, \"grafanaLabel\", \"$1\", \"instance\", \"^([^.]+)\\\\..+\")",
     "legendFormat": "scalerqar"
    }
   ]
  },
  {
   "title": "RHEL security updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "label_replace(hms_dnf{instanceName=\"doh-nj-dev\",type=~\"Critical|Important|Moderate\"}, \"serverName\", \"$1\", \"instance\", \"^([^.]+)\\\\..+\")",
     "legendFormat": "{{serverName}}: {{type}}"
    },
    {
     "expr": "label_replace(hms_dnf{instanceName=\"cnjdoh-prod\",type=~\"Critical|Important|Moderate\"}, \"serverName\", \"$1\", \"instance\", \"^([^.]+)\\\\..+\")",
     "legendFormat": "{{serverName}}: {{type}}"
    }
   ]
  },
  { "title": "Shared Panels", "type": "dashlist", "gridPos": { "h": 9, "w": 6, "x": 0, "y": 25 } },
  {
   "title": "Audit Log",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_audit_status{instanceName=\"cnjdoh-prod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Daily (Monday - Saturday)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_backup_info_daily_all{instanceName=\"cnjdoh-prod\",backupType=\"daily\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Weekly (4 Sundays)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_backup_info_weekly_all{instanceName=\"cnjdoh-prod\",backupType=\"weekly\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backups Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resource": "/subscriptions/e38c5d4b-7180-437d-84a3-7c04ba4cfec9/resourceGroups/hmsrg-cnjdoh-hub-prod/providers/Microsoft.RecoveryServices/vaults/rsv-cnjdoh-prod"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "azureLogAnalytics": {
        "resource": "/subscriptions/3caf960b-e93d-4863-9128-af667b1c44a2/resourceGroups/hmsrg-caldhr-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-caldhr-nonprod"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.recoveryservices/vaults",
        "resourceGroup": "hmsrg-cnjdoh-hub-prod",
        "resourceName": "rsv-cnjdoh-prod",
        "timeGrain": "auto"
       },
       "subscription": "e38c5d4b-7180-437d-84a3-7c04ba4cfec9"
      }
     ]
    },
    {
     "title": "Daily (Monday - Saturday)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info_daily_all{containerName=~\".*db$\",instanceName=\"cnjdoh-prod\",backupType=\"daily\"}",
       "legendFormat": "{{backupItem}}-database"
      }
     ]
    },
    {
     "title": "Weekly (4 Sundays)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info_weekly_all{containerName=~\".*db$\",instanceName=\"cnjdoh-prod\",backupType=\"weekly\"}",
       "legendFormat": "{{backupItem}}-database"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs Processing ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler workflows (Job Duration)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "hms_scaler_jobDuration{instanceName=\"cnjdoh-prod\", workflow!=\"Test\"}",
       "legendFormat": "{{workflow}}"
      }
     ]
    },
    {
     "title": "Scaler QAR workflows (Job Duration)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "hms_scaler_jobDuration{instanceName=\"cnjdoh-qar-prod\"}",
       "legendFormat": "{{workflow}}"
      }
     ]
    },
    {
     "title": "Number of requests over 3s Past 24h",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= ago(24h)  // Filter data for the last 24 hours\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, clientResponseTime_d, serverResponseLatency_s\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count() by RequestType, RequestEndpoint\r\n| render table",
        "resource": "/subscriptions/e38c5d4b-7180-437d-84a3-7c04ba4cfec9/resourceGroups/hmsrg-cnjdoh-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-cnjdoh-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= ago(24h)  // Filter data for the last 24 hours\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, clientResponseTime_d, serverResponseLatency_s\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count() by RequestType, RequestEndpoint\r\n| render table",
        "resource": "/subscriptions/e38c5d4b-7180-437d-84a3-7c04ba4cfec9/resourceGroups/hmsrg-cnjdoh-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-cnjdoh-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "TotalRequests",
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-cnjdoh-hub-prod",
        "resourceName": "appgw-cnjdoh-prod",
        "timeGrain": "auto"
       },
       "subscription": "e38c5d4b-7180-437d-84a3-7c04ba4cfec9"
      },
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= ago(24h)  // Filter data for the last 24 hours\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, clientResponseTime_d, serverResponseLatency_s\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count() by RequestType, RequestEndpoint\r\n| render table",
        "resource": "/subscriptions/e38c5d4b-7180-437d-84a3-7c04ba4cfec9/resourceGroups/hmsrg-cnjdoh-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-cnjdoh-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "FailedRequests",
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-cnjdoh-hub-prod",
        "resourceName": "appgw-cnjdoh-prod",
        "timeGrain": "auto"
       },
       "subscription": "e38c5d4b-7180-437d-84a3-7c04ba4cfec9"
      }
     ]
    },
    {
     "title": "SUCCESSFUL - Average Request Time in (s) Past 24h",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and httpStatus_d < 299\r\n    and TimeGenerated >= ago(24h)\r\n| project timeStamp_t, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, timeTaken_d, clientResponseTime_d, serverResponseLatency_s\r\n| summarize RequestCount = count(), AvgTimeTaken = avg(timeTaken_d) by RequestType, RequestStatus, RequestEndpoint\r\n| order by RequestType desc, RequestCount desc",
        "resource": "/subscriptions/e38c5d4b-7180-437d-84a3-7c04ba4cfec9/resourceGroups/hmsrg-cnjdoh-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-cnjdoh-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "FAILED - Average Request Time in (s) Past 24h",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and httpStatus_d >=300\r\n    and TimeGenerated >= ago(24h)\r\n| project timeStamp_t, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, timeTaken_d, clientResponseTime_d, serverResponseLatency_s\r\n| summarize RequestCount = count(), AvgTimeTaken = avg(timeTaken_d) by RequestType, RequestStatus, RequestEndpoint\r\n| order by RequestType desc, RequestCount desc",
        "resource": "/subscriptions/e38c5d4b-7180-437d-84a3-7c04ba4cfec9/resourceGroups/hmsrg-cnjdoh-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-cnjdoh-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "AppGW Number of requests over 3s Past 24h",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= ago(24h)  // Filter data for the last 24 hours\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()",
        "resource": "/subscriptions/e38c5d4b-7180-437d-84a3-7c04ba4cfec9/resourceGroups/hmsrg-cnjdoh-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-cnjdoh-prod"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "AppGW Number of requests over 30m Past 24h",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 1800 // 1800 seconds = 30 minutes\r\n    and TimeGenerated >= ago(24h) // Filter data for the last 24 hours\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()",
        "resource": "/subscriptions/e38c5d4b-7180-437d-84a3-7c04ba4cfec9/resourceGroups/hmsrg-cnjdoh-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-cnjdoh-prod"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Number of requests over 3s - Detail Past 24h",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3 // Filter entries with timeTaken_d greater than 3 seconds\r\n    and TimeGenerated >= ago(24h)\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, ClientIP = clientIP_s, RecievedBytes = receivedBytes_d, SendBytes = sentBytes_d, ClientResponseTime = clientResponseTime_d, ServerResponseLatency = serverResponseLatency_s\r\n\r\n",
        "resource": "/subscriptions/e38c5d4b-7180-437d-84a3-7c04ba4cfec9/resourceGroups/hmsrg-cnjdoh-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-cnjdoh-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive0.cnjdoh-prod.gov.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "interactive0"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive1.cnjdoh-prod.gov.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "interactive1"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler0.cnjdoh-prod.gov.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler0"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler1.cnjdoh-prod.gov.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler1"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler2.cnjdoh-prod.gov.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler2"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(windows_cpu_time_total{mode=\"idle\",instanceName=\"cnjdoh-qar-prod\"}[5m])) * 100)",
       "legendFormat": "scalerqar"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"monitoring.cnjdoh-prod.gov.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "monitoring"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"^(.*?)cnjdoh-prod.gov.quadient.cloud:9100\"}[5m])",
       "legendFormat": "{{instance}} recv {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"^(.*?)cnjdoh-prod.gov.quadient.cloud:9100\"}[5m])",
       "legendFormat": "{{instance}} trans {{device}}"
      },
      {
       "expr": "rate(windows_net_bytes_received_total{instanceName=\"cnjdoh-qar-prod\"}[5m])",
       "legendFormat": "{{instanceName}} recv {{device}}"
      },
      {
       "expr": "rate(windows_net_bytes_sent_total{instanceName=\"cnjdoh-qar-prod\"}[5m])",
       "legendFormat": "{{instanceName}} trans {{device}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\",instance=\"interactive0.cnjdoh-prod.gov.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\",instance=\"interactive0.cnjdoh-prod.gov.quadient.cloud:9100\"})*100",
       "legendFormat": "interactive0"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\",instance=\"interactive1.cnjdoh-prod.gov.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\",instance=\"interactive1.cnjdoh-prod.gov.quadient.cloud:9100\"})*100",
       "legendFormat": "interactive1"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\",instance=\"scaler0.cnjdoh-prod.gov.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\",instance=\"scaler0.cnjdoh-prod.gov.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler0"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\",instance=\"scaler1.cnjdoh-prod.gov.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\",instance=\"scaler1.cnjdoh-prod.gov.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler1"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\",instance=\"scaler2.cnjdoh-prod.gov.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\",instance=\"scaler2.cnjdoh-prod.gov.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler2"
      },
      {
       "expr": "100 - (windows_os_virtual_memory_free_bytes{instanceName=\"cnjdoh-qar-prod\"} / windows_os_virtual_memory_bytes{instanceName=\"cnjdoh-qar-prod\"})*100",
       "legendFormat": "scalerqar"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\",instance=\"monitoring.cnjdoh-prod.gov.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\",instance=\"monitoring.cnjdoh-prod.gov.quadient.cloud:9100\"})*100",
       "legendFormat": "monitoring"
      }
     ]
    },
    {
     "title": "Disk Space Used Monitoring VM",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"monitoring.*\", instanceName=\"cnjdoh-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"monitoring.*\", instanceName=\"cnjdoh-prod\",device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 0 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler0.cnjdoh-prod.gov.quadient.cloud:9100\", device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler0.cnjdoh-prod.gov.quadient.cloud:9100\", device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 1 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler1.cnjdoh-prod.gov.quadient.cloud:9100\", device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler1.cnjdoh-prod.gov.quadient.cloud:9100\", device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 2 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler2.cnjdoh-prod.gov.quadient.cloud:9100\", device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler2.cnjdoh-prod.gov.quadient.cloud:9100\", device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Interactive 0 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive0.cnjdoh-prod.gov.quadient.cloud:9100\", device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive0.cnjdoh-prod.gov.quadient.cloud:9100\", device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Interactive 1 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive1.cnjdoh-prod.gov.quadient.cloud:9100\", device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive1.cnjdoh-prod.gov.quadient.cloud:9100\", device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "QMS Data Service Storage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         3600000
        ],
        "dimensionFilters": [],
        "metricName": "UsedCapacity",
        "metricNamespace": "microsoft.storage/storageaccounts",
        "region": "USGov Virginia",
        "resources": [
         {
          "metricNamespace": "Microsoft.Storage/storageAccounts",
          "region": "USGov Virginia",
          "resourceGroup": "hmsrg-cnjdoh-prod",
          "resourceName": "sahmsdatalwim5y4jwwbs6",
          "subscription": "e38c5d4b-7180-437d-84a3-7c04ba4cfec9"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "e38c5d4b-7180-437d-84a3-7c04ba4cfec9"
      }
     ]
    }
   ]
  },
  {
   "title": "Scalers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler workflows",
     "type": "timeseries",
     "description": "Provides the number of deployed workflows for each workflow type, and for each of the following statuse",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "scaler_deployed_workflows_total{instance=~\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600|scaler1.cnjdoh-prod.gov.quadient.cloud:30600|scaler2.cnjdoh-prod.gov.quadient.cloud:30600\"}",
       "legendFormat": "{{instance}}/{{ group }}: {{ status }}"
      }
     ]
    },
    {
     "title": "Processing jobs",
     "type": "timeseries",
     "description": "Provides the number of all the jobs that are currently being processed.\nUse this metric to create custom alerts about the number of currently processed jobs that is rapidly growing. That could indicate issues, for example, with jobs being stuck in a loop in the Script workflow module.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_processing_jobs_total{instance=~\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600|scaler1.cnjdoh-prod.gov.quadient.cloud:30600|scaler2.cnjdoh-prod.gov.quadient.cloud:30600\"}[5m])",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Completed jobs",
     "type": "timeseries",
     "description": "Indicates jobs that have been successfully processed.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{instance=~\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600|scaler1.cnjdoh-prod.gov.quadient.cloud:30600|scaler2.cnjdoh-prod.gov.quadient.cloud:30600\", status=\"completed\"}[5m])",
       "legendFormat": "{{instance}}/{{ group }}: {{ status }}"
      }
     ]
    },
    {
     "title": "Failed jobs",
     "type": "timeseries",
     "description": "Indicates jobs that failed to process.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{instance=~\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600|scaler1.cnjdoh-prod.gov.quadient.cloud:30600|scaler2.cnjdoh-prod.gov.quadient.cloud:30600\", status=\"failed\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    {
     "title": "Canceled jobs",
     "type": "timeseries",
     "description": "Indicates jobs that have been successfully processed.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{instance=~\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600|scaler1.cnjdoh-prod.gov.quadient.cloud:30600|scaler2.cnjdoh-prod.gov.quadient.cloud:30600\", status=\"canceled\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    {
     "title": "Average IPS Queue Waiting Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(scaler_processing_jobs_total{instance=~\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600|scaler1.cnjdoh-prod.gov.quadient.cloud:30600|scaler2.cnjdoh-prod.gov.quadient.cloud:30600\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scalers QAR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler workflows",
     "type": "timeseries",
     "description": "Provides the number of deployed workflows for each workflow type, and for each of the following statuse",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "scaler_deployed_workflows_total{customerName=\"C-NJ-DOH\",instanceName=\"cnjdoh-qar-prod\"}",
       "legendFormat": "{{instanceName}}/{{ group }}: {{ status }}"
      }
     ]
    },
    {
     "title": "Processing jobs",
     "type": "timeseries",
     "description": "Provides the number of all the jobs that are currently being processed.\nUse this metric to create custom alerts about the number of currently processed jobs that is rapidly growing. That could indicate issues, for example, with jobs being stuck in a loop in the Script workflow module.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_processing_jobs_total{instanceName=\"cnjdoh-qar-prod\",instance=\"localhost:30600\"}[5m])",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Completed jobs",
     "type": "timeseries",
     "description": "Indicates jobs that have been successfully processed.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{status=\"completed\",instanceName=\"cnjdoh-qar-prod\",instance=\"localhost:30600\"}[5m])",
       "legendFormat": "{{instanceName}}/{{ group }}: {{ status }}"
      }
     ]
    },
    {
     "title": "Failed jobs",
     "type": "timeseries",
     "description": "Indicates jobs that failed to process.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{status=\"failed\",instanceName=\"cnjdoh-qar-prod\",instance=\"localhost:30600\"}[5m])",
       "legendFormat": "{{instanceName}}/{{group}}"
      }
     ]
    },
    {
     "title": "Canceled jobs",
     "type": "timeseries",
     "description": "Indicates jobs that have been successfully processed.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{status=\"canceled\",instanceName=\"cnjdoh-qar-prod\",instance=\"localhost:30600\"}[5m])",
       "legendFormat": "{{instanceName}}/{{group}}"
      }
     ]
    },
    {
     "title": "Average IPS Queue Waiting Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(scaler_processing_jobs_total{instanceName=\"cnjdoh-qar-prod\",instance=\"localhost:30600\"}[5m])",
       "legendFormat": "{{instanceName}}/{{group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scaler JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler heap used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{area=\"heap\",instance=\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{area=\"heap\",instance=\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 0"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{area=\"heap\",instance=\"scaler1.cnjdoh-prod.gov.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{area=\"heap\",instance=\"scaler1.cnjdoh-prod.gov.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 1"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{area=\"heap\",instance=\"scaler2.cnjdoh-prod.gov.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{area=\"heap\",instance=\"scaler2.cnjdoh-prod.gov.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 2"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{area=\"heap\",instanceName=\"cnjdoh-qar-prod\",instance=\"localhost:30600\"})*100/sum(jvm_memory_bytes_max{area=\"heap\",instanceName=\"cnjdoh-qar-prod\",instance=\"localhost:30600\"})",
       "legendFormat": "Scaler QAR"
      }
     ]
    },
    {
     "title": "JVM Heap Scaler",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler1.cnjdoh-prod.gov.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler1.cnjdoh-prod.gov.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler1.cnjdoh-prod.gov.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler2.cnjdoh-prod.gov.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler2.cnjdoh-prod.gov.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler2.cnjdoh-prod.gov.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Heap Scaler QAR",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{area=\"heap\", instanceName=\"cnjdoh-qar-prod\", instance=\"localhost:30600\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{area=\"heap\", instanceName=\"cnjdoh-qar-prod\", instance=\"localhost:30600\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{area=\"heap\", instanceName=\"cnjdoh-qar-prod\", instance=\"localhost:30600\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Scaler start time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(process_start_time_seconds{job=\"cnjdoh-prod-scaler-vm\"}*1000,\"instanceLabel\", \"$1\", \"instance\", \"^([^.]+)\\\\..+\")",
       "legendFormat": "{{instanceLabel}}"
      },
      {
       "expr": "label_replace(process_start_time_seconds{job=\"cnjdoh-qar-nonprod-qar-vm\"}*1000,\"instanceLabel\", \"$1\", \"instance\", \"^([^.]+)\\\\..+\")",
       "legendFormat": "scalerqar"
      }
     ]
    },
    {
     "title": "Scaler thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler0.cnjdoh-prod.gov.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler1.cnjdoh-prod.gov.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler2.cnjdoh-prod.gov.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Scaler thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instanceName=\"cnjdoh-qar-nonprod\",instance=\"localhost:30600\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of tickets",
     "type": "timeseries",
     "description": "Number of tickets created since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "II_CreatedTicketsCount_total{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701|interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IPS call errors",
     "type": "timeseries",
     "description": "Number of IPS calls made ending in errors since Interactive startup.\nNumber of IPS calls ending in a timeout made since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
     "targets": [
      {
       "expr": "rate(II_IPSCallExceptionCount_total{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701|interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"}[5m])",
       "legendFormat": "IPS Call Expections/{{instance}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "Number of currently active and idle Interactive connections to the database.\nNumber of currently active and idle Interactive connections to Inspire Content Manager (ICM).\n\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
     "targets": [
      {
       "expr": "II_DBConnections{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701|interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"}",
       "legendFormat": "DB {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_ICMConnections{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701|interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"}",
       "legendFormat": "ICM {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_IPSConnections{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701|interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"}",
       "legendFormat": "IPS {{instance}}/{{Connection}}"
      }
     ]
    },
    {
     "title": "Number of users",
     "type": "timeseries",
     "description": "Number of currently logged in users (active session only).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "II_DBSessions{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701|interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Drafts and Tickets",
     "type": "timeseries",
     "description": "Number of currently active drafts and tickets, and drafts and tickets that are marked for deletion. Numbers are grouped by: active drafts, drafts marked for deletion, active tickets, tickets marked for deletion.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
     "targets": [
      {
       "expr": "II_DBData{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701|interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}/{{ObjectType}}/{{State}}"
      }
     ]
    },
    {
     "title": "Interactive requests & errors",
     "type": "timeseries",
     "description": "Number of user synchronization errors since Interactive startup.\nNumber of REST/SOAP requests received since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
     "targets": [
      {
       "expr": "increase(II_InteractiveError_total{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701|interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Requests Errot Total/{{instance}}"
      },
      {
       "expr": "increase(II_InteractiveRequest_count{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701|interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Requests Count /{{instance}}"
      },
      {
       "expr": "increase(II_InteractiveRequestExceptionCount{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701|interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Errors Count /{{instance}}/Requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactive JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactive heap used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{area=\"heap\",instance=\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701\"})*100/sum(jvm_memory_bytes_max{area=\"heap\",instance=\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 0"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{area=\"heap\",instance=\"interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"})*100/sum(jvm_memory_bytes_max{area=\"heap\",instance=\"interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 1"
      }
     ]
    },
    {
     "title": "Interactive start time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(process_start_time_seconds{job=\"cnjdoh-prod-interactive-vm\"}*1000, \"instanceLabel\", \"$1\", \"instance\", \"^([^.]+)\\\\..+\")",
       "legendFormat": "{{instanceLabel}}"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 0",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 1",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive1.cnjdoh-prod.gov.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive1.cnjdoh-prod.gov.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive1.cnjdoh-prod.gov.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Interactive 0 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive0.cnjdoh-prod.gov.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Interactive 1 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 195 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive1.cnjdoh-prod.gov.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 189 },
     "targets": [
      {
       "expr": "{job=\"scalerlogs\"}"
      }
     ]
    },
    {
     "title": "Scaler ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
     "targets": [
      {
       "expr": "{instance=~\"scaler2.cnjdoh-prod.gov.quadient.cloud|scaler1.cnjdoh-prod.gov.quadient.cloud|scaler0.cnjdoh-prod.gov.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Scaler IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
     "targets": [
      {
       "expr": "{instance=~\"scaler2.cnjdoh-prod.gov.quadient.cloud|scaler1.cnjdoh-prod.gov.quadient.cloud|scaler0.cnjdoh-prod.gov.quadient.cloud\", job=\"ipslogs\"}"
      }
     ]
    },
    {
     "title": "Interactive Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 210 },
     "targets": [
      {
       "expr": "{job=\"interactivelogs\"}"
      }
     ]
    },
    {
     "title": "Interactive ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 223 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud|interactive1.cnjdoh-prod.gov.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Interactive  IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 223 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.cnjdoh-prod.gov.quadient.cloud|interactive1.cnjdoh-prod.gov.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    }
   ]
  }
 ]
}