{
 "title": "Excellusbcbs - PROD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "qmsInstanceName", "label": "QMS Instance name", "query": "excellusbcbs-prod" },
   { "name": "qmsDatasource", "label": "QMS Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Linux VM Overview", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 } },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "RHEL security updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "hms_dnf{instanceName=\"excellusbcbs-prod\",type=~\"Critical|Important|Moderate\"}",
     "legendFormat": "{{job}}:{{type}}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat",
   "type": "stat",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance, name) (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"excellusbcbs-prod\", environment=\"prod1\"})",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"excellusbcbs-prod\", instance!~\"monitoring.*\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"excellusbcbs-prod\", instance!~\"monitoring.*\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 22, "w": 7, "x": 17, "y": 12 } },
  { "title": "Shared Panels", "type": "dashlist", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 } },
  {
   "title": "Scaler File Share Sync Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_status_active{job_name=~\"cron-job-azsync-excellusbcbs-prod-scaler-.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests over 3s ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()\r\n",
      "resource": "/subscriptions/61bc806e-8e88-434b-907c-ab77d1ec9ff0/resourceGroups/hmsrg-excellusbcbs-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-excellusbcbs-prod",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod",
      "resourceName": "appgw-excellusbcbs-nonprod",
      "timeGrain": "auto"
     },
     "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
    }
   ]
  },
  {
   "title": "Audit Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_audit_status{instanceName=\"excellusbcbs-prod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaler File Share Sync Failure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_status_failed{job_name=~\"cron-job-azsync-excellusbcbs-prod-scaler-.+\"} >=1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests over 30m ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 1800 // 1800 seconds = 30 minutes\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()",
      "resource": "/subscriptions/61bc806e-8e88-434b-907c-ab77d1ec9ff0/resourceGroups/hmsrg-excellusbcbs-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-excellusbcbs-prod",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod",
      "resourceName": "appgw-excellusbcbs-nonprod",
      "timeGrain": "auto"
     },
     "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
    }
   ]
  },
  { "title": "Backups Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Daily VM/Disk Azure backup",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
      "resource": "/subscriptions/61bc806e-8e88-434b-907c-ab77d1ec9ff0/resourceGroups/hmsrg-excellusbcbs-hub-prod/providers/Microsoft.RecoveryServices/vaults/rsv-excellusbcbs-prod",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Azure VM/Disks backup health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(7d)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
      "resource": "/subscriptions/de74e022-0016-4972-ac5a-d17f177ed92d/resourceGroups/hmsrg-gfbank-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-gfbank-nonprod",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "healthStatus",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "backupInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "BackupHealthEvent",
      "metricNamespace": "microsoft.recoveryservices/vaults",
      "resourceGroup": "hmsrg-excellusbcbs-hub-prod",
      "resourceName": "rsv-excellusbcbs-prod",
      "timeGrain": "auto"
     },
     "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
    }
   ]
  },
  {
   "title": "DB - Daily (Monday - Saturday)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hms_backup_info_daily_all{containerName=~\".*db$\",instanceName=\"excellusbcbs-prod\"}",
     "legendFormat": "{{backupItem}}-database"
    }
   ]
  },
  {
   "title": "DB - Weekly (4 Sundays)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hms_backup_info_weekly_all{containerName=~\".*db$\",instanceName=\"excellusbcbs-prod\"}",
     "legendFormat": "{{backupItem}}-database"
    }
   ]
  },
  {
   "title": "All Daily (Monday - Saturday)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_backup_info_daily_all{instanceName=\"excellusbcbs-prod\",backupType=\"daily\"})"
    }
   ]
  },
  {
   "title": "All Weekly (4 Sundays)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_backup_info_weekly_all{instanceName=\"excellusbcbs-prod\",backupType=\"weekly\"})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  { "title": "CPU Usage", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 } },
  { "title": "Memory Usage", "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 } },
  { "title": "DiskSpace usage", "gridPos": { "h": 27, "w": 8, "x": 16, "y": 61 } },
  { "title": "Average CPU Usage", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 70 } },
  { "title": "File Shares usage", "gridPos": { "h": 9, "w": 8, "x": 8, "y": 70 } },
  { "title": "Network Traffic", "gridPos": { "h": 9, "w": 16, "x": 0, "y": 79 } },
  {
   "title": "Application Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler workflows (Job Duration)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "hms_scaler_jobDuration{instanceName=\"excellusbcbs-prod\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of requests over 3s ",
     "type": "table",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 152 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n  // Filter data for the last 24 hours\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, clientResponseTime_d, serverResponseLatency_s\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count() by RequestType, RequestEndpoint\r\n| render table\r\n",
        "resource": "/subscriptions/61bc806e-8e88-434b-907c-ab77d1ec9ff0/resourceGroups/hmsrg-excellusbcbs-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-excellusbcbs-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod",
        "resourceName": "appgw-excellusbcbs-nonprod",
        "timeGrain": "auto"
       },
       "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 152 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "BackendSettingsPool",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "TotalRequests",
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-excellusbcbs-hub-prod",
        "resourceName": "appgw-excellusbcbs-prod",
        "timeGrain": "auto"
       },
       "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
      },
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "FailedRequests",
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod",
        "resourceName": "appgw-excellusbcbs-nonprod",
        "timeGrain": "auto"
       },
       "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
      }
     ]
    },
    {
     "title": "SUCCESSFUL - Average Request Time",
     "type": "table",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 159 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and httpStatus_d < 299\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project timeStamp_t, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, timeTaken_d, clientResponseTime_d, serverResponseLatency_s\r\n| summarize RequestCount = count(), AvgTimeTaken = avg(timeTaken_d) by RequestType, RequestStatus, RequestEndpoint\r\n| order by RequestType desc, RequestCount desc",
        "resource": "/subscriptions/61bc806e-8e88-434b-907c-ab77d1ec9ff0/resourceGroups/hmsrg-excellusbcbs-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-excellusbcbs-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod",
        "resourceName": "appgw-excellusbcbs-nonprod",
        "timeGrain": "auto"
       },
       "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
      }
     ]
    },
    {
     "title": "FAILED - Average Request Time",
     "type": "table",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 159 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and httpStatus_d >=300\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project timeStamp_t, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, timeTaken_d, clientResponseTime_d, serverResponseLatency_s\r\n| summarize RequestCount = count(), AvgTimeTaken = avg(timeTaken_d) by RequestType, RequestStatus, RequestEndpoint\r\n| order by RequestType desc, RequestCount desc",
        "resource": "/subscriptions/61bc806e-8e88-434b-907c-ab77d1ec9ff0/resourceGroups/hmsrg-excellusbcbs-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-excellusbcbs-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod",
        "resourceName": "appgw-excellusbcbs-nonprod",
        "timeGrain": "auto"
       },
       "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
      }
     ]
    },
    {
     "title": "Number of requests over 3s - Detail",
     "type": "table",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 166 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3 // Filter entries with timeTaken_d greater than 3 seconds\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, ClientIP = clientIP_s, RecievedBytes = receivedBytes_d, SendBytes = sentBytes_d, ClientResponseTime = clientResponseTime_d, ServerResponseLatency = serverResponseLatency_s\r\n\r\n",
        "resource": "/subscriptions/61bc806e-8e88-434b-907c-ab77d1ec9ff0/resourceGroups/hmsrg-excellusbcbs-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-excellusbcbs-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-excellusbcbs-hub-nonprod",
        "resourceName": "appgw-excellusbcbs-nonprod",
        "timeGrain": "auto"
       },
       "subscription": "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
      }
     ]
    }
   ]
  },
  {
   "title": "Scalers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 } },
    { "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 } },
    {
     "title": "Canceled jobs",
     "type": "timeseries",
     "description": "Indicates jobs that have been successfully processed.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{status=\"canceled\", instance=~\"scaler0.excellusbcbs-prod.quadient.cloud:30600|scaler1.excellusbcbs-prod.quadient.cloud:30600|scaler2.excellusbcbs-prod.quadient.cloud:30600|scaler3.excellusbcbs-prod.quadient.cloud:30600|scaler4.excellusbcbs-prod.quadient.cloud:30600\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 } },
    { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 } },
    { "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 } },
    {
     "title": "Average IPS Queue Waiting Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(scaler_processing_jobs_total{instance=~\"scaler0.excellusbcbs-prod.quadient.cloud:30600|scaler1.excellusbcbs-prod.quadient.cloud:30600|scaler2.excellusbcbs-prod.quadient.cloud:30600|scaler3.excellusbcbs-prod.quadient.cloud:30600|scaler4.excellusbcbs-prod.quadient.cloud:30600\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    {
     "title": "Scaler workflows",
     "type": "timeseries",
     "description": "Provides the number of deployed workflows for each workflow type, and for each of the following statuse",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "scaler_deployed_workflows_total{instance=~\"scaler0.excellusbcbs-prod.quadient.cloud:30600|scaler1.excellusbcbs-prod.quadient.cloud:30600|scaler2.excellusbcbs-prod.quadient.cloud:30600|scaler3.excellusbcbs-prod.quadient.cloud:30600|scaler4.excellusbcbs-prod.quadient.cloud:30600\"}",
       "legendFormat": "{{instance}}/{{ group }}: {{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of tickets",
     "type": "timeseries",
     "description": "Number of tickets created since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 146 },
     "targets": [
      {
       "expr": "II_CreatedTicketsCount_total{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud:30701|interactive1.excellusbcbs-prod.quadient.cloud:30701|interactive2.excellusbcbs-prod.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IPS call errors",
     "type": "timeseries",
     "description": "Number of IPS calls made ending in errors since Interactive startup.\nNumber of IPS calls ending in a timeout made since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 146 },
     "targets": [
      {
       "expr": "rate(II_IPSCallExceptionCount_total{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud:30701|interactive1.excellusbcbs-prod.quadient.cloud:30701|interactive2.excellusbcbs-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "IPS Call Expections/{{instance}}"
      }
     ]
    },
    {
     "title": "Interactive requests & errors",
     "type": "timeseries",
     "description": "Number of user synchronization errors since Interactive startup.\nNumber of REST/SOAP requests received since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 146 },
     "targets": [
      {
       "expr": "increase(II_InteractiveError{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud:30701|interactive1.excellusbcbs-prod.quadient.cloud:30701|interactive2.excellusbcbs-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Errors/{{instance}}/{{Type}}"
      },
      {
       "expr": "increase(II_InteractiveRequest_count{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud:30701|interactive1.excellusbcbs-prod.quadient.cloud:30701|interactive2.excellusbcbs-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Requests/{{instance}}"
      },
      {
       "expr": "increase(II_InteractiveRequestExceptionCount{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud:30701|interactive1.excellusbcbs-prod.quadient.cloud:30701|interactive2.excellusbcbs-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Errors/{{instance}}/Requests"
      }
     ]
    },
    {
     "title": "Number of users",
     "type": "timeseries",
     "description": "Number of currently logged in users (active session only).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
     "targets": [
      {
       "expr": "II_DBSessions{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud:30701|interactive1.excellusbcbs-prod.quadient.cloud:30701|interactive2.excellusbcbs-prod.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Drafts and Tickets",
     "type": "timeseries",
     "description": "Number of currently active drafts and tickets, and drafts and tickets that are marked for deletion. Numbers are grouped by: active drafts, drafts marked for deletion, active tickets, tickets marked for deletion.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 154 },
     "targets": [
      {
       "expr": "II_DBData{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud:30701|interactive1.excellusbcbs-prod.quadient.cloud:30701|interactive2.excellusbcbs-prod.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}/{{ObjectType}}/{{State}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "Number of currently active and idle Interactive connections to the database.\nNumber of currently active and idle Interactive connections to Inspire Content Manager (ICM).\n\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 154 },
     "targets": [
      {
       "expr": "II_DBConnections{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud:30701|interactive1.excellusbcbs-prod.quadient.cloud:30701|interactive2.excellusbcbs-prod.quadient.cloud:30701\"}",
       "legendFormat": "DB {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_ICMConnections{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud:30701|interactive1.excellusbcbs-prod.quadient.cloud:30701|interactive2.excellusbcbs-prod.quadient.cloud:30701\"}",
       "legendFormat": "ICM {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_IPSConnections{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud:30701|interactive1.excellusbcbs-prod.quadient.cloud:30701|interactive2.excellusbcbs-prod.quadient.cloud:30701\"}",
       "legendFormat": "IPS {{instance}}/{{Connection}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scaler JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler heap used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"scaler0.excellusbcbs-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"scaler0.excellusbcbs-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 0"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"scaler1.excellusbcbs-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"scaler1.excellusbcbs-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 1"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"scaler2.excellusbcbs-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"scaler2.excellusbcbs-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 2"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"scaler3.excellusbcbs-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"scaler3.excellusbcbs-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 3"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"scaler4.excellusbcbs-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"scaler4.excellusbcbs-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 4"
      }
     ]
    },
    {
     "title": "Scaler start time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{customerName=\"EXCELLUSBCBS\",job=\"excellusbcbs-prod-scaler-vm\"}*1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Heap Scaler",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler0.excellusbcbs-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler0.excellusbcbs-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.excellusbcbs-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler1.excellusbcbs-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler1.excellusbcbs-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.excellusbcbs-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler2.excellusbcbs-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler2.excellusbcbs-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler2.excellusbcbs-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Scaler thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler0.excellusbcbs-prod.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler1.excellusbcbs-prod.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler2.excellusbcbs-prod.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactive JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactive heap used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"interactive0.excellusbcbs-prod.quadient.cloud:30701\"})*100/sum(jvm_memory_bytes_max{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"interactive0.excellusbcbs-prod.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 0"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"interactive1.excellusbcbs-prod.quadient.cloud:30701\",instanceName=\"excellusbcbs-prod\"})*100/sum(jvm_memory_bytes_max{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"interactive1.excellusbcbs-prod.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 1"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"interactive2.excellusbcbs-prod.quadient.cloud:30701\",instanceName=\"excellusbcbs-prod\"})*100/sum(jvm_memory_bytes_max{customerName=\"EXCELLUSBCBS\",area=\"heap\",instance=\"interactive2.excellusbcbs-prod.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 2"
      }
     ]
    },
    {
     "title": "Interactive start time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{customerName=\"EXCELLUSBCBS\",job=\"excellusbcbs-prod-interactive-vm\"}*1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 0",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive0.excellusbcbs-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive0.excellusbcbs-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive0.excellusbcbs-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 1",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive1.excellusbcbs-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive1.excellusbcbs-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive1.excellusbcbs-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Interactive 0 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive0.excellusbcbs-prod.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Interactive 1 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive1.excellusbcbs-prod.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "{job=\"scalerlogs\"}"
      }
     ]
    },
    {
     "title": "Scaler ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "{instance=~\"scaler2.excellusbcbs-prod.quadient.cloud|scaler1.excellusbcbs-prod.quadient.cloud|scaler0.excellusbcbs-prod.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Scaler IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "{instance=~\"scaler0.excellusbcbs-prod.quadient.cloud|scaler2.excellusbcbs-prod.quadient.cloud|scaler1.excellusbcbs-prod.quadient.cloud\", job=\"ipslogs\"}"
      }
     ]
    },
    {
     "title": "Scaler Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "{job=\"scalersenlogs\"}"
      }
     ]
    },
    {
     "title": "Interactive Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "{job=\"interactivelogs\"}"
      }
     ]
    },
    {
     "title": "Interactive ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud|interactive1.excellusbcbs-prod.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Interactive  IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.excellusbcbs-prod.quadient.cloud|interactive1.excellusbcbs-prod.quadient.cloud\", job=\"ipslogs\"}"
      }
     ]
    }
   ]
  }
 ]
}