{
 "title": "Fidelity-PROD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "qmsDatasource", "label": "QMS Datasource", "query": "prometheus" },
   { "name": "qmsCustomer", "label": "QMS Customer", "query": "fmr" },
   { "name": "qmsInstanceName", "label": "QMS Instance name", "query": "fmr-prod" }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Linux VM Overview", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 } },
    { "title": "RHEL security updates", "gridPos": { "h": 12, "w": 8, "x": 0, "y": 28 } },
    {
     "title": "Inspire heartbeat",
     "type": "stat",
     "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
     "gridPos": { "h": 22, "w": 6, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(\n  node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"$qmsInstanceName\"},\n    \"instanceShort\", \"$1\", \"instance\", \"^(.*?)\\\\.$qmsInstanceName\\\\.quadient\\\\.cloud:\\\\d+$\"\n)",
       "legendFormat": "{{instanceShort}}: {{ name}}"
      }
     ]
    },
    {
     "title": "Inspire heartbeat percentage",
     "type": "stat",
     "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
     "gridPos": { "h": 22, "w": 7, "x": 14, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(\n  avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"$qmsInstanceName\", instance!~\"monitoring.*\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"$qmsInstanceName\", instance!~\"monitoring.*\"}[$__range])))[$__range:1m]) * 100,\n    \"instanceShort\", \"$1\", \"instance\", \"^(.*?)\\\\.$qmsInstanceName\\\\.quadient\\\\.cloud:\\\\d+$\"\n)",
       "legendFormat": "{{instanceShort}}: {{ name}}"
      }
     ]
    },
    {
     "title": "All Weekly (4 Sundays)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hms_backup_info_weekly_all{instanceName=\"fmr-prod\",backupType=\"weekly\"})"
      }
     ]
    },
    {
     "title": "All Daily (Monday - Saturday)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hms_backup_info_daily_all{instanceName=\"fmr-prod\",backupType=\"daily\"})"
      }
     ]
    },
    {
     "title": "Audit Logs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hms_audit_status{instanceName=\"fmr-prod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Output File Share Sync Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_job_status_active{job_name=~\"cron-job-azsync-fmr-prod-output-.+\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Shared Panels", "type": "dashlist", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 } },
    {
     "title": "Output File Share Sync Failure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_job_status_failed{job_name=~\"cron-job-azsync-fmr-prod-output-.+\"} >=1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scaler File Share Sync Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_job_status_active{job_name=~\"cron-job-azsync-fmr-prod-scaler-.+\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of requests over 3s",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and not(\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINT\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE2\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE3\"\r\n    )\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()\r\n",
        "resource": "/subscriptions/ea549d66-7b11-4554-879a-55742d7f76a7/resourceGroups/hmsrg-fmr-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-fmr-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-fmr-hub-prod",
        "resourceName": "appgw-fmr-prod",
        "timeGrain": "auto"
       },
       "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
      }
     ]
    },
    {
     "title": "Number of requests over 30m",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 1800 // 1800 seconds = 30 minutes\r\n    and not(\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINT\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE2\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE3\"\r\n    )\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()",
        "resource": "/subscriptions/ea549d66-7b11-4554-879a-55742d7f76a7/resourceGroups/hmsrg-fmr-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-fmr-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-fmr-hub-prod",
        "resourceName": "appgw-fmr-prod",
        "timeGrain": "auto"
       },
       "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
      }
     ]
    },
    {
     "title": "Scaler File Share Sync Failure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_job_status_failed{job_name=~\"cron-job-azsync-fmr-prod-scaler-.+\"} >=1)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Splunk Forwarder Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Splunk heartbeat",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_systemd_unit_state{state=\"active\", name=~\"splunkforwarder.service\", instanceName=\"fmr-prod\", environment=\"prod1\"}",
       "legendFormat": "PROD -- {{ name}} -- {{instance}}"
      }
     ]
    },
    {
     "title": "Splunk heartbeat percentage",
     "type": "stat",
     "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"splunkforwarder.service\", instanceName=\"fmr-prod\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"splunkforwarder.service\", instanceName=\"fmr-prod\"}[$__range])))[$__range:1m]) * 100",
       "legendFormat": "PROD -- {{ name}} -- {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily VM/Disk Azure backup",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resource": "/subscriptions/ea549d66-7b11-4554-879a-55742d7f76a7/resourceGroups/hmsrg-fmr-hub-prod/providers/Microsoft.RecoveryServices/vaults/rsv-fmr-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Azure VM/Disks backup health",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(7d)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resource": "/subscriptions/de74e022-0016-4972-ac5a-d17f177ed92d/resourceGroups/hmsrg-gfbank-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-gfbank-nonprod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [
         {
          "dimension": "healthStatus",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "backupInstanceName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "BackupHealthEvent",
        "metricNamespace": "microsoft.recoveryservices/vaults",
        "resourceGroup": "hmsrg-fmr-hub-prod",
        "resourceName": "rsv-fmr-prod",
        "timeGrain": "auto"
       },
       "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
      }
     ]
    },
    {
     "title": "Daily (Monday - Saturday)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info_daily_all{containerName=~\".*db$\",instanceName=\"fmr-prod\",backupType=\"daily\"}",
       "legendFormat": "{{backupItem}}-database"
      }
     ]
    },
    {
     "title": "Weekly (4 Sundays)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info_weekly_all{containerName=~\".*db$\",instanceName=\"fmr-prod\",backupType=\"weekly\"}",
       "legendFormat": "{{backupItem}}-database"
      }
     ]
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  { "title": "CPU Usage", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"^(.*?)fmr-prod.quadient.cloud:9100\"}[5m])",
     "legendFormat": "{{instance}} recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"^(.*?)fmr-prod.quadient.cloud:9100\"}[5m])",
     "legendFormat": "{{instance}} trans {{device}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"fmr-prod\",instance=\"interactive0.fmr-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"fmr-prod\",instance=\"interactive0.fmr-prod.quadient.cloud:9100\"})*100",
     "legendFormat": "interactive0"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"fmr-prod\",instance=\"interactive1.fmr-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"fmr-prod\",instance=\"interactive1.fmr-prod.quadient.cloud:9100\"})*100",
     "legendFormat": "interactive1"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"fmr-prod\",instance=\"interactive2.fmr-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"fmr-prod\",instance=\"interactive2.fmr-prod.quadient.cloud:9100\"})*100",
     "legendFormat": "interactive2"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"fmr-prod\",instance=\"scaler0.fmr-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"fmr-prod\",instance=\"scaler0.fmr-prod.quadient.cloud:9100\"})*100",
     "legendFormat": "scaler0"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"fmr-prod\",instance=\"scaler1.fmr-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"fmr-prod\",instance=\"scaler1.fmr-prod.quadient.cloud:9100\"})*100",
     "legendFormat": "scaler1"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"fmr-prod\",instance=\"scaler2.fmr-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"fmr-prod\",instance=\"scaler2.fmr-prod.quadient.cloud:9100\"})*100",
     "legendFormat": "scaler2"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"fmr-prod\",instance=\"scaler3.fmr-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"fmr-prod\",instance=\"scaler3.fmr-prod.quadient.cloud:9100\"})*100",
     "legendFormat": "scaler3"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"fmr-prod\",instance=\"scaler4.fmr-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"fmr-prod\",instance=\"scaler4.fmr-prod.quadient.cloud:9100\"})*100",
     "legendFormat": "scaler4"
    },
    {
     "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"fmr-prod\",instance=\"monitoring.fmr-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"fmr-prod\",instance=\"monitoring.fmr-prod.quadient.cloud:9100\"})*100",
     "legendFormat": "monitoring"
    }
   ]
  },
  { "title": "Average CPU Usage", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 } },
  {
   "title": "Disk Space Used Interactive 0 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive0.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive0.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Interactive 1 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive1.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive1.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"monitoring.fmr-prod.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "monitoring"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive0.fmr-prod.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "interactive0"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive1.fmr-prod.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "interactive1"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive2.fmr-prod.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "interactive2"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler0.fmr-prod.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "scaler0"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler1.fmr-prod.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "scaler1"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler2.fmr-prod.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "scaler2"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler3.fmr-prod.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "scaler3"
    },
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler4.fmr-prod.quadient.cloud:9100\"}[5m])) * 100)",
     "legendFormat": "scaler4"
    }
   ]
  },
  {
   "title": "Disk Space Used Scaler 0 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler0.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler0.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Scaler 1 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler1.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler1.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Monitoring VM",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"monitoring.*\", instanceName=\"fmr-prod\", device!~'rootfs', mountpoint!=\"/mnt/hmstemp\"} * 100) / node_filesystem_size_bytes{instance=~\"monitoring.*\", instanceName=\"fmr-prod\", device!~'rootfs', mountpoint!=\"/mnt/hmstemp\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Scaler 3 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler3.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler3.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Interactive 2 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive2.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive2.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Scaler 2 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler2.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler2.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Scaler 4 VM",
   "type": "bargauge",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler4.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler4.fmr-prod.quadient.cloud:9100\", instanceName=\"fmr-prod\",device!~'rootfs'})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Application Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of requests over 3s",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 104 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and not(\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINT\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE2\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE3\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPREFLIGHT\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPREFLIGHTPHASE2\"\r\n    )\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n  // Filter data for the last 24 hours\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, clientResponseTime_d, serverResponseLatency_s\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count() by RequestType, RequestEndpoint\r\n| render table\r\n",
        "resource": "/subscriptions/ea549d66-7b11-4554-879a-55742d7f76a7/resourceGroups/hmsrg-fmr-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-fmr-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-fmr-hub-prod",
        "resourceName": "appgw-fmr-prod",
        "timeGrain": "auto"
       },
       "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
      }
     ]
    },
    {
     "title": "Number of requests over 10s",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 104 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 10\r\n    and not(\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINT\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE2\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE3\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPREFLIGHT\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPREFLIGHTPHASE2\"\r\n    )\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, clientResponseTime_d, serverResponseLatency_s\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count() by RequestType, RequestEndpoint\r\n| render table\r\n",
        "resource": "/subscriptions/ea549d66-7b11-4554-879a-55742d7f76a7/resourceGroups/hmsrg-fmr-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-fmr-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-fmr-hub-prod",
        "resourceName": "appgw-fmr-prod",
        "timeGrain": "auto"
       },
       "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "TotalRequests",
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-fmr-hub-prod",
        "resourceName": "appgw-fmr-prod",
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
      },
      {
       "azureMonitor": {
        "aggregation": "Total",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "FailedRequests",
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-fmr-hub-prod",
        "resourceName": "appgw-fmr-prod",
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
      }
     ]
    },
    {
     "title": "SUCCESSFUL - Average Request Time in (s)",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and httpStatus_d < 299\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project timeStamp_t, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, timeTaken_d, clientResponseTime_d, serverResponseLatency_s\r\n| summarize RequestCount = count(), AvgTimeTaken = avg(timeTaken_d) by RequestType, RequestStatus, RequestEndpoint\r\n| order by RequestType desc, RequestCount desc",
        "resource": "/subscriptions/ea549d66-7b11-4554-879a-55742d7f76a7/resourceGroups/hmsrg-fmr-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-fmr-prod",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-fmr-hub-prod",
        "resourceName": "appgw-fmr-prod",
        "timeGrain": "auto"
       },
       "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
      }
     ]
    },
    {
     "title": "FAILED - Average Request Time in (s)",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 122 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and httpStatus_d >=300\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project timeStamp_t, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, timeTaken_d, clientResponseTime_d, serverResponseLatency_s\r\n| summarize RequestCount = count(), AvgTimeTaken = avg(timeTaken_d) by RequestType, RequestStatus, RequestEndpoint\r\n| order by RequestType desc, RequestCount desc",
        "resource": "/subscriptions/ea549d66-7b11-4554-879a-55742d7f76a7/resourceGroups/hmsrg-fmr-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-fmr-prod",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-fmr-hub-prod",
        "resourceName": "appgw-fmr-prod",
        "timeGrain": "auto"
       },
       "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
      }
     ]
    },
    {
     "title": "Number of requests over 3s - Detail",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 132 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and not(\r\n        requestUri_s == \"/rest/api/submit-job/icmImport\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINT\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE2\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE3\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPREFLIGHT\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPREFLIGHTPHASE2\"\r\n    )\r\n    and timeTaken_d > 3 // Filter entries with timeTaken_d greater than 3 seconds\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, ClientIP = clientIP_s, RecievedBytes = receivedBytes_d, SendBytes = sentBytes_d, ClientResponseTime = clientResponseTime_d, ServerResponseLatency = serverResponseLatency_s\r\n\r\n",
        "resource": "/subscriptions/ea549d66-7b11-4554-879a-55742d7f76a7/resourceGroups/hmsrg-fmr-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-fmr-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-fmr-hub-prod",
        "resourceName": "appgw-fmr-prod",
        "timeGrain": "auto"
       },
       "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
      }
     ]
    },
    {
     "title": "Number of requests over 10s - Detail",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 143 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and not(\r\n        requestUri_s == \"/rest/api/submit-job/icmImport\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINT\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE2\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPRINTPHASE3\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPREFLIGHT\" or\r\n        requestUri_s == \"/rest/api/submit-job/COPPREFLIGHTPHASE2\"\r\n    )\r\n    and timeTaken_d > 10 // Filter entries with timeTaken_d greater than 3 seconds\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, ClientIP = clientIP_s, RecievedBytes = receivedBytes_d, SendBytes = sentBytes_d, ClientResponseTime = clientResponseTime_d, ServerResponseLatency = serverResponseLatency_s\r\n\r\n",
        "resource": "/subscriptions/ea549d66-7b11-4554-879a-55742d7f76a7/resourceGroups/hmsrg-fmr-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-fmr-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-fmr-hub-prod",
        "resourceName": "appgw-fmr-prod",
        "timeGrain": "auto"
       },
       "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
      }
     ]
    }
   ]
  },
  {
   "title": "Scalers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler Jobs per Workflow (Completed)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "increase(qms_scaler_workflow_job_counter{status=\"Completed\"}[5m])",
       "legendFormat": "{{wfId}}"
      }
     ]
    },
    {
     "title": "Completed jobs",
     "type": "timeseries",
     "description": "Indicates jobs that have been successfully processed.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(group) (increase(scaler_job_runs_total{instance=~\"scaler0.fmr-prod.quadient.cloud:30600|scaler1.fmr-prod.quadient.cloud:30600|scaler2.fmr-prod.quadient.cloud:30600|scaler3.fmr-prod.quadient.cloud:30600|scaler4.fmr-prod.quadient.cloud:30600\", status=\"completed\"}[5m]))",
       "legendFormat": "{{group}}"
      },
      {
       "expr": "increase(scaler_job_runs_total{instance=~\"scaler0.fmr-prod.quadient.cloud:30600|scaler1.fmr-prod.quadient.cloud:30600|scaler2.fmr-prod.quadient.cloud:30600|scaler3.fmr-prod.quadient.cloud:30600|scaler4.fmr-prod.quadient.cloud:30600\", status=\"completed\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    {
     "title": "Canceled jobs",
     "type": "timeseries",
     "description": "Indicates jobs that have been successfully processed.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{status=\"canceled\", instance=~\"scaler0.fmr-prod.quadient.cloud:30600|scaler1.fmr-prod.quadient.cloud:30600|scaler2.fmr-prod.quadient.cloud:30600|scaler3.fmr-prod.quadient.cloud:30600|scaler4.fmr-prod.quadient.cloud:30600\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    {
     "title": "Failed jobs",
     "type": "timeseries",
     "description": "Indicates jobs that failed to process.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{instance=~\"scaler0.fmr-prod.quadient.cloud:30600|scaler1.fmr-prod.quadient.cloud:30600|scaler2.fmr-prod.quadient.cloud:30600|scaler3.fmr-prod.quadient.cloud:30600|scaler4.fmr-prod.quadient.cloud:30600\", status=\"failed\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    {
     "title": "Average IPS Queue Waiting Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(group) (increase(scaler_processing_jobs_total{instance=~\"scaler0.fmr-prod.quadient.cloud:30600|scaler1.fmr-prod.quadient.cloud:30600|scaler2.fmr-prod.quadient.cloud:30600|scaler3.fmr-prod.quadient.cloud:30600|scaler4.fmr-prod.quadient.cloud:30600\"}[5m]))",
       "legendFormat": "{{group}}"
      },
      {
       "expr": "increase(scaler_processing_jobs_total{instance=~\"scaler0.fmr-prod.quadient.cloud:30600|scaler1.fmr-prod.quadient.cloud:30600|scaler2.fmr-prod.quadient.cloud:30600|scaler3.fmr-prod.quadient.cloud:30600|scaler4.fmr-prod.quadient.cloud:30600\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    {
     "title": "Scaler workflows",
     "type": "timeseries",
     "description": "Provides the number of deployed workflows for each workflow type, and for each of the following statuse",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "scaler_deployed_workflows_total{instance=~\"scaler0.fmr-prod.quadient.cloud:30600|scaler1.fmr-prod.quadient.cloud:30600|scaler2.fmr-prod.quadient.cloud:30600|scaler3.fmr-prod.quadient.cloud:30600|scaler4.fmr-prod.quadient.cloud:30600\"}",
       "legendFormat": "{{instance}}/{{ group }}: {{ status }}"
      }
     ]
    },
    {
     "title": "Processing jobs",
     "type": "timeseries",
     "description": "Provides the number of all the jobs that are currently being processed.\nUse this metric to create custom alerts about the number of currently processed jobs that is rapidly growing. That could indicate issues, for example, with jobs being stuck in a loop in the Script workflow module.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(group) (increase(scaler_processing_jobs_total{instance=~\"scaler0.fmr-prod.quadient.cloud:30600|scaler1.fmr-prod.quadient.cloud:30600|scaler2.fmr-prod.quadient.cloud:30600|scaler3.fmr-prod.quadient.cloud:30600|scaler4.fmr-prod.quadient.cloud:30600\"}[5m]))",
       "legendFormat": "{{group}}"
      },
      {
       "expr": "label_replace(increase(scaler_processing_jobs_total{instance=~\"scaler.*fmr-prod.*\"}[5m]), \"virtualMachine\", \"$1\", \"instance\", \"(.*)\\\\.fmr.*\")",
       "legendFormat": "{{virtualMachine}}/{{group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of tickets",
     "type": "timeseries",
     "description": "Number of tickets created since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 196 },
     "targets": [
      {
       "expr": "II_CreatedTicketsCount_total{instance=~\"interactive0.fmr-prod.quadient.cloud:30701|interactive1.fmr-prod.quadient.cloud:30701|interactive2.fmr-prod.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IPS call errors",
     "type": "timeseries",
     "description": "Number of IPS calls made ending in errors since Interactive startup.\nNumber of IPS calls ending in a timeout made since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 196 },
     "targets": [
      {
       "expr": "rate(II_IPSCallExceptionCount_total{instance=~\"interactive0.fmr-prod.quadient.cloud:30701|interactive1.fmr-prod.quadient.cloud:30701|interactive2.fmr-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "IPS Call Expections/{{instance}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "Number of currently active and idle Interactive connections to the database.\nNumber of currently active and idle Interactive connections to Inspire Content Manager (ICM).\n\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 196 },
     "targets": [
      {
       "expr": "II_DBConnections{instance=~\"interactive0.fmr-prod.quadient.cloud:30701|interactive1.fmr-prod.quadient.cloud:30701|interactive2.fmr-prod.quadient.cloud:30701\"}",
       "legendFormat": "DB {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_ICMConnections{instance=~\"interactive0.fmr-prod.quadient.cloud:30701|interactive1.fmr-prod.quadient.cloud:30701|interactive2.fmr-prod.quadient.cloud:30701\"}",
       "legendFormat": "ICM {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_IPSConnections{instance=~\"interactive0.fmr-prod.quadient.cloud:30701|interactive1.fmr-prod.quadient.cloud:30701|interactive2.fmr-prod.quadient.cloud:30701\"}",
       "legendFormat": "IPS {{instance}}/{{Connection}}"
      }
     ]
    },
    {
     "title": "Number of users",
     "type": "timeseries",
     "description": "Number of currently logged in users (active session only).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 204 },
     "targets": [
      {
       "expr": "II_DBSessions{instance=~\"interactive0.fmr-prod.quadient.cloud:30701|interactive1.fmr-prod.quadient.cloud:30701|interactive2.fmr-prod.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Drafts and Tickets",
     "type": "timeseries",
     "description": "Number of currently active drafts and tickets, and drafts and tickets that are marked for deletion. Numbers are grouped by: active drafts, drafts marked for deletion, active tickets, tickets marked for deletion.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 204 },
     "targets": [
      {
       "expr": "II_DBData{instance=~\"interactive0.fmr-prod.quadient.cloud:30701|interactive1.fmr-prod.quadient.cloud:30701|interactive2.fmr-prod.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}/{{ObjectType}}/{{State}}"
      }
     ]
    },
    {
     "title": "Interactive requests & errors",
     "type": "timeseries",
     "description": "Number of user synchronization errors since Interactive startup.\nNumber of REST/SOAP requests received since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 204 },
     "targets": [
      {
       "expr": "increase(II_InteractiveError{instance=~\"interactive0.fmr-prod.quadient.cloud:30701|interactive1.fmr-prod.quadient.cloud:30701|interactive2.fmr-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Errors/{{instance}}/{{Type}}"
      },
      {
       "expr": "increase(II_InteractiveRequest_count{instance=~\"interactive0.fmr-prod.quadient.cloud:30701|interactive1.fmr-prod.quadient.cloud:30701|interactive2.fmr-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Requests/{{instance}}"
      },
      {
       "expr": "increase(II_InteractiveRequestExceptionCount{instance=~\"interactive0.fmr-prod.quadient.cloud:30701|interactive1.fmr-prod.quadient.cloud:30701|interactive2.fmr-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Errors/{{instance}}/Requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Scaler JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler heap used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{area=\"heap\",instance=\"scaler0.fmr-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Fidelity\",area=\"heap\",instance=\"scaler0.fmr-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 0"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Fidelity\",area=\"heap\",instance=\"scaler1.fmr-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Fidelity\",area=\"heap\",instance=\"scaler1.fmr-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 1"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Fidelity\",area=\"heap\",instance=\"scaler2.fmr-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Fidelity\",area=\"heap\",instance=\"scaler2.fmr-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 2"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Fidelity\",area=\"heap\",instance=\"scaler3.fmr-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Fidelity\",area=\"heap\",instance=\"scaler3.fmr-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 3"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Fidelity\",area=\"heap\",instance=\"scaler4.fmr-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Fidelity\",area=\"heap\",instance=\"scaler4.fmr-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 4"
      }
     ]
    },
    {
     "title": "Scaler start time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{customerName=\"Fidelity\",job=\"fmr-prod-scaler-vm\"}*1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Heap Scaler",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler0.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler0.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler1.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler1.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler1.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler2.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler2.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler2.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler3.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler3.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "comitted"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler3.fmr-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Scaler thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler0.fmr-prod.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler1.fmr-prod.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler2.fmr-prod.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler3.fmr-prod.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler4.fmr-prod.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactive JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactive heap used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Fidelity\",area=\"heap\",instance=\"interactive0.fmr-prod.quadient.cloud:30701\"})*100/sum(jvm_memory_bytes_max{customerName=\"Fidelity\",area=\"heap\",instance=\"interactive0.fmr-prod.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 0"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Fidelity\",area=\"heap\",instance=\"interactive1.fmr-prod.quadient.cloud:30701\",instanceName=\"fmr-prod\"})*100/sum(jvm_memory_bytes_max{customerName=\"Fidelity\",area=\"heap\",instance=\"interactive1.fmr-prod.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 1"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Fidelity\",area=\"heap\",instance=\"interactive2.fmr-prod.quadient.cloud:30701\",instanceName=\"fmr-prod\"})*100/sum(jvm_memory_bytes_max{customerName=\"Fidelity\",area=\"heap\",instance=\"interactive2.fmr-prod.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 2"
      }
     ]
    },
    {
     "title": "Interactive start time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{customerName=\"Fidelity\",job=\"fmr-prod-interactive-vm\"}*1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 0",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive0.fmr-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive0.fmr-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive0.fmr-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 1",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive1.fmr-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive1.fmr-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive1.fmr-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 2",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive2.fmr-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive2.fmr-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive2.fmr-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Interactive 0 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive0.fmr-prod.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Interactive 1 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive1.fmr-prod.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Interactive 2 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive2.fmr-prod.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "{job=\"scalerlogs\"}"
      }
     ]
    },
    {
     "title": "Scaler ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "{instance=~\"scaler2.fmr-prod.quadient.cloud|scaler1.fmr-prod.quadient.cloud|scaler0.fmr-prod.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Scaler IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "targets": [
      {
       "expr": "{instance=~\"scaler.*fmr-prod.quadient.cloud\", job=\"ipslogs\"}"
      }
     ]
    },
    {
     "title": "Interactive Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "{job=\"interactivelogs\"}"
      }
     ]
    },
    {
     "title": "Interactive ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.fmr-prod.quadient.cloud|interactive1.fmr-prod.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Interactive  IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.fmr-prod.quadient.cloud|interactive1.fmr-prod.quadient.cloud\", job=\"ipslogs\"}"
      }
     ]
    }
   ]
  }
 ]
}