{
 "title": "Generali-UK-UAT",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server's Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Automation traffic lights properly. \n",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*vm\", instanceName=\"generaliuk-uat\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat",
   "type": "stat",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"generaliuk-uat\", environment=\"pre2\"}",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"generaliuk-uat\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"generaliuk-uat\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 22, "w": 7, "x": 17, "y": 1 } },
  {
   "title": "Server's Percentage Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"generaliuk-uat\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"generaliuk-uat\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RHEL security updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "hms_dnf{instanceName=\"generaliuk-uat\",type=~\"Critical|Important|Moderate\"}",
     "legendFormat": "{{job}}:{{type}}"
    }
   ]
  },
  { "title": "Shared Panels", "type": "dashlist", "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 } },
  {
   "title": "Audit Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_audit_status{instanceName=\"generaliuk-uat\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive0.generaliuk-uat.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "interactive0"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"automation0.generaliuk-uat.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "automation0"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"monitoring.generaliuk-uat.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "monitoring"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"^(.*?)generaliuk-uat.quadient.cloud:9100\"}[5m])",
       "legendFormat": "{{instance}} recv {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"^(.*?)generaliuk-uat.quadient.cloud:9100\"}[5m])",
       "legendFormat": "{{instance}} trans {{device}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"generaliuk-uat\",instance=\"interactive0.generaliuk-uat.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"generaliuk-uat\",instance=\"interactive0.generaliuk-uat.quadient.cloud:9100\"})*100",
       "legendFormat": "interactive0"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"generaliuk-uat\",instance=\"automation0.generaliuk-uat.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"generaliuk-uat\",instance=\"automation0.generaliuk-uat.quadient.cloud:9100\"})*100",
       "legendFormat": "automation0"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"generaliuk-uat\",instance=\"monitoring.generaliuk-uat.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"generaliuk-uat\",instance=\"monitoring.generaliuk-uat.quadient.cloud:9100\"})*100",
       "legendFormat": "monitoring"
      }
     ]
    },
    {
     "title": "Disk Space Used Monitoring VM",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 86 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"monitoring.*\", instanceName=\"generaliuk-uat\", device!~'rootfs', mountpoint!=\"/mnt/hmstemp\"} * 100) / node_filesystem_size_bytes{instance=~\"monitoring.*\", instanceName=\"generaliuk-uat\", device!~'rootfs', mountpoint!=\"/mnt/hmstemp\"})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Interactive 0 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 86 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive0.generaliuk-uat.quadient.cloud:9100\", instanceName=\"generaliuk-uat\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive0.generaliuk-uat.quadient.cloud:9100\", instanceName=\"generaliuk-uat\",device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Automation 0 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 86 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"automation0.generaliuk-uat.quadient.cloud:9100\", instanceName=\"generaliuk-uat\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"automation0.generaliuk-uat.quadient.cloud:9100\", instanceName=\"generaliuk-uat\",device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily VM/Disk Azure backup",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n    and not(\r\n        BackupItemFriendlyName1 contains \"test\" or\r\n        BackupItemFriendlyName1 contains \"qa\"\r\n    )\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resources": [
         "/subscriptions/f5b39a1e-2ffb-4548-94bb-3872e4d8da57/resourceGroups/hmsrg-generaliuk-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-generaliuk-nonprod"
        ],
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Azure VM/Disks backup health",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(7d)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resources": [
         "/subscriptions/de74e022-0016-4972-ac5a-d17f177ed92d/resourceGroups/hmsrg-gfbank-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-gfbank-nonprod"
        ],
        "resultFormat": "table"
       },
       "azureMonitor": {
        "aggregation": "Count",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [
         {
          "dimension": "healthStatus",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "backupInstanceName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "BackupHealthEvent",
        "metricNamespace": "microsoft.recoveryservices/vaults",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "Microsoft.RecoveryServices/vaults",
          "region": "westeurope",
          "resourceGroup": "hmsrg-generaliuk-hub-nonprod",
          "resourceName": "rsv-generaliuk-nonprod",
          "subscription": "f5b39a1e-2ffb-4548-94bb-3872e4d8da57"
         }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "azureResourceGraph": { "query": "" },
       "subscription": "f5b39a1e-2ffb-4548-94bb-3872e4d8da57",
       "subscriptions": [
        "61bc806e-8e88-434b-907c-ab77d1ec9ff0"
       ]
      }
     ]
    }
   ]
  },
  { "title": "Automation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Submodules Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "increase(qms_automation_submodule_error{environment=\"pre2\", instanceName=\"generaliuk-uat\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Metrics Last Update (seconds)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - qms_automation_metrics_lastUpdate{environment=\"pre2\",customerName=\"GENERALIUK\",exported_instance=\"automation0.generaliuk-uat.quadient.cloud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "increase(qms_automation_job_status_counter{exported_instance=\"automation0.generaliuk-uat.quadient.cloud\",status=\"error\"}[5m])",
     "legendFormat": "Error Jobs"
    },
    {
     "expr": "increase(qms_automation_job_status_counter{exported_instance=\"automation0.generaliuk-uat.quadient.cloud\",status=\"ok\"}[5m])",
     "legendFormat": "Success Jobs"
    }
   ]
  },
  {
   "title": "Server's Percentage Availability",
   "type": "timeseries",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "up{job=~\".*vm\", instanceName=\"generaliuk-uat\",instance=\"automation0.generaliuk-uat.quadient.cloud:9100\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Automation heartbeat percentage",
   "type": "timeseries",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "network_check{name=\"automation0.generaliuk-uat.quadient.cloud\"}",
     "legendFormat": "Network"
    }
   ]
  },
  {
   "title": "Automation start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{customerName=\"GENERALIUK\",job=\"generaliuk-uat-automation-vm\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Interactives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of tickets",
     "type": "timeseries",
     "description": "Number of tickets created since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "II_CreatedTicketsCount_total{instance=~\"interactive0.generaliuk-uat.quadient.cloud:30701|interactive1.generaliuk-uat.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IPS call errors",
     "type": "timeseries",
     "description": "Number of IPS calls made ending in errors since Interactive startup.\nNumber of IPS calls ending in a timeout made since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "targets": [
      {
       "expr": "rate(II_IPSCallExceptionCount_total{instance=~\"interactive0.generaliuk-uat.quadient.cloud:30701|interactive1.generaliuk-uat.quadient.cloud:30701\"}[5m])",
       "legendFormat": "IPS Call Expections/{{instance}}"
      }
     ]
    },
    {
     "title": "Interactive requests & errors",
     "type": "timeseries",
     "description": "Number of user synchronization errors since Interactive startup.\nNumber of REST/SOAP requests received since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "targets": [
      {
       "expr": "increase(II_InteractiveError{instance=~\"interactive0.generaliuk-uat.quadient.cloud:30701|interactive1.generaliuk-uat.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Errors/{{instance}}/{{Type}}"
      },
      {
       "expr": "increase(II_InteractiveRequest_count{instance=~\"interactive0.generaliuk-uat.quadient.cloud:30701|interactive1.generaliuk-uat.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Requests/{{instance}}"
      },
      {
       "expr": "increase(II_InteractiveRequestExceptionCount{instance=~\"interactive0.generaliuk-uat.quadient.cloud:30701|interactive1.generaliuk-uat.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Errors/{{instance}}/Requests"
      }
     ]
    },
    {
     "title": "Number of users",
     "type": "timeseries",
     "description": "Number of currently logged in users (active session only).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "II_DBSessions{instance=~\"interactive0.generaliuk-uat.quadient.cloud:30701|interactive1.generaliuk-uat.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Drafts and Tickets",
     "type": "timeseries",
     "description": "Number of currently active drafts and tickets, and drafts and tickets that are marked for deletion. Numbers are grouped by: active drafts, drafts marked for deletion, active tickets, tickets marked for deletion.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
     "targets": [
      {
       "expr": "II_DBData{instance=~\"interactive0.generaliuk-uat.quadient.cloud:30701|interactive1.generaliuk-uat.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}/{{ObjectType}}/{{State}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "Number of currently active and idle Interactive connections to the database.\nNumber of currently active and idle Interactive connections to Inspire Content Manager (ICM).\n\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
     "targets": [
      {
       "expr": "II_DBConnections{instance=~\"interactive0.generaliuk-uat.quadient.cloud:30701|interactive1.generaliuk-uat.quadient.cloud:30701\"}",
       "legendFormat": "DB {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_ICMConnections{instance=~\"interactive0.generaliuk-uat.quadient.cloud:30701|interactive1.generaliuk-uat.quadient.cloud:30701\"}",
       "legendFormat": "ICM {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_IPSConnections{instance=~\"interactive0.generaliuk-uat.quadient.cloud:30701|interactive1.generaliuk-uat.quadient.cloud:30701\"}",
       "legendFormat": "IPS {{instance}}/{{Connection}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactive JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactive heap used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"GENERALIUK\",area=\"heap\",instance=\"interactive0.generaliuk-uat.quadient.cloud:30701\"})*100/sum(jvm_memory_bytes_max{customerName=\"GENERALIUK\",area=\"heap\",instance=\"interactive0.generaliuk-uat.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 0"
      }
     ]
    },
    {
     "title": "Interactive start time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{customerName=\"GENERALIUK\",job=\"generaliuk-uat-interactive-vm\"}*1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 0",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive0.generaliuk-uat.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive0.generaliuk-uat.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive0.generaliuk-uat.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Interactive 0 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive0.generaliuk-uat.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Automation Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "{job=\"automationlogs\"}"
      }
     ]
    },
    {
     "title": "Automation ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "{instance=~\"automation0.generaliuk-uat.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Automation IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "{instance=~\"automation0.generaliuk-uat.quadient.cloud\", job=\"ipslogs\"}"
      }
     ]
    },
    {
     "title": "Audit Logs",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "{job=\"auditlogs\"}"
      }
     ]
    },
    {
     "title": "Interactive Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "{job=\"interactivelogs\"}"
      }
     ]
    },
    {
     "title": "Interactive ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.generaliuk-uat.quadient.cloud|interactive1.generaliuk-uat.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Interactive  IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.generaliuk-uat.quadient.cloud|interactive1.generaliuk-uat.quadient.cloud\", job=\"ipslogs\"}"
      }
     ]
    }
   ]
  }
 ]
}