{
 "title": "Homeserve PROD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server's Availability",
   "type": "bargauge",
   "description": "NOTE: The monitoring server needs to be ON to show Automation traffic lights properly. \n",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*vm\", instanceName=\"homeserve-prod\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Automation heartbeat",
   "type": "bargauge",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_check{name=\"automation.homeserve-prod.quadient.cloud\"}",
     "legendFormat": "Network"
    },
    {
     "expr": "health_check{name=\"automation.homeserve-prod.quadient.cloud\"}",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Inspire heartbeat",
   "type": "bargauge",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 3, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=\"automation.homeserve-prod.quadient.cloud:9100\", job=\"homeserve-prod-automation-vm\", name=\"InspireAutomation-10140.service\", state=\"active\"}",
     "legendFormat": "Automation"
    },
    {
     "expr": "node_systemd_unit_state{instance=\"automation.homeserve-prod.quadient.cloud:9100\", job=\"homeserve-prod-automation-vm\", name=\"InspireContentManager-30353.service\", state=\"active\"}",
     "legendFormat": "ICM"
    },
    {
     "expr": "node_systemd_unit_state{instance=\"automation.homeserve-prod.quadient.cloud:9100\", job=\"homeserve-prod-automation-vm\", name=\"InspireProductionServer-30354.service\", state=\"active\"}",
     "legendFormat": "IPS"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 17, "w": 6, "x": 18, "y": 1 } },
  {
   "title": "Server's Percentage Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"homeserve-prod\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"homeserve-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Automation heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(network_check{name=\"automation.homeserve-prod.quadient.cloud\"}[$__range]) * 100",
     "legendFormat": "Network"
    },
    {
     "expr": "avg_over_time(health_check{name=\"automation.homeserve-prod.quadient.cloud\"}[$__range]) * 100",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Inspire heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"homeserve-prod\", job=\"homeserve-prod-automation-vm\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"homeserve-prod\", job=\"homeserve-prod-automation-vm\"}[$__range])))[$__range:1m]) * 100, \"grafanalabel\", \"$1\", \"name\", \"Inspire(.+)-.*.service\")",
     "legendFormat": "{{grafanalabel}}"
    }
   ]
  },
  {
   "title": "Automation modules",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "subsystem_eventsys{exported_instance=\"homeserve_prod\"}",
     "legendFormat": "Events"
    },
    {
     "expr": "subsystem_http_1{exported_instance=\"homeserve_prod\"}",
     "legendFormat": "HTTP service"
    },
    {
     "expr": "subsystem_tpool{exported_instance=\"homeserve_prod\"}",
     "legendFormat": "Production services"
    },
    {
     "expr": "subsystem_scheduler{exported_instance=\"homeserve_prod\"}",
     "legendFormat": "Scheduler"
    }
   ]
  },
  {
   "title": "Response times",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "server_IPS_response_time{instanceName=\"homeserve-prod\"}",
     "legendFormat": "IPS"
    },
    {
     "expr": "server_LB_response_time{instanceName=\"homeserve-prod\"}",
     "legendFormat": "LB"
    }
   ]
  },
  {
   "title": "RHEL security updates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "hms_dnf{instanceName=\"homeserve-prod\",type=~\"Critical|Important|Moderate\"}",
     "legendFormat": "{{job}}:{{type}}"
    }
   ]
  },
  { "title": "Shared Panels", "type": "dashlist", "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 } },
  {
   "title": "Audit Logs",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Automation traffic lights properly. \n",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_audit_status{instanceName=\"homeserve-prod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Weekly (4 Sundays)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_backup_info_weekly_all{instanceName=\"homeserve-dev\",backupType=\"weekly\"})"
    }
   ]
  },
  {
   "title": "All Daily (Monday - Saturday)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_backup_info_daily_all{instanceName=\"homeserve-dev\",backupType=\"daily\"})"
    }
   ]
  },
  { "title": "Backups Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Daily VM/Disk Azure backup",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
      "resources": [
       "/subscriptions/eef97cf8-d121-4657-9555-2e386bdf95b6/resourceGroups/hmsrg-homeserve-prod/providers/Microsoft.RecoveryServices/vaults/rsv-homeserve-prod"
      ]
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Azure VM/Disks backup health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "healthStatus",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "backupInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "BackupHealthEvent",
      "metricNamespace": "microsoft.recoveryservices/vaults",
      "region": "uksouth",
      "resources": [
       {
        "metricNamespace": "microsoft.recoveryservices/vaults",
        "region": "uksouth",
        "resourceGroup": "hmsrg-homeserve-prod",
        "resourceName": "rsv-homeserve-prod",
        "subscription": "eef97cf8-d121-4657-9555-2e386bdf95b6"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "eef97cf8-d121-4657-9555-2e386bdf95b6"
    }
   ]
  },
  {
   "title": "Daily (Monday - Saturday)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hms_backup_info_daily_all{instanceName=\"homeserve-prod\",backupType=\"daily\",containerName=\"hms-backup-fs\"}",
     "legendFormat": "{{backupItem}}-fileshare"
    }
   ]
  },
  {
   "title": "Daily (Monday - Saturday)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hms_backup_info_daily_all{instanceName=\"homeserve-prod\", backupType=\"daily\", containerName=\"hms-backup-db\", backupItem=~\"automation-db|custom-db|icm-db\"}",
     "legendFormat": "{{backupItem}}-database"
    }
   ]
  },
  {
   "title": "Weekly (4 Sundays)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hms_backup_info_weekly_all{instanceName=\"homeserve-prod\",backupType=\"weekly\",containerName=\"hms-backup-fs\"}",
     "legendFormat": "{{backupItem}}-fileshare"
    }
   ]
  },
  {
   "title": "Weekly (4 Sundays)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hms_backup_info_weekly_all{instanceName=\"homeserve-prod\", backupType=\"weekly\", containerName=\"hms-backup-db\", backupItem=~\"automation-db|custom-db|icm-db\"}",
     "legendFormat": "{{backupItem}}-database"
    }
   ]
  },
  {
   "title": "Automation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(jobs_finished_unsuccessfully_total{exported_instance=\"homeserve_prod\", exported_job=\"automation-metric\"}[5m])",
       "legendFormat": "Newly failed jobs"
      },
      {
       "expr": "increase(jobs_finished_successfully_total{exported_instance=\"homeserve_prod\", exported_job=\"automation-metric\"}[5m])",
       "legendFormat": "Newly finished jobs"
      }
     ]
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{instanceName=\"homeserve-prod\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "expr": "node_load1 / count without (cpu) (count without (mode) (node_cpu_seconds_total{instanceName=\"homeserve-prod\"}))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{instanceName=\"homeserve-prod\"} / node_memory_MemTotal_bytes{instanceName=\"homeserve-prod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin{instanceName=\"homeserve-prod\"}[5m]) + rate(node_vmstat_pgpgout{instanceName=\"homeserve-prod\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Used Automation",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (max by (device) (node_filesystem_avail_bytes{instance=~\"automation.*\", instanceName=\"homeserve-prod\"}) / max by (device) (node_filesystem_size_bytes{instance=~\"automation.*\", instanceName=\"homeserve-prod\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Used Monitoring",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (max by (device) (node_filesystem_avail_bytes{instance=~\"monitoring.*\", instanceName=\"homeserve-prod\",fstype!=\"cifs\"}) / max by (device) (node_filesystem_size_bytes{instance=~\"monitoring.*\", instanceName=\"homeserve-prod\",fstype!=\"cifs\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instanceName=\"homeserve-prod\", device!=\"lo\"}[5m])",
     "legendFormat": "{{job}}: {{device}}_receive"
    },
    {
     "expr": "- rate(node_network_transmit_bytes_total{instanceName=\"homeserve-prod\", device!=\"lo\"}[5m])",
     "legendFormat": "{{job}}: {{device}}_transmit"
    }
   ]
  },
  {
   "title": "Automation JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Automation Start time",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"homeserve-prod-automation-automation\"}*1000"
      }
     ]
    },
    {
     "title": "JVM Heap Automation",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 4, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{job=\"homeserve-prod-automation-automation\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{job=\"homeserve-prod-automation-automation\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{job=\"homeserve-prod-automation-automation\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Automation Thread states",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_state{job=\"homeserve-prod-automation-automation\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Automation Heap used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{job=\"homeserve-prod-automation-automation\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{job=\"homeserve-prod-automation-automation\", area=\"heap\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Automation Log",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "{instance=\"automation.homeserve-prod.quadient.cloud\",job=\"automationlogs\"}",
       "legendFormat": "Automation Log"
      }
     ]
    },
    {
     "title": "ICM log",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "{instance=\"automation.homeserve-prod.quadient.cloud\",job=\"icmlogs\"} != \";O;SEND\" != \";I;0\" != \";I;1\" != \";O;OK\" != \";I;begin command\" != \";I;end command\" != \";I;VCS_SERVER_DATETIME\"",
       "legendFormat": "ICM log"
      }
     ]
    },
    {
     "title": "IPS Log",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "targets": [
      {
       "expr": "{instance=\"automation.homeserve-prod.quadient.cloud\",job=\"ipslogs\"} != \"ping\" != \"diag\" != \"version\" != \";ok;\" != \";qallt\"",
       "legendFormat": "IPS log"
      }
     ]
    }
   ]
  }
 ]
}