{
 "title": "Prudential-PROD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server's Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Automation traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*vm\", instanceName=\"prudential-prod\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat",
   "type": "stat",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"prudential-prod\", environment=\"prod1\"}",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"prudential-prod\", instance!~\"monitoring.*\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"prudential-prod\", instance!~\"monitoring.*\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 22, "w": 7, "x": 17, "y": 1 } },
  {
   "title": "Server's Percentage Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"prudential-prod\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"prudential-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RHEL security updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "hms_dnf{instanceName=\"prudential-prod\",type=~\"Critical|Important|Moderate\"}",
     "legendFormat": "{{job}}:{{type}}"
    }
   ]
  },
  { "title": "Shared Panels", "type": "dashlist", "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 } },
  {
   "title": "Scaler File Share Sync Failure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_status_failed{job_name=~\"cron-job-azsync-prudential-prod-scaler-.+\"} >=1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Audit Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_audit_status{instanceName=\"prudential-prod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scaler Job Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Scaler jobs over 3s percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "( sum(increase(hms_scaler_jobDuration_3s_total{ workflow=\"ComposeDocument\", instanceName=\"prudential-prod\", environment=\"prod1\"}[$__range])) * 100) / sum(increase(scaler_job_runs_total{instanceName=\"prudential-prod\", environment=\"prod1\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaler jobs over 3s percentage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hms_scaler_jobDuration_3s_total{ workflow=\"ComposeDocument\", instanceName=\"prudential-prod\", environment=\"prod1\"}[$__range]))",
     "legendFormat": "Jobs over 3 seconds"
    },
    {
     "expr": "sum(increase(scaler_job_runs_total{instanceName=\"prudential-prod\", environment=\"prod1\"}[$__range]))",
     "legendFormat": "Jobs total"
    }
   ]
  },
  {
   "title": "Scaler jobs over 5s percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "( sum(increase(hms_scaler_jobDuration_5s_total{ workflow=\"ComposeDocument\", instanceName=\"prudential-prod\", environment=\"prod1\"}[$__range])) * 100) / sum(increase(scaler_job_runs_total{instanceName=\"prudential-prod\", environment=\"prod1\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scaler jobs over 5s percentage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hms_scaler_jobDuration_5s_total{ workflow=\"ComposeDocument\", instanceName=\"prudential-prod\", environment=\"prod1\"}[$__range]))",
     "legendFormat": "Jobs over 5 seconds"
    },
    {
     "expr": "sum(increase(scaler_job_runs_total{instanceName=\"prudential-prod\", environment=\"prod1\"}[$__range]))",
     "legendFormat": "Jobs total"
    }
   ]
  },
  {
   "title": "Scaler jobs over 3 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "increase(hms_scaler_jobDuration_3s_total{ workflow=\"ComposeDocument\", instanceName=\"prudential-prod\", environment=\"prod1\"}[$__interval])",
     "legendFormat": "3s/{{workflow}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Scaler jobs over 5 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "increase(hms_scaler_jobDuration_5s_total{ workflow=\"ComposeDocument\", instanceName=\"prudential-prod\", environment=\"prod1\"}[$__interval])",
     "legendFormat": "5s/{{workflow}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Appgw number of requests over 3s",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and not(\r\n        requestUri_s == \"/rest/api/submit-job/TEST\"\r\n    )\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, clientResponseTime_d, serverResponseLatency_s\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count() by RequestType, RequestEndpoint\r\n| render table\r\n",
      "resources": [
       "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-prudential-prod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-fmr-hub-prod", "resourceName": "appgw-fmr-prod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
    }
   ]
  },
  {
   "title": "Appgw number of requests over 5s",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 5\r\n    and not(\r\n        requestUri_s == \"/rest/api/submit-job/TEST\"\r\n    )\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, clientResponseTime_d, serverResponseLatency_s\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count() by RequestType, RequestEndpoint\r\n| render table\r\n",
      "resources": [
       "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-prudential-prod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-fmr-hub-prod", "resourceName": "appgw-fmr-prod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
    }
   ]
  },
  {
   "title": "Appgw number of requests over 3s - Detail",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and not(\r\n        requestUri_s == \"/rest/api/submit-job/TEST\"\r\n    )\r\n    and timeTaken_d > 3 // Filter entries with timeTaken_d greater than 3 seconds\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, ClientIP = clientIP_s, RecievedBytes = receivedBytes_d, SendBytes = sentBytes_d, ClientResponseTime = clientResponseTime_d, ServerResponseLatency = serverResponseLatency_s\r\n\r\n",
      "resources": [
       "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-prudential-prod"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-fmr-hub-prod", "resourceName": "appgw-fmr-prod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.network/applicationgateways",
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "eastus",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "eastus",
        "resourceGroup": "hmsrg-prudential-hub-prod",
        "resourceName": "appgw-prudential-prod",
        "subscription": "b3a1bc7c-4424-45f5-8d8d-98db685519b4"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "b3a1bc7c-4424-45f5-8d8d-98db685519b4"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FailedRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "eastus",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "eastus",
        "resourceGroup": "hmsrg-prudential-hub-nonprod",
        "resourceName": "appgw-prudential-nonprod",
        "subscription": "b3a1bc7c-4424-45f5-8d8d-98db685519b4"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "b3a1bc7c-4424-45f5-8d8d-98db685519b4"
    }
   ]
  },
  {
   "title": "SUCCESSFUL - Overall average request time in (s)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and httpStatus_d < 299\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project timeStamp_t, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, timeTaken_d, clientResponseTime_d, serverResponseLatency_s\r\n| summarize RequestCount = count(), AvgTimeTaken = avg(timeTaken_d) by RequestType, RequestStatus, RequestEndpoint\r\n| order by RequestType desc, RequestCount desc",
      "resources": [
       "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-prudential-prod"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-fmr-hub-prod", "resourceName": "appgw-fmr-prod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
    }
   ]
  },
  {
   "title": "FAILED - Overall average request time in (s)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and httpStatus_d >=300\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project timeStamp_t, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, timeTaken_d, clientResponseTime_d, serverResponseLatency_s\r\n| summarize RequestCount = count(), AvgTimeTaken = avg(timeTaken_d) by RequestType, RequestStatus, RequestEndpoint\r\n| order by RequestType desc, RequestCount desc",
      "resources": [
       "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-prudential-prod"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       { "resourceGroup": "hmsrg-fmr-hub-prod", "resourceName": "appgw-fmr-prod" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "ea549d66-7b11-4554-879a-55742d7f76a7"
    }
   ]
  },
  {
   "title": "Backups Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily VM/Disk Azure backup",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 133 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resource": "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-prod/providers/Microsoft.RecoveryServices/vaults/rsv-prudential-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Azure VM/Disks backup health",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 133 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(7d)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resource": "/subscriptions/de74e022-0016-4972-ac5a-d17f177ed92d/resourceGroups/hmsrg-gfbank-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-gfbank-nonprod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [
         {
          "dimension": "healthStatus",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "backupInstanceName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "BackupHealthEvent",
        "metricNamespace": "microsoft.recoveryservices/vaults",
        "resourceGroup": "hmsrg-prudential-hub-prod",
        "resourceName": "rsv-prudential-prod",
        "timeGrain": "auto"
       },
       "subscription": "b3a1bc7c-4424-45f5-8d8d-98db685519b4"
      }
     ]
    },
    {
     "title": "DB - Daily (Monday - Saturday)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 142 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info_daily_all{containerName=~\".*db$\",instanceName=\"prudential-prod\"}",
       "legendFormat": "{{backupItem}}-database"
      }
     ]
    },
    {
     "title": "DB - Weekly (4 Sundays)",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 4, "y": 142 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hms_backup_info_weekly_all{containerName=~\".*db$\",instanceName=\"prudential-prod\"}",
       "legendFormat": "{{backupItem}}-database"
      }
     ]
    },
    {
     "title": "All Daily (Monday - Saturday)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 142 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hms_backup_info_daily_all{instanceName=\"prudential-prod\",backupType=\"daily\"})"
      }
     ]
    },
    {
     "title": "All Weekly (4 Sundays)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 147 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hms_backup_info_weekly_all{instanceName=\"prudential-prod\",backupType=\"weekly\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive0.prudential-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "interactive0"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive1.prudential-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "interactive1"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"interactive2.prudential-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "interactive2"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler0.prudential-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler0"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler1.prudential-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler1"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler2.prudential-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler2"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler3.prudential-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler3"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler4.prudential-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler4"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"monitoring.prudential-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "monitoring"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"^(.*?)prudential-prod.quadient.cloud:9100\"}[5m])",
       "legendFormat": "{{instance}} recv {{prodice}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"^(.*?)prudential-prod.quadient.cloud:9100\"}[5m])",
       "legendFormat": "{{instance}} trans {{prodice}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"prudential-prod\",instance=\"interactive0.prudential-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"prudential-prod\",instance=\"interactive0.prudential-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "interactive0"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"prudential-prod\",instance=\"interactive1.prudential-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"prudential-prod\",instance=\"interactive1.prudential-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "interactive1"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"prudential-prod\",instance=\"interactive2.prudential-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"prudential-prod\",instance=\"interactive2.prudential-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "interactive2"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"prudential-prod\",instance=\"scaler0.prudential-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"prudential-prod\",instance=\"scaler0.prudential-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler0"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"prudential-prod\",instance=\"scaler1.prudential-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"prudential-prod\",instance=\"scaler1.prudential-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler1"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"prudential-prod\",instance=\"scaler2.prudential-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"prudential-prod\",instance=\"scaler2.prudential-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler2"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"prudential-prod\",instance=\"scaler3.prudential-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"prudential-prod\",instance=\"scaler3.prudential-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler3"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"prudential-prod\",instance=\"scaler4.prudential-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"prudential-prod\",instance=\"scaler4.prudential-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler4"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"prudential-prod\",instance=\"monitoring.prudential-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"prudential-prod\",instance=\"monitoring.prudential-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "monitoring"
      }
     ]
    },
    {
     "title": "Disk Space Used Monitoring VM",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 152 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"monitoring.*\", instanceName=\"prudential-prod\", prodice!~'rootfs', mountpoint!=\"/mnt/hmstemp\"} * 100) / node_filesystem_size_bytes{instance=~\"monitoring.*\", instanceName=\"prudential-prod\", prodice!~'rootfs', mountpoint!=\"/mnt/hmstemp\"})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Interactive 0 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 152 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive0.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive0.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Interactive 1 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 152 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive1.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive1.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Interactive 2 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 162 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"interactive2.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"interactive2.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 0 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 162 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler0.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler0.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 1 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 162 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler1.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler1.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 2 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 172 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler2.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler2.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 3 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 172 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler3.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler3.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 4 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 172 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler4.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler4.prudential-prod.quadient.cloud:9100\", instanceName=\"prudential-prod\",prodice!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler workflows (Job Duration)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 162 },
     "targets": [
      {
       "expr": "hms_scaler_jobDuration{instanceName=\"prudential-prod\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of requests over 3s ",
     "type": "table",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 170 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n  // Filter data for the last 24 hours\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, clientResponseTime_d, serverResponseLatency_s\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count() by RequestType, RequestEndpoint\r\n| render table\r\n",
        "resource": "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-prudential-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-prudential-hub-nonprod",
        "resourceName": "appgw-prudential-nonprod",
        "timeGrain": "auto"
       },
       "subscription": "b3a1bc7c-4424-45f5-8d8d-98db685519b4"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 170 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "BackendSettingsPool",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "TotalRequests",
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-prudential-hub-prod",
        "resourceName": "appgw-prudential-prod",
        "timeGrain": "auto"
       },
       "subscription": "b3a1bc7c-4424-45f5-8d8d-98db685519b4"
      },
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "FailedRequests",
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-prudential-hub-nonprod",
        "resourceName": "appgw-prudential-nonprod",
        "timeGrain": "auto"
       },
       "subscription": "b3a1bc7c-4424-45f5-8d8d-98db685519b4"
      }
     ]
    },
    {
     "title": "SUCCESSFUL - Average Request Time",
     "type": "table",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 177 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and httpStatus_d < 299\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project timeStamp_t, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, timeTaken_d, clientResponseTime_d, serverResponseLatency_s\r\n| summarize RequestCount = count(), AvgTimeTaken = avg(timeTaken_d) by RequestType, RequestStatus, RequestEndpoint\r\n| order by RequestType desc, RequestCount desc",
        "resource": "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-prudential-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-prudential-hub-nonprod",
        "resourceName": "appgw-prudential-nonprod",
        "timeGrain": "auto"
       },
       "subscription": "b3a1bc7c-4424-45f5-8d8d-98db685519b4"
      }
     ]
    },
    {
     "title": "FAILED - Average Request Time",
     "type": "table",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 177 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and httpStatus_d >=300\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project timeStamp_t, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, clientIP_s, host_s, serverRouted_s, instanceId_s, receivedBytes_d, sentBytes_d, timeTaken_d, clientResponseTime_d, serverResponseLatency_s\r\n| summarize RequestCount = count(), AvgTimeTaken = avg(timeTaken_d) by RequestType, RequestStatus, RequestEndpoint\r\n| order by RequestType desc, RequestCount desc",
        "resource": "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-prudential-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-prudential-hub-nonprod",
        "resourceName": "appgw-prudential-nonprod",
        "timeGrain": "auto"
       },
       "subscription": "b3a1bc7c-4424-45f5-8d8d-98db685519b4"
      }
     ]
    },
    {
     "title": "Number of requests over 3s - Detail",
     "type": "table",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 184 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3 // Filter entries with timeTaken_d greater than 3 seconds\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = timeStamp_t, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d, ClientIP = clientIP_s, RecievedBytes = receivedBytes_d, SendBytes = sentBytes_d, ClientResponseTime = clientResponseTime_d, ServerResponseLatency = serverResponseLatency_s\r\n\r\n",
        "resource": "/subscriptions/b3a1bc7c-4424-45f5-8d8d-98db685519b4/resourceGroups/hmsrg-prudential-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-prudential-prod",
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resourceGroup": "hmsrg-prudential-hub-nonprod",
        "resourceName": "appgw-prudential-nonprod",
        "timeGrain": "auto"
       },
       "subscription": "b3a1bc7c-4424-45f5-8d8d-98db685519b4"
      }
     ]
    }
   ]
  },
  {
   "title": "Scalers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed jobs",
     "type": "timeseries",
     "description": "Indicates jobs that failed to process.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{instance=~\"scaler0.prudential-prod.quadient.cloud:30600|scaler1.prudential-prod.quadient.cloud:30600|scaler2.prudential-prod.quadient.cloud:30600|scaler3.prudential-prod.quadient.cloud:30600|scaler4.prudential-prod.quadient.cloud:30600\", status=\"failed\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    {
     "title": "Completed jobs",
     "type": "timeseries",
     "description": "Indicates jobs that have been successfully processed.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{instance=~\"scaler0.prudential-prod.quadient.cloud:30600|scaler1.prudential-prod.quadient.cloud:30600|scaler2.prudential-prod.quadient.cloud:30600|scaler3.prudential-prod.quadient.cloud:30600|scaler4.prudential-prod.quadient.cloud:30600\", status=\"completed\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    {
     "title": "Canceled jobs",
     "type": "timeseries",
     "description": "Indicates jobs that have been successfully processed.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_job_runs_total{status=\"canceled\", instance=~\"scaler0.prudential-prod.quadient.cloud:30600|scaler1.prudential-prod.quadient.cloud:30600|scaler2.prudential-prod.quadient.cloud:30600|scaler3.prudential-prod.quadient.cloud:30600|scaler4.prudential-prod.quadient.cloud:30600\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    {
     "title": "Processing jobs",
     "type": "timeseries",
     "description": "Provides the number of all the jobs that are currently being processed.\nUse this metric to create custom alerts about the number of currently processed jobs that is rapidly growing. That could indicate issues, for example, with jobs being stuck in a loop in the Script workflow module.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(scaler_processing_jobs_total{instance=~\"scaler0.prudential-prod.quadient.cloud:30600|scaler1.prudential-prod.quadient.cloud:30600|scaler2.prudential-prod.quadient.cloud:30600|scaler3.prudential-prod.quadient.cloud:30600|scaler4.prudential-prod.quadient.cloud:30600\"}[5m])",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Average IPS Queue Waiting Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(scaler_processing_jobs_total{instance=~\"scaler0.prudential-prod.quadient.cloud:30600|scaler1.prudential-prod.quadient.cloud:30600|scaler2.prudential-prod.quadient.cloud:30600|scaler3.prudential-prod.quadient.cloud:30600|scaler4.prudential-prod.quadient.cloud:30600\"}[5m])",
       "legendFormat": "{{instance}}/{{group}}"
      }
     ]
    },
    {
     "title": "Scaler workflows",
     "type": "timeseries",
     "description": "Provides the number of deployed workflows for each workflow type, and for each of the following statuse",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "scaler_deployed_workflows_total{instance=~\"scaler0.prudential-prod.quadient.cloud:30600|scaler1.prudential-prod.quadient.cloud:30600|scaler2.prudential-prod.quadient.cloud:30600|scaler3.prudential-prod.quadient.cloud:30600|scaler4.prudential-prod.quadient.cloud:30600\"}",
       "legendFormat": "{{instance}}/{{ group }}: {{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of tickets",
     "type": "timeseries",
     "description": "Number of tickets created since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 145 },
     "targets": [
      {
       "expr": "II_CreatedTicketsCount_total{instance=~\"interactive0.prudential-prod.quadient.cloud:30701|interactive1.prudential-prod.quadient.cloud:30701|interactive2.prudential-prod.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IPS call errors",
     "type": "timeseries",
     "description": "Number of IPS calls made ending in errors since Interactive startup.\nNumber of IPS calls ending in a timeout made since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 145 },
     "targets": [
      {
       "expr": "rate(II_IPSCallExceptionCount_total{instance=~\"interactive0.prudential-prod.quadient.cloud:30701|interactive1.prudential-prod.quadient.cloud:30701|interactive2.prudential-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "IPS Call Expections/{{instance}}"
      }
     ]
    },
    {
     "title": "Interactive requests & errors",
     "type": "timeseries",
     "description": "Number of user synchronization errors since Interactive startup.\nNumber of REST/SOAP requests received since Interactive startup.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 145 },
     "targets": [
      {
       "expr": "increase(II_InteractiveError{instance=~\"interactive0.prudential-prod.quadient.cloud:30701|interactive1.prudential-prod.quadient.cloud:30701|interactive2.prudential-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Errors/{{instance}}/{{Type}}"
      },
      {
       "expr": "increase(II_InteractiveRequest_count{instance=~\"interactive0.prudential-prod.quadient.cloud:30701|interactive1.prudential-prod.quadient.cloud:30701|interactive2.prudential-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Requests/{{instance}}"
      },
      {
       "expr": "increase(II_InteractiveRequestExceptionCount{instance=~\"interactive0.prudential-prod.quadient.cloud:30701|interactive1.prudential-prod.quadient.cloud:30701|interactive2.prudential-prod.quadient.cloud:30701\"}[5m])",
       "legendFormat": "II Errors/{{instance}}/Requests"
      }
     ]
    },
    {
     "title": "Number of users",
     "type": "timeseries",
     "description": "Number of currently logged in users (active session only).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 153 },
     "targets": [
      {
       "expr": "II_DBSessions{instance=~\"interactive0.prudential-prod.quadient.cloud:30701|interactive1.prudential-prod.quadient.cloud:30701|interactive2.prudential-prod.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Drafts and Tickets",
     "type": "timeseries",
     "description": "Number of currently active drafts and tickets, and drafts and tickets that are marked for deletion. Numbers are grouped by: active drafts, drafts marked for deletion, active tickets, tickets marked for deletion.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 153 },
     "targets": [
      {
       "expr": "II_DBData{instance=~\"interactive0.prudential-prod.quadient.cloud:30701|interactive1.prudential-prod.quadient.cloud:30701|interactive2.prudential-prod.quadient.cloud:30701\"}",
       "legendFormat": "{{instance}}/{{ObjectType}}/{{State}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "Number of currently active and idle Interactive connections to the database.\nNumber of currently active and idle Interactive connections to Inspire Content Manager (ICM).\n\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 153 },
     "targets": [
      {
       "expr": "II_DBConnections{instance=~\"interactive0.prudential-prod.quadient.cloud:30701|interactive1.prudential-prod.quadient.cloud:30701|interactive2.prudential-prod.quadient.cloud:30701\"}",
       "legendFormat": "DB {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_ICMConnections{instance=~\"interactive0.prudential-prod.quadient.cloud:30701|interactive1.prudential-prod.quadient.cloud:30701|interactive2.prudential-prod.quadient.cloud:30701\"}",
       "legendFormat": "ICM {{instance}}/{{Connection}}"
      },
      {
       "expr": "II_IPSConnections{instance=~\"interactive0.prudential-prod.quadient.cloud:30701|interactive1.prudential-prod.quadient.cloud:30701|interactive2.prudential-prod.quadient.cloud:30701\"}",
       "legendFormat": "IPS {{instance}}/{{Connection}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scaler JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler heap used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Prudential\",area=\"heap\",instance=\"scaler0.prudential-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Prudential\",area=\"heap\",instance=\"scaler0.prudential-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 0"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Prudential\",area=\"heap\",instance=\"scaler1.prudential-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Prudential\",area=\"heap\",instance=\"scaler1.prudential-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 1"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Prudential\",area=\"heap\",instance=\"scaler2.prudential-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Prudential\",area=\"heap\",instance=\"scaler2.prudential-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 2"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Prudential\",area=\"heap\",instance=\"scaler3.prudential-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Prudential\",area=\"heap\",instance=\"scaler3.prudential-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 3"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Prudential\",area=\"heap\",instance=\"scaler4.prudential-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Prudential\",area=\"heap\",instance=\"scaler4.prudential-prod.quadient.cloud:30600\"})",
       "legendFormat": "Scaler 4"
      }
     ]
    },
    {
     "title": "Scaler start time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{customerName=\"Prudential\",job=\"prudential-prod-scaler-vm\"}*1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Heap Scaler",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler0.prudential-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler0.prudential-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.prudential-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler1.prudential-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler1.prudential-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.prudential-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"scaler2.prudential-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler2.prudential-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"scaler2.prudential-prod.quadient.cloud:30600\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Scaler thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler0.prudential-prod.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler1.prudential-prod.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"scaler2.prudential-prod.quadient.cloud:30600\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactive JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactive heap used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Prudential\",area=\"heap\",instance=\"interactive0.prudential-prod.quadient.cloud:30701\"})*100/sum(jvm_memory_bytes_max{customerName=\"Prudential\",area=\"heap\",instance=\"interactive0.prudential-prod.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 0"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Prudential\",area=\"heap\",instance=\"interactive1.prudential-prod.quadient.cloud:30701\",instanceName=\"prudential-prod\"})*100/sum(jvm_memory_bytes_max{customerName=\"Prudential\",area=\"heap\",instance=\"interactive1.prudential-prod.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 1"
      },
      {
       "expr": "sum(jvm_memory_bytes_used{customerName=\"Prudential\",area=\"heap\",instance=\"interactive2.prudential-prod.quadient.cloud:30701\",instanceName=\"prudential-prod\"})*100/sum(jvm_memory_bytes_max{customerName=\"Prudential\",area=\"heap\",instance=\"interactive2.prudential-prod.quadient.cloud:30701\"})",
       "legendFormat": "Interactive 2"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 0",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive0.prudential-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive0.prudential-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive0.prudential-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Interactive 1 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive1.prudential-prod.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Interactive 2 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive2.prudential-prod.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Interactive start time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{customerName=\"Prudential\",job=\"prudential-prod-interactive-vm\"}*1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Interactive 0 thread states",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(state) (jvm_threads_state{instance=\"interactive0.prudential-prod.quadient.cloud:30701\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 1",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive1.prudential-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive1.prudential-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive1.prudential-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Heap Interactive 2",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_bytes_used{instance=\"interactive2.prudential-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_bytes_committed{instance=\"interactive2.prudential-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{instance=\"interactive2.prudential-prod.quadient.cloud:30701\",area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 148 },
     "targets": [
      {
       "expr": "{job=\"scalerlogs\"}"
      }
     ]
    },
    {
     "title": "Scaler ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
     "targets": [
      {
       "expr": "{instance=~\"scaler2.prudential-prod.quadient.cloud|scaler1.prudential-prod.quadient.cloud|scaler0.prudential-prod.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Scaler IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
     "targets": [
      {
       "expr": "{instance=~\"scaler0.prudential-prod.quadient.cloud|scaler2.prudential-prod.quadient.cloud|scaler1.prudential-prod.quadient.cloud\", job=\"ipslogs\"}"
      }
     ]
    },
    {
     "title": "Scaler Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 169 },
     "targets": [
      {
       "expr": "{job=\"scalersenlogs\"}"
      }
     ]
    },
    {
     "title": "Interactive Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 182 },
     "targets": [
      {
       "expr": "{job=\"interactivelogs\"}"
      }
     ]
    },
    {
     "title": "Interactive ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.prudential-prod.quadient.cloud|interactive1.prudential-prod.quadient.cloud\", job=\"icmlogs\"}"
      }
     ]
    },
    {
     "title": "Interactive  IPS Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
     "targets": [
      {
       "expr": "{instance=~\"interactive0.prudential-prod.quadient.cloud|interactive1.prudential-prod.quadient.cloud\", job=\"ipslogs\"}"
      }
     ]
    }
   ]
  }
 ]
}