{
 "title": "Unqork-PROD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server's Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Automation traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\".*vm\", instanceName=\"unqork-prod\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat",
   "type": "stat",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"unqork-prod\", environment=\"prod1\"}",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  {
   "title": "Inspire heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 22, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"unqork-prod\", instance!~\"monitoring.*\"}) or (0 * sum_over_time(node_systemd_unit_state{state=\"active\", name=~\"Inspire.*service\", instanceName=\"unqork-prod\", instance!~\"monitoring.*\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}: {{ name}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 28, "w": 7, "x": 17, "y": 1 } },
  {
   "title": "Server's Percentage Availability",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (up{job=~\".*vm\", instanceName=\"unqork-prod\"}) or (0 * sum_over_time(up{job=~\".*vm\", instanceName=\"unqork-prod\"}[$__range])))[$__range:1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RHEL security updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "hms_dnf{instanceName=\"unqork-prod\",type=~\"Critical|Important|Moderate\"}",
     "legendFormat": "{{job}}:{{type}}"
    }
   ]
  },
  { "title": "Shared Panels", "type": "dashlist", "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 } },
  {
   "title": "Scaler File Share Sync Failure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_status_failed{job_name=~\"cron-job-azsync-unqork-prod-scaler-.+\"} >=1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Daily (Monday - Saturday)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_backup_info_daily_all{instanceName=\"unqork-prod\",backupType=\"daily\"})"
    }
   ]
  },
  {
   "title": "All Weekly (4 Sundays)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_backup_info_weekly_all{instanceName=\"unqork-prod\",backupType=\"weekly\"})"
    }
   ]
  },
  {
   "title": "Scaler File Share Sync Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_status_active{job_name=~\"cron-job-azsync-unqork-prod-scaler-.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Audit Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hms_audit_log{instance=\"monitoring.unqork-prod.quadient.cloud:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backups Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Daily VM/Disk Azure backup",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h) \r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
      "resource": "/subscriptions/c6400c42-d154-4e54-b595-70ef444f066a/resourceGroups/hmsrg-unqork-hub-prod/providers/Microsoft.RecoveryServices/vaults/rsv-unqork-prod",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Azure VM/Disks backup health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 30 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(7d)\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
      "resource": "/subscriptions/de74e022-0016-4972-ac5a-d17f177ed92d/resourceGroups/hmsrg-gfbank-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-gfbank-nonprod",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       {
        "dimension": "healthStatus",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "backupInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "BackupHealthEvent",
      "metricNamespace": "microsoft.recoveryservices/vaults",
      "resourceGroup": "hmsrg-unqork-hub-prod",
      "resourceName": "rsv-unqork-prod",
      "timeGrain": "auto"
     },
     "subscription": "c6400c42-d154-4e54-b595-70ef444f066a"
    }
   ]
  },
  {
   "title": "Daily (Monday - Saturday)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hms_backup_info_daily_all{containerName=~\".*db$\",instanceName=\"unqork-prod\",backupType=\"daily\"}",
     "legendFormat": "{{backupItem}}-database"
    }
   ]
  },
  {
   "title": "Weekly (4 Sundays)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hms_backup_info_weekly_all{containerName=~\".*db$\",instanceName=\"unqork-prod\",backupType=\"weekly\"}",
     "legendFormat": "{{backupItem}}-database"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler0.unqork-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler0"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler1.unqork-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler1"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler2.unqork-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler2"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler3.unqork-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler3"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"scaler4.unqork-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "scaler4"
      },
      {
       "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"monitoring.unqork-prod.quadient.cloud:9100\"}[5m])) * 100)",
       "legendFormat": "monitoring"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"^(.*?)unqork-prod.quadient.cloud:9100\"}[5m])",
       "legendFormat": "{{instance}} recv {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"^(.*?)unqork-prod.quadient.cloud:9100\"}[5m])",
       "legendFormat": "{{instance}} trans {{device}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"unqork-prod\",instance=\"scaler0.unqork-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"unqork-prod\",instance=\"scaler0.unqork-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler0"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"unqork-prod\",instance=\"scaler1.unqork-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"unqork-prod\",instance=\"scaler1.unqork-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler1"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"unqork-prod\",instance=\"scaler2.unqork-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"unqork-prod\",instance=\"scaler2.unqork-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler2"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"unqork-prod\",instance=\"scaler3.unqork-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"unqork-prod\",instance=\"scaler3.unqork-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler3"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"unqork-prod\",instance=\"scaler4.unqork-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"unqork-prod\",instance=\"scaler4.unqork-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "scaler4"
      },
      {
       "expr": "100 - ({__name__=~\"node_memory_MemAvailable_bytes\", instanceName=\"unqork-prod\",instance=\"monitoring.unqork-prod.quadient.cloud:9100\"} / {__name__=~\"node_memory_MemTotal_bytes\", instanceName=\"unqork-prod\",instance=\"monitoring.unqork-prod.quadient.cloud:9100\"})*100",
       "legendFormat": "monitoring"
      }
     ]
    },
    {
     "title": "Disk Space Used Monitoring VM",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"monitoring.*\", instanceName=\"unqork-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"monitoring.*\", instanceName=\"unqork-prod\",device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 0 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler0.unqork-prod.quadient.cloud:9100\", instanceName=\"unqork-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler0.unqork-prod.quadient.cloud:9100\", instanceName=\"unqork-prod\",device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 1 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler1.unqork-prod.quadient.cloud:9100\", instanceName=\"unqork-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler1.unqork-prod.quadient.cloud:9100\", instanceName=\"unqork-prod\",device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 2 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler2.unqork-prod.quadient.cloud:9100\", instanceName=\"unqork-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler2.unqork-prod.quadient.cloud:9100\", instanceName=\"unqork-prod\",device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 3 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler3.unqork-prod.quadient.cloud:9100\", instanceName=\"unqork-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler3.unqork-prod.quadient.cloud:9100\", instanceName=\"unqork-prod\",device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used Scaler 4 VM",
     "type": "bargauge",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"scaler4.unqork-prod.quadient.cloud:9100\", instanceName=\"unqork-prod\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"scaler4.unqork-prod.quadient.cloud:9100\", instanceName=\"unqork-prod\",device!~'rootfs'})",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  { "title": "Scalers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Failed jobs",
   "type": "timeseries",
   "description": "Indicates jobs that failed to process.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_job_runs_total{instance=~\"scaler0.unqork-prod.quadient.cloud:30600|scaler1.unqork-prod.quadient.cloud:30600|scaler2.unqork-prod.quadient.cloud:30600|scaler3.unqork-prod.quadient.cloud:30600|scaler4.unqork-prod.quadient.cloud:30600\", status=\"failed\"}[5m])",
     "legendFormat": "{{instance}}/{{group}}"
    }
   ]
  },
  {
   "title": "Completed jobs",
   "type": "timeseries",
   "description": "Indicates jobs that have been successfully processed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_job_runs_total{instance=~\"scaler0.unqork-prod.quadient.cloud:30600|scaler1.unqork-prod.quadient.cloud:30600|scaler2.unqork-prod.quadient.cloud:30600|scaler3.unqork-prod.quadient.cloud:30600|scaler4.unqork-prod.quadient.cloud:30600\", status=\"completed\"}[5m])",
     "legendFormat": "{{instance}}/{{group}}"
    }
   ]
  },
  {
   "title": "Canceled jobs",
   "type": "timeseries",
   "description": "Indicates jobs that have been successfully processed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_job_runs_total{status=\"canceled\", instance=~\"scaler0.unqork-prod.quadient.cloud:30600|scaler1.unqork-prod.quadient.cloud:30600|scaler2.unqork-prod.quadient.cloud:30600|scaler3.unqork-prod.quadient.cloud:30600|scaler4.unqork-prod.quadient.cloud:30600\"}[5m])",
     "legendFormat": "{{instance}}/{{group}}"
    }
   ]
  },
  {
   "title": "Processing jobs",
   "type": "timeseries",
   "description": "Provides the number of all the jobs that are currently being processed.\nUse this metric to create custom alerts about the number of currently processed jobs that is rapidly growing. That could indicate issues, for example, with jobs being stuck in a loop in the Script workflow module.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(scaler_processing_jobs_total{instance=~\"scaler0.unqork-prod.quadient.cloud:30600|scaler1.unqork-prod.quadient.cloud:30600|scaler2.unqork-prod.quadient.cloud:30600|scaler3.unqork-prod.quadient.cloud:30600|scaler4.unqork-prod.quadient.cloud:30600\"}[5m])",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Average IPS Queue Waiting Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(scaler_processing_jobs_total{instance=~\"scaler0.unqork-prod.quadient.cloud:30600|scaler1.unqork-prod.quadient.cloud:30600|scaler2.unqork-prod.quadient.cloud:30600|scaler3.unqork-prod.quadient.cloud:30600|scaler4.unqork-prod.quadient.cloud:30600\"}[5m])",
     "legendFormat": "{{instance}}/{{group}}"
    }
   ]
  },
  {
   "title": "Scaler workflows",
   "type": "timeseries",
   "description": "Provides the number of deployed workflows for each workflow type, and for each of the following statuse",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scaler_deployed_workflows_total{instance=~\"scaler0.unqork-prod.quadient.cloud:30600|scaler1.unqork-prod.quadient.cloud:30600|scaler2.unqork-prod.quadient.cloud:30600|scaler3.unqork-prod.quadient.cloud:30600|scaler4.unqork-prod.quadient.cloud:30600\"}",
     "legendFormat": "{{instance}}/{{ group }}: {{ status }}"
    }
   ]
  },
  { "title": "Scaler JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Scaler heap used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"heap\",instance=\"scaler0.unqork-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Unqork\",area=\"heap\",instance=\"scaler0.unqork-prod.quadient.cloud:30600\"})",
     "legendFormat": "Scaler 0"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"Unqork\",area=\"heap\",instance=\"scaler1.unqork-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Unqork\",area=\"heap\",instance=\"scaler1.unqork-prod.quadient.cloud:30600\"})",
     "legendFormat": "Scaler 1"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"Unqork\",area=\"heap\",instance=\"scaler2.unqork-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Unqork\",area=\"heap\",instance=\"scaler2.unqork-prod.quadient.cloud:30600\"})",
     "legendFormat": "Scaler 2"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"Unqork\",area=\"heap\",instance=\"scaler3.unqork-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Unqork\",area=\"heap\",instance=\"scaler3.unqork-prod.quadient.cloud:30600\"})",
     "legendFormat": "Scaler 3"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{customerName=\"Unqork\",area=\"heap\",instance=\"scaler4.unqork-prod.quadient.cloud:30600\"})*100/sum(jvm_memory_bytes_max{customerName=\"Unqork\",area=\"heap\",instance=\"scaler4.unqork-prod.quadient.cloud:30600\"})",
     "legendFormat": "Scaler 4"
    }
   ]
  },
  {
   "title": "Scaler start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{customerName=\"Unqork\",job=\"unqork-prod-scaler-vm\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Heap Scaler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"scaler0.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler0.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"scaler1.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler1.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"scaler0.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"scaler2.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler2.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"scaler2.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"scaler3.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler3.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"scaler3.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"scaler4.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"scaler4.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"scaler4.unqork-prod.quadient.cloud:30600\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Scaler thread states",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"scaler0.unqork-prod.quadient.cloud:30600\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"scaler1.unqork-prod.quadient.cloud:30600\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"scaler2.unqork-prod.quadient.cloud:30600\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"scaler3.unqork-prod.quadient.cloud:30600\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by(state) (jvm_threads_state{instance=\"scaler4.unqork-prod.quadient.cloud:30600\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Scaler Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "{job=\"scalerlogs\"}"
    }
   ]
  },
  {
   "title": "Scaler ICM Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "{instance=~\"scaler4.unqork-prod.quadient.cloud|scaler3.unqork-prod.quadient.cloud|scaler2.unqork-prod.quadient.cloud|scaler1.unqork-prod.quadient.cloud|scaler0.unqork-prod.quadient.cloud\", job=\"icmlogs\"}"
    }
   ]
  },
  {
   "title": "Scaler IPS Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "{instance=~\"scaler0.unqork-prod.quadient.cloud|scaler1.unqork-prod.quadient.cloud|scaler2.unqork-prod.quadient.cloud|scaler3.unqork-prod.quadient.cloud|scaler4.unqork-prod.quadient.cloud\", job=\"ipslogs\"}"
    }
   ]
  }
 ]
}