{
 "title": "Fidelity LOGS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "qmsInstanceName", "label": "QMS Instance name", "query": "fmr-dev, fmr-prod, fmr-qa" },
   { "name": "qmsDatasource", "label": "QMS Datasource", "query": "prometheus" },
   { "name": "lokiInstance", "label": "Loki Instance", "query": "loki" },
   { "name": "qmsDomainSuffix", "query": ".quadient.cloud" },
   { "name": "qmsCustomerName", "query": "Fidelity" }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 } },
    { "gridPos": { "h": 9, "w": 24, "x": 0, "y": 597 } },
    { "gridPos": { "h": 8, "w": 15, "x": 0, "y": 606 } },
    { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 14, "w": 9, "x": 15, "y": 606 } },
    { "gridPos": { "h": 3, "w": 5, "x": 0, "y": 614 } },
    { "gridPos": { "h": 3, "w": 5, "x": 5, "y": 614 } },
    { "gridPos": { "h": 3, "w": 5, "x": 10, "y": 614 } }
   ]
  },
  {
   "title": "Backups Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 } },
    { "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 } },
    { "gridPos": { "h": 5, "w": 6, "x": 0, "y": 397 } },
    { "gridPos": { "h": 5, "w": 6, "x": 6, "y": 397 } },
    { "gridPos": { "h": 5, "w": 6, "x": 12, "y": 397 } },
    { "gridPos": { "h": 5, "w": 6, "x": 18, "y": 397 } },
    { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 402 } },
    { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 402 } }
   ]
  },
  { "title": "Splunk Forwarder Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 } },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 } },
    { "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 } },
    { "gridPos": { "h": 33, "w": 8, "x": 16, "y": 12 } },
    { "gridPos": { "h": 10, "w": 8, "x": 0, "y": 212 } },
    { "gridPos": { "h": 10, "w": 8, "x": 8, "y": 212 } },
    { "gridPos": { "h": 13, "w": 16, "x": 0, "y": 222 } }
   ]
  },
  {
   "title": "Application Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 } },
    { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 } },
    { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 } },
    { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 } },
    { "gridPos": { "h": 7, "w": 24, "x": 0, "y": 196 } }
   ]
  },
  {
   "title": "Scalers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 } },
    { "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 } },
    { "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 } },
    { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 } },
    { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 } },
    { "gridPos": { "h": 8, "w": 8, "x": 0, "y": 173 } },
    { "gridPos": { "h": 8, "w": 8, "x": 8, "y": 173 } },
    { "gridPos": { "h": 8, "w": 8, "x": 16, "y": 173 } }
   ]
  },
  {
   "title": "Interactives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 } },
    { "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 } },
    { "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 } },
    { "gridPos": { "h": 8, "w": 8, "x": 0, "y": 150 } },
    { "gridPos": { "h": 8, "w": 8, "x": 8, "y": 150 } },
    { "gridPos": { "h": 8, "w": 8, "x": 16, "y": 150 } }
   ]
  },
  {
   "title": "Scaler JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 } },
    { "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 } },
    { "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 } },
    { "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 } }
   ]
  },
  {
   "title": "Interactive JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    { "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 } },
    { "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 } },
    { "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 } },
    { "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 } }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scaler Logs",
     "type": "logs",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "{job=\"scalerlogs\"}",
       "maxLines": 5000
      }
     ]
    },
    {
     "title": "Scaler ICM Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "{instance=~\"scaler2.$qmsInstanceName$qmsDomainSuffix|scaler1.$qmsInstanceName$qmsDomainSuffix|scaler0.$qmsInstanceName$qmsDomainSuffix\", job=\"icmlogs\"}"
      }
     ]
    },
    { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 } },
    { "gridPos": { "h": 13, "w": 24, "x": 0, "y": 66 } },
    { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 } },
    { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 } }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Heap memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{job=\"scalerlogs\"} |= `HealthMonitor` | pattern `<_> heap.memory.used/total=<heap_memory>%,`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Heap memory usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"scalerlogs\"} |= `HealthMonitor` | pattern `<_> heap.memory.used/total=<heap_memory>%,`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Minor gc time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"scalerlogs\"} |= `HealthMonitor` | pattern `<_>, minor.gc.time=<minor_time>ms`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Minor gc count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "{job=\"scalerlogs\"} |= `HealthMonitor` |= `gc.count` | pattern `<_>, minor.gc.count=<minor_count>,`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Load system",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "{job=\"scalerlogs\"} |= `HealthMonitor` | pattern `<_> load.system=<load_system>%`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Load process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "{job=\"scalerlogs\"} |= `HealthMonitor` | pattern `<_> load.process=<load_process>%`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Physical memory free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "G" } },
   "targets": [
    {
     "expr": "{job=\"scalerlogs\"} |= `HealthMonitor` | pattern `<_> physical.memory.free=<physical_memory_free>G,`",
     "maxLines": 5000
    }
   ]
  }
 ]
}