{
 "title": "CNJDOH QAR",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "qmsInstanceName",
    "label": "QMS Instance name",
    "query": "cnjdoh-qar-nonprod, cnjdoh-qar-prod"
   },
   { "name": "qmsDatasource", "label": "QMS Datasource", "query": "prometheus" },
   { "name": "lokiInstance", "label": "Loki Instance", "query": "loki" },
   { "name": "qmsDomainSuffix", "label": "QMS Domain Suffix", "query": ".gov.quadient.cloud" },
   { "name": "qmsInstanceNameQarNonProd", "query": "caldhr-qar-nonprod" },
   { "name": "qmsCustomerName", "label": "QMS Customer Name", "query": "C-NJ-DOH" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job,instance_name, customerName, projectName, issueKey, environment) (irate(windows_cpu_time_total{mode=\"idle\",instanceName=\"$qmsInstanceName\"}[5m])) * 100)",
     "legendFormat": "scalerqar"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (windows_os_virtual_memory_free_bytes{instanceName=\"$qmsInstanceName\"} / windows_os_virtual_memory_bytes{instanceName=\"$qmsInstanceName\"})*100",
     "legendFormat": "scalerqar"
    }
   ]
  },
  { "title": "QAR NON-PROD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "QAR heartbeat",
   "type": "stat",
   "description": "Check the application's availability using ping and the application's health status API. \nNOTE: The monitoring server needs to be ON to show other metrics properly. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_service_state{instanceName=\"$qmsInstanceName\",state=\"running\", name=~\"OnDemand.*|MSSQLSERVER\"}",
     "legendFormat": "{{instanceName}}: {{ name}}"
    }
   ]
  },
  {
   "title": "QAR heartbeat percentage",
   "type": "stat",
   "description": "NOTE: The monitoring server needs to be ON to show Scaler and Interactive traffic lights properly. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum without() (windows_service_state{state=\"running\", name=~\"OnDemand.*|MSSQLSERVER\", instanceName=\"$qmsInstanceName\"}) or (0 * sum_over_time(windows_service_state{state=\"running\", name=~\"OnDemand.*|MSSQLSERVER\", instanceName=\"$qmsInstanceName\"}[$__range])))[$__range:$__interval]) * 100",
     "legendFormat": "{{instanceName}}: {{ name}}"
    }
   ]
  },
  { "title": "Scaler QAR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  { "title": "Failed jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 } },
  { "title": "Completed jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 } },
  { "title": "Canceled jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 } },
  {
   "title": "Scaler Jobs per Workflow (Completed)",
   "type": "library-panel-ref",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 }
  },
  {
   "title": "Scaler QAR workflows (Job Duration)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hms_scaler_jobDuration{instanceName=\"$qmsInstanceName\"}",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  { "title": "Processing jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 } },
  { "title": "Average IPS Queue Waiting Time", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 } },
  { "title": "Scaler workflows", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 } },
  {
   "title": "Scaler JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    { "title": "Scaler heap used", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 44 } },
    { "title": "Panel Title", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 3, "y": 44 } },
    { "title": "Panel Title", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 7, "x": 9, "y": 44 } },
    { "title": "Panel Title", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 } }
   ]
  }
 ]
}