{
 "title": "DESJARDINS main",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "qmsInstanceName",
    "label": "QMS Instance name",
    "query": "desjardins-predev,desjardins-dev,desjardins-staging,desjardins-certif,desjardins-prod"
   },
   { "name": "qmsDatasource", "label": "QMS Datasource", "query": "prometheus" },
   { "name": "lokiInstance", "label": "Loki Instance", "query": "loki" },
   { "name": "qmsDomainSuffix", "query": ".quadient.cloud" },
   { "name": "qmsCustomerName", "query": "DESJARDINS" }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Linux VM Overview", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 } },
    { "title": "Inspire heartbeat", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 } },
    { "title": "RHEL security updates", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 15, "x": 0, "y": 86 } },
    { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 14, "w": 9, "x": 15, "y": 86 } },
    {
     "title": "Number of requests over 30m NONPROD",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "mode": "raw",
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 1800 // 1800 seconds = 30 minutes\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = TimeGenerated, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()\r\n",
        "resources": [
         "/subscriptions/2c83fb0e-d801-4451-b6f2-c0fa060c963d/resourceGroups/hmsrg-desjardins-hub-nonprod/providers/Microsoft.Network/applicationGateways/appgw-desjardins-nonprod"
        ],
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resources": [
         { "resourceGroup": "hmsrg-desjardins-hub-nonprod", "resourceName": "appgw-desjardins-nonprod" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "2c83fb0e-d801-4451-b6f2-c0fa060c963d"
      }
     ]
    },
    {
     "title": "Number of requests over 3s NONPROD",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "mode": "raw",
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = TimeGenerated, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()\r\n",
        "resources": [
         "/subscriptions/2c83fb0e-d801-4451-b6f2-c0fa060c963d/resourceGroups/hmsrg-desjardins-hub-nonprod/providers/Microsoft.Network/applicationGateways/appgw-desjardins-nonprod"
        ],
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resources": [
         { "resourceGroup": "hmsrg-desjardins-hub-nonprod", "resourceName": "appgw-desjardins-nonprod" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "2c83fb0e-d801-4451-b6f2-c0fa060c963d"
      }
     ]
    },
    { "title": "Audit Logs", "type": "library-panel-ref", "gridPos": { "h": 3, "w": 5, "x": 10, "y": 94 } },
    {
     "title": "Number of requests over 30m PROD",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "mode": "raw",
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 1800 // 1800 seconds = 30 minutes\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = TimeGenerated, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()\r\n",
        "resources": [
         "/subscriptions/2c83fb0e-d801-4451-b6f2-c0fa060c963d/resourceGroups/hmsrg-desjardins-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-desjardins-prod"
        ],
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resources": [
         { "resourceGroup": "hmsrg-desjardins-hub-nonprod", "resourceName": "appgw-desjardins-nonprod" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "2c83fb0e-d801-4451-b6f2-c0fa060c963d"
      }
     ]
    },
    {
     "title": "Number of requests over 3s PROD",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "mode": "raw",
        "query": "AzureDiagnostics\r\n| where ResourceType == \"APPLICATIONGATEWAYS\"\r\n    and OperationName == \"ApplicationGatewayAccess\"\r\n    and (httpMethod_s == \"POST\" or httpMethod_s == \"GET\")\r\n    and requestUri_s startswith \"/rest/api/\"\r\n    and timeTaken_d > 3\r\n    and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| project TimeStamp = TimeGenerated, TimeTaken = timeTaken_d, RequestType = httpMethod_s, RequestEndpoint = requestUri_s, RequestStatus = httpStatus_d\r\n| sort by TimeTaken desc\r\n| summarize RequestCount = count()\r\n",
        "resources": [
         "/subscriptions/2c83fb0e-d801-4451-b6f2-c0fa060c963d/resourceGroups/hmsrg-desjardins-hub-prod/providers/Microsoft.Network/applicationGateways/appgw-desjardins-prod"
        ],
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "dimensionFilters": [],
        "metricNamespace": "microsoft.network/applicationgateways",
        "resources": [
         { "resourceGroup": "hmsrg-desjardins-hub-nonprod", "resourceName": "appgw-desjardins-nonprod" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "2c83fb0e-d801-4451-b6f2-c0fa060c963d"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily VM/Disk Azure backup",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 132 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "AddonAzureBackupJobs\r\n| where JobOperation==\"Backup\"\r\n| summarize arg_max(TimeGenerated,*) by JobUniqueId\r\n| where JobStatus==\"Completed\"\r\n| join kind=inner\r\n(\r\n    CoreAzureBackup\r\n    | where OperationName == \"BackupItem\"\r\n    | where BackupItemType ==\"VM\" and BackupManagementType==\"IaaSVM\"\r\n    | distinct BackupItemUniqueId, BackupItemFriendlyName\r\n)\r\non BackupItemUniqueId\r\n| where JobStartDateTime > ago(24h)\r\n    and not(\r\n        BackupItemFriendlyName1 contains \"test\" or\r\n        BackupItemFriendlyName1 contains \"qa\"\r\n    )\r\n| project BackupItemFriendlyName1, JobOperation, JobStatus, JobStartDateTime",
        "resources": [
         "/subscriptions/2c83fb0e-d801-4451-b6f2-c0fa060c963d/resourceGroups/hmsrg-desjardins-hub-prod/providers/Microsoft.RecoveryServices/vaults/rsv-desjardins-prod"
        ],
        "resultFormat": "table"
       },
       "azureMonitor": {
        "allowedTimeGrainsMs": [],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Azure VM/Disks backup health",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 132 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "",
        "resources": [
         "/subscriptions/2c83fb0e-d801-4451-b6f2-c0fa060c963d/resourceGroups/hmsrg-desjardins-hub-nonprod/providers/Microsoft.RecoveryServices/vaults/rsv-desjardins-nonprod"
        ]
       },
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "healthStatus",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "dataSourceType",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "backupInstanceName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "BackupHealthEvent",
        "metricNamespace": "microsoft.recoveryservices/vaults",
        "region": "germanywestcentral",
        "resources": [
         {
          "metricNamespace": "Microsoft.RecoveryServices/vaults",
          "region": "germanywestcentral",
          "resourceGroup": "hmsrg-desjardins-hub-prod",
          "resourceName": "rsv-desjardins-prod",
          "subscription": "2c83fb0e-d801-4451-b6f2-c0fa060c963d"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "2c83fb0e-d801-4451-b6f2-c0fa060c963d"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "title": "CPU Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 133 } },
    { "title": "Memory Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 8, "y": 133 } },
    { "title": "DiskSpace usage", "type": "library-panel-ref", "gridPos": { "h": 33, "w": 8, "x": 16, "y": 133 } },
    { "title": "Average CPU Usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 143 } },
    { "title": "File Shares usage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 8, "x": 8, "y": 143 } },
    { "title": "Network Traffic", "type": "library-panel-ref", "gridPos": { "h": 13, "w": 16, "x": 0, "y": 153 } }
   ]
  },
  {
   "title": "Automation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Automation Jobs per processor (Completed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 }
    },
    {
     "title": "Automation Jobs per processor (Failed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 }
    },
    {
     "title": "Automation Jobs per Queue (Completed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 90 }
    },
    { "title": "Metrics Last Update (seconds)", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 } },
    {
     "title": "Automation Jobs per Queue (Failed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 98 }
    },
    { "title": "Submodules Errors", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 8, "x": 16, "y": 98 } }
   ]
  },
  {
   "title": "Scalers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    { "title": "Failed jobs  ", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 176 } },
    { "title": "Completed jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 176 } },
    { "title": "Canceled jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 176 } },
    {
     "title": "Scaler Jobs per Workflow (Completed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 }
    },
    {
     "title": "Scaler Jobs per Workflow (Failed)",
     "type": "library-panel-ref",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 }
    },
    { "title": "Processing jobs", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 236 } },
    { "title": "Average IPS Queue Waiting Time", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 236 } },
    { "title": "Scaler workflows", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 236 } }
   ]
  },
  {
   "title": "Interactives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    { "title": "Number of tickets", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 597 } },
    { "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 597 } },
    { "title": "Interactive requests & errors", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 597 } },
    { "title": "Number of users", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 619 } },
    { "title": "Drafts and Tickets", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 619 } },
    { "title": "Connections", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 619 } }
   ]
  },
  {
   "title": "Scaler JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    { "title": "Scaler heap used", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 312 } },
    { "title": "Scaler start time", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 6, "y": 312 } },
    { "title": "JVM Heap Scaler", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 12, "y": 312 } },
    { "title": "Scaler thread states", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 312 } }
   ]
  },
  {
   "title": "Interactive JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    { "title": "Interactive heap used", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 247 } },
    { "title": "Interactive start time", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 6, "y": 247 } },
    { "title": "JVM Heap interactive", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 12, "y": 247 } },
    { "title": "Interactive thread states", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 247 } }
   ]
  }
 ]
}